
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							POTION "USABILITY"
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION revise_potion_use BEGIN

//MAKE POTIONS USABLE BY ANY CLASSES________________________________________________
//
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~
  PATCH_IF (~%SOURCE_SIZE%~ > ~0x71~) BEGIN
	READ_SHORT 0x1c type
	PATCH_IF (%type% = 9) BEGIN // potions
	  WRITE_BYTE 0x1e (THIS BAND 0b00111111)
	  WRITE_BYTE 0x1f (THIS BAND 0b00000000)
	  WRITE_BYTE 0x20 (THIS BAND 0b10000000)
	  WRITE_BYTE 0x21 (THIS BAND 0b10011111)
	END
  END
BUT_ONLY
//__________________________________________________________________________________

END // end function