
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						WPO - MAJOR OVERHAUL
//__________________________________________________________________________________
//__________________________________________________________________________________


//COPY MARKER FILE_________________________________________________________________
//
COPY ~scales_of_balance/profs/d5_profs.d5~ ~override~
//__________________________________________________________________________________


//RESPECT PROFSMAX!_________________________________________________________________
//
ACTION_IF MOD_IS_INSTALLED "TOBEX.TP2" "100" THEN BEGIN
	COPY ~TobEx_ini/TobExTweak.ini~ ~TobEx_ini~
		REPLACE_TEXTUALLY ~Proficiency Restrictions=0~ ~Proficiency Restrictions=1~
	BUT_ONLY
END
//__________________________________________________________________________________


//PROF BONUSES______________________________________________________________________
//
COPY ~scales_of_balance/profs/wspat3.2da~ ~override/wspatck.2da~

COPY ~scales_of_balance/profs/wspecial2.2da~ ~override/wspecial.2da~

COPY ~scales_of_balance/profs/thac0.2da~ ~override~
ACTION_IF GAME_IS ~iwdee tob bgt~ BEGIN
	COPY ~scales_of_balance/profs/profsmax_i.2da~ ~override/profsmax.2da~
END
ACTION_IF GAME_IS ~bgee bg2ee eet~ BEGIN
	COPY ~scales_of_balance/profs/profsmax.2da~ ~override~
END

COPY ~scales_of_balance/profs/profs.2da~ ~override~

COPY ~scales_of_balance/misc/d5_numat.spl~ ~override~
//__________________________________________________________________________________
	

//UPDATE CLASS STRINGS______________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~clastext.2da~) BEGIN
	COPY_EXISTING ~clastext.2da~ ~override~
		SET_2DA_ENTRY 3 4 1 RESOLVE_STR_REF (@1214)
		SET_2DA_ENTRY 8 4 1 RESOLVE_STR_REF (@1215)
		SET_2DA_ENTRY 16 4 1 RESOLVE_STR_REF (@1216)
		SET_2DA_ENTRY 25 4 1 RESOLVE_STR_REF (@1217)
		SET_2DA_ENTRY 31 4 1 RESOLVE_STR_REF (@1218)
		SET_2DA_ENTRY 45 4 1 RESOLVE_STR_REF (@1219)
		SET_2DA_ENTRY 50 4 1 RESOLVE_STR_REF (@1220)
		SET_2DA_ENTRY 35 4 1 RESOLVE_STR_REF (@1221)
	BUT_ONLY
END
ACTION_IF (FILE_EXISTS_IN_GAME ~sodcltxt.2da~) BEGIN
	COPY_EXISTING ~sodcltxt.2da~ ~override~
		SET_2DA_ENTRY 3 4 1 RESOLVE_STR_REF (@1214)
		SET_2DA_ENTRY 8 4 1 RESOLVE_STR_REF (@1215)
		SET_2DA_ENTRY 16 4 1 RESOLVE_STR_REF (@1216)
		SET_2DA_ENTRY 25 4 1 RESOLVE_STR_REF (@1217)
		SET_2DA_ENTRY 31 4 1 RESOLVE_STR_REF (@1218)
		SET_2DA_ENTRY 45 4 1 RESOLVE_STR_REF (@1219)
		SET_2DA_ENTRY 50 4 1 RESOLVE_STR_REF (@1220)
		SET_2DA_ENTRY 35 4 1 RESOLVE_STR_REF (@1221)
	BUT_ONLY
END
ACTION_IF ENGINE_IS ~tob~ BEGIN
	STRING_SET 9556 @1214
	STRING_SET 9557 @1215
	STRING_SET 9558 @1216
	STRING_SET 9559 @1217
	STRING_SET 9560 @1218
	STRING_SET 9561 @1219
	STRING_SET 9562 @1220
	STRING_SET 9563 @1221
END
//__________________________________________________________________________________


//UPDATE PROFICIENCY STRINGS________________________________________________________
//
/*
COPY_EXISTING ~weapprof.2da~ ~override~
	SET_2DA_ENTRY 12 3 1 RESOLVE_STR_REF (@1230)
	SET_2DA_ENTRY 13 3 1 RESOLVE_STR_REF (@1231)
	SET_2DA_ENTRY 14 3 1 RESOLVE_STR_REF (@1232)
	SET_2DA_ENTRY 15 3 1 RESOLVE_STR_REF (@1233)
	SET_2DA_ENTRY 17 3 1 RESOLVE_STR_REF (@1234)
	SET_2DA_ENTRY 18 3 1 RESOLVE_STR_REF (@1235)
	SET_2DA_ENTRY 19 3 1 RESOLVE_STR_REF (@1236)
	SET_2DA_ENTRY 20 3 1 RESOLVE_STR_REF (@1237)
	SET_2DA_ENTRY 21 3 1 RESOLVE_STR_REF (@1238)
	SET_2DA_ENTRY 23 3 1 RESOLVE_STR_REF (@1239)
	SET_2DA_ENTRY 24 3 1 RESOLVE_STR_REF (@1240)
	SET_2DA_ENTRY 25 3 1 RESOLVE_STR_REF (@1241)
	SET_2DA_ENTRY 26 3 1 RESOLVE_STR_REF (@1242)
	SET_2DA_ENTRY 28 3 1 RESOLVE_STR_REF (@1243)
	SET_2DA_ENTRY 30 3 1 RESOLVE_STR_REF (@1244)
BUT_ONLY
*/

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25025 @1230
	STRING_SET 25026 @1231
	STRING_SET 25027 @1232
	STRING_SET 25028 @1233
	STRING_SET 25030 @1234
	STRING_SET 25031 @1235
	STRING_SET 25032 @1236
	STRING_SET 25033 @1237
	STRING_SET 25034 @1238
	STRING_SET 25036 @1239
	STRING_SET 25037 @1240
	STRING_SET 25038 @1241
	STRING_SET 25039 @1242
	STRING_SET 25041 @1243
	STRING_SET 25043 @1244
END
ACTION_IF GAME_IS ~tob bgt tutu bg2ee eet~ THEN BEGIN
	STRING_SET 34147 @1230
	STRING_SET 34148 @1231
	STRING_SET 34149 @1232
	STRING_SET 34150 @1233
	STRING_SET 34152 @1234
	STRING_SET 34153 @1235
	STRING_SET 34156 @1236
	STRING_SET 35442 @1237
	STRING_SET 34157 @1238
	STRING_SET 34159 @1239
	STRING_SET 34160 @1240
	STRING_SET 34161 @1241
	STRING_SET 34162 @1242
	STRING_SET 34164 @1243
	STRING_SET 34166 @1244
END
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
	STRING_SET 36802 @1230 // long sw
	STRING_SET 36804 @1231 // short sw
	STRING_SET 36806 @1232 // axe
	STRING_SET 36808 @1233 // 2-H sw
	STRING_SET 36812 @1234 // scimitar
	STRING_SET 36814 @1235 // dagger
	STRING_SET 36816 @1236 // hammer
	STRING_SET 36818 @1237 // club
	STRING_SET 36820 @1238 // spear
	STRING_SET 37712 @1239 // flail
	STRING_SET 37714 @1240 // mace
	STRING_SET 37716 @1241 // staff
	STRING_SET 37718 @1242 // xbow
	STRING_SET 37722 @1243 // shortbow
	STRING_SET 37726 @1244 // sling
END
//__________________________________________________________________________________


//AMEND WEAPPROF.2da_______________________________________________________________
//
COPY_EXISTING ~weapprof.2da~ ~override~
	REPLACE_TEXTUALLY ~ ID ~ ~ TYPE ID ~
	REPLACE_TEXTUALLY ~ 2 ~ ~ 3 ~
	REPLACE_TEXTUALLY ~ 5 ~ ~ 4 ~
	SET_2DA_ENTRY_LATER ~#weapprof~ 5 1 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 8 1 4
	// Fighter
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 5 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 5 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 5 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 5 3
	// Cleric
	SET_2DA_ENTRY_LATER ~#weapprof~ 7 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 8 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 10 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 6 2
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 6 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 6 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 6 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 6 0
	// Thief
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 7 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 7 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 7 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 7 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 7 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 7 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 7 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 7 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 7 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 7 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 7 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 7 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 7 3
	// Bard
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 8 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 8 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 8 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 8 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 8 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 8 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 8 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 8 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 8 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 8 2
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 8 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 8 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 8 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 8 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 8 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 8 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 8 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 8 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 8 3
	// Paladin
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 9 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 9 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 9 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 9 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 9 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 9 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 9 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 9 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 9 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 9 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 9 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 9 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 9 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 9 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 9 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 9 3
	// Druid
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 10 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 10 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 10 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 10 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 10 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 10 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 10 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 10 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 10 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 10 0
	// Ranger
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 11 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 11 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 11 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 11 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 11 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 11 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 11 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 11 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 11 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 11 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 11 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 11 3
	// Fighter/Mage
//	SET_2DA_ENTRY_LATER ~#weapprof~ 12 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 13 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 14 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 15 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 17 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 18 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 19 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 20 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 21 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 23 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 25 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 26 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 28 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 30 12 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 12 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 12 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 12 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 12 0
	// Fighter/Cleric
//	SET_2DA_ENTRY_LATER ~#weapprof~ 12 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 13 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 14 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 15 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 17 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 18 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 19 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 20 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 21 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 23 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 25 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 26 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 28 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 30 13 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 13 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 13 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 13 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 13 0
	// Fighter/Thief
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 14 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 14 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 14 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 15 3
	// Fighter/Mage/Thief
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 15 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 15 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 15 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 15 3
	// Mage/Thief
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 16 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 16 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 16 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 16 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 16 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 16 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 16 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 16 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 16 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 16 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 16 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 16 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 16 3
	// Cleric/Mage
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 17 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 17 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 17 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 17 2
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 17 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 17 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 17 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 17 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 17 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 17 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 17 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 17 0
	// Cleric/Thief
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 18 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 18 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 18 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 18 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 18 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 18 2
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 18 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 18 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 18 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 18 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 18 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 18 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 18 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 18 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 18 3
	// Fighter/Druid
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 19 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 19 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 19 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 19 3
	// Fighter/Mage/Cleric
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 20 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 20 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 20 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 20 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 20 0
	// Ranger/Cleric
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 21 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 21 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 21 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 21 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 21 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 21 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 21 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 21 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 21 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 21 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 21 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 21 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 21 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 21 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 21 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 21 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 21 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 21 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 21 3
	// Wizards
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 4 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 4 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 22 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 22 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 23 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 23 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 24 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 24 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 25 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 25 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 26 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 26 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 27 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 27 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 28 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 28 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 29 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 29 1
	// Berserker
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 30 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 30 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 30 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 30 4
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 30 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 30 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 30 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 30 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 30 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 30 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 30 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 30 3
	// Wizard Slayer
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 31 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 31 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 31 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 31 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 31 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 31 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 31 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 31 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 31 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 31 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 31 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 31 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 31 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 31 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 31 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 31 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 31 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 31 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 31 3
	// Kensai
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 32 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 32 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 32 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 32 3
	// Cavalier
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 33 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 33 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 33 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 33 3
	// Inquisitor
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 34 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 34 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 34 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 34 3
	// Undead Hunter
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 35 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 35 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 35 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 35 3
	// Archer
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 36 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 36 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 36 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 36 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 36 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 36 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 36 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 36 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 36 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 36 2
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 36 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 36 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 36 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 36 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 36 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 36 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 36 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 36 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 36 2
	// Stalker
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 37 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 37 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 37 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 37 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 37 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 37 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 37 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 37 2
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 37 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 37 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 37 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 37 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 37 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 37 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 37 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 37 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 37 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 37 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 37 3
	// Beastmaster
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 38 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 38 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 38 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 38 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 38 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 38 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 38 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 38 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 38 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 38 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 38 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 38 3
	// Assassin
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 39 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 39 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 39 2
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 39 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 39 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 39 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 39 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 39 3
	// Bounty Hunter
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 40 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 40 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 40 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 40 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 40 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 40 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 40 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 40 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 40 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 40 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 40 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 40 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 40 3
	// Swashbuckler
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 41 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 41 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 41 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 41 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 41 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 41 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 41 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 41 2
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 41 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 41 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 41 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 41 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 41 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 41 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 41 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 41 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 41 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 41 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 41 3
	// Blade
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 42 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 42 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 42 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 42 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 42 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 42 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 42 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 42 2
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 42 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 42 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 42 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 42 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 42 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 42 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 42 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 42 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 42 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 42 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 42 3
	// Jester
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 43 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 43 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 43 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 43 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 43 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 43 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 43 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 43 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 43 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 43 2
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 43 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 43 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 43 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 43 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 43 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 43 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 43 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 43 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 43 3
	// Skald
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 44 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 44 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 44 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 44 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 44 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 44 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 44 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 44 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 44 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 44 2
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 44 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 44 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 44 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 44 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 44 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 44 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 44 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 44 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 44 3
	// Totemic Driud
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 45 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 45 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 45 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 45 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 45 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 45 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 45 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 45 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 45 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 45 2
	// Shapeshifter
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 46 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 46 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 46 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 46 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 46 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 46 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 46 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 46 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 46 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 46 2
	// Avenger
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 47 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 47 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 47 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 47 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 47 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 47 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 47 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 47 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 47 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 47 2
	// Talos
	SET_2DA_ENTRY_LATER ~#weapprof~ 7 48 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 8 48 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 10 48 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 48 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 48 2
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 48 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 48 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 48 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 48 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 48 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 48 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 48 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 48 0
	// Helm
	SET_2DA_ENTRY_LATER ~#weapprof~ 7 49 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 8 49 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 10 49 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 49 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 49 2
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 49 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 49 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 49 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 49 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 49 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 49 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 49 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 49 0
	// Lathander
	SET_2DA_ENTRY_LATER ~#weapprof~ 7 50 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 8 50 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 10 50 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 50 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 50 2
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 50 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 50 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 50 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 50 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 49 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 49 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 49 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 49 0
	// Monk
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 51 1
	// Barbarian
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 52 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 52 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 52 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 52 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 52 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 52 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 52 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 52 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 52 3
	// Wild Mage	
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 53 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 53 1
	SET_2DA_ENTRIES_NOW ~#weapprof~ 1
	REPLACE_TEXTUALLY ~TYPE ~ ~      ~

ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	COPY_EXISTING ~weapprof.2da~ ~override~
		// Blackguard
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 20 54 3
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 31 54 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 32 54 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 33 54 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 34 54 3
		// Shadowdancer
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 12 55 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 13 55 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 17 55 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 18 55 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 20 55 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 25 55 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 26 55 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 28 55 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 30 55 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 31 55 0
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 32 55 0
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 33 55 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 34 55 3
		// Dwarven Defender
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 12 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 13 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 14 56 4
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 15 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 17 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 18 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 19 56 4
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 20 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 21 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 23 56 2
//		SET_2DA_ENTRY_LATER ~EE#weapprof~ 24 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 25 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 26 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 28 56 0
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 30 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 31 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 32 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 33 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 34 56 3
		// Dragon Disciple
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 20 57 1
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 26 57 1
		// Dark Moon Monk
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 20 58 1
		// Sun Soul Monk
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 20 59 1
		// Tyr
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 7 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 8 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 10 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 19 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 23 61 2
//		SET_2DA_ENTRY_LATER ~EE#weapprof~ 24 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 25 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 30 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 20 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 26 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 31 61 1
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 32 61 1
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 33 61 1
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 34 61 0
	SET_2DA_ENTRIES_NOW ~EE#weapprof~ 1
END

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	COPY_EXISTING ~weapprof.2da~ ~override~
		// Shaman
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 9 60 2
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 14 60 2
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 17 60 0
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 18 60 2
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 20 60 2
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 21 60 2
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 25 60 2
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 28 60 2
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 30 60 2
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 31 60 1
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 32 60 0
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 33 60 1
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 34 60 2
	SET_2DA_ENTRIES_NOW ~BEE#weapprof~ 1
END
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN
	COPY_EXISTING ~weapprof.2da~ ~override~
		// Shaman
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 9 62 2
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 14 62 2
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 17 62 0
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 18 62 2
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 20 62 2
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 21 62 2
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 25 62 2
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 28 62 2
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 30 62 2
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 31 62 1
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 32 62 0
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 33 62 1
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 34 62 2
	SET_2DA_ENTRIES_NOW ~2EE#weapprof~ 1
END
	
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
	COPY_EXISTING ~weapprof.2da~ ~override~
/*
		// Tyr
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 7 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 8 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 10 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 19 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 23 61 2
//		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 24 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 25 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 30 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 20 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 26 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 31 61 1
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 32 61 1
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 33 61 1
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 34 61 0
*/
		// Tempus
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 7 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 8 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 10 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 19 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 23 62 2
//		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 24 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 25 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 30 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 20 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 26 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 31 62 1
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 32 62 1
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 33 62 1
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 34 62 0
	SET_2DA_ENTRIES_NOW ~IEE#weapprof~ 1
END
//__________________________________________________________________________________


//PROFICIENCIES FOR MOD CLERICS_____________________________________________________
//
DEFINE_ACTION_FUNCTION mod_cleric_profs BEGIN
	OUTER_SET count = 0

	ACTION_FOR_EACH class IN
                  cleric

	BEGIN
		OUTER_SPRINT $clerics("%count%") "%class%"
		OUTER_SET ++count
	END

	COPY_EXISTING kitlist.2da override
		READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 31; row < kitlist; ++row) BEGIN // Skip past the vanilla kits
			READ_2DA_ENTRY_FORMER kitlist row 1 label
			READ_2DA_ENTRY_FORMER kitlist row 8 class
			PATCH_IF class = 3 BEGIN // cleric
				SPRINT $clerics("%count%") "%label%"
				++count
			END
		END
	BUT_ONLY

	COPY_EXISTING ~WEAPPROF.2DA~ override
		READ_2DA_ENTRIES_NOW weapprof 3
		COUNT_2DA_COLS cols
		PHP_EACH clerics AS _ => name BEGIN
			FOR (col = 0; col < cols - 1; ++col) BEGIN
				READ_2DA_ENTRY_FORMER weapprof 0 col column_name
				PATCH_IF "%column_name%" STRING_EQUAL_CASE "%name%" BEGIN
					SET_2DA_ENTRY_LATER C#weapprof 7 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 8 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 10 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 18 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 19 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 20 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 21 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 23 (col + 1) 2
//					SET_2DA_ENTRY_LATER C#weapprof 24 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 25 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 26 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 30 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 31 (col + 1) 1
					SET_2DA_ENTRY_LATER C#weapprof 32 (col + 1) 1
					SET_2DA_ENTRY_LATER C#weapprof 33 (col + 1) 1
					SET_2DA_ENTRY_LATER C#weapprof 34 (col + 1) 0
				END
			END
		END
		SET_2DA_ENTRIES_NOW C#weapprof 1
		PRETTY_PRINT_2DA
	BUT_ONLY
END

LAF mod_cleric_profs END
//__________________________________________________________________________________


//PROFICIENCIES FOR MOD DRUIDS_______________________________________________________
//
DEFINE_ACTION_FUNCTION mod_druid_profs BEGIN
	OUTER_SET count = 0

	ACTION_FOR_EACH class IN
                  druid

	BEGIN
		OUTER_SPRINT $druids("%count%") "%class%"
		OUTER_SET ++count
	END

	COPY_EXISTING kitlist.2da override
		READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 31; row < kitlist; ++row) BEGIN // Skip past the vanilla kits
			READ_2DA_ENTRY_FORMER kitlist row 1 label
			READ_2DA_ENTRY_FORMER kitlist row 8 class
			PATCH_IF class = 11 BEGIN // druid
				SPRINT $druids("%count%") "%label%"
				++count
			END
		END
	BUT_ONLY

	COPY_EXISTING ~WEAPPROF.2DA~ override
		READ_2DA_ENTRIES_NOW weapprof 3
		COUNT_2DA_COLS cols
		PHP_EACH druids AS _ => name BEGIN
			FOR (col = 0; col < cols - 1; ++col) BEGIN
				READ_2DA_ENTRY_FORMER weapprof 0 col column_name
				PATCH_IF "%column_name%" STRING_EQUAL_CASE "%name%" BEGIN
					SET_2DA_ENTRY_LATER D#weapprof 17 (col + 1) 2
					SET_2DA_ENTRY_LATER D#weapprof 18 (col + 1) 2
					SET_2DA_ENTRY_LATER D#weapprof 20 (col + 1) 2
					SET_2DA_ENTRY_LATER D#weapprof 21 (col + 1) 2
					SET_2DA_ENTRY_LATER D#weapprof 25 (col + 1) 2
					SET_2DA_ENTRY_LATER D#weapprof 28 (col + 1) 2
					SET_2DA_ENTRY_LATER D#weapprof 30 (col + 1) 2
					SET_2DA_ENTRY_LATER D#weapprof 31 (col + 1) 2
					SET_2DA_ENTRY_LATER D#weapprof 32 (col + 1) 0
					SET_2DA_ENTRY_LATER D#weapprof 33 (col + 1) 2
					SET_2DA_ENTRY_LATER D#weapprof 34 (col + 1) 2
				END
			END
		END
		SET_2DA_ENTRIES_NOW D#weapprof 1
		PRETTY_PRINT_2DA
	BUT_ONLY
END

LAF mod_druid_profs END
//__________________________________________________________________________________


//PROFICIENCIES FOR MOD THIEVES_____________________________________________________
//
DEFINE_ACTION_FUNCTION mod_thief_profs BEGIN
	OUTER_SET count = 0

	ACTION_FOR_EACH class IN
                  thief

	BEGIN
		OUTER_SPRINT $thiefs("%count%") "%class%"
		OUTER_SET ++count
	END

	COPY_EXISTING kitlist.2da override
		READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 31; row < kitlist; ++row) BEGIN // Skip past the vanilla kits
			READ_2DA_ENTRY_FORMER kitlist row 1 label
			READ_2DA_ENTRY_FORMER kitlist row 8 class
			PATCH_IF class = 4 BEGIN // thief
				SPRINT $thiefs("%count%") "%label%"
				++count
			END
		END
	BUT_ONLY

	COPY_EXISTING ~WEAPPROF.2DA~ override
		READ_2DA_ENTRIES_NOW weapprof 3
		COUNT_2DA_COLS cols
		PHP_EACH thiefs AS _ => name BEGIN
			FOR (col = 0; col < cols - 1; ++col) BEGIN
				READ_2DA_ENTRY_FORMER weapprof 0 col column_name
				PATCH_IF "%column_name%" STRING_EQUAL_CASE "%name%" BEGIN
					SET_2DA_ENTRY_LATER T#weapprof 12 (col + 1) 2
					SET_2DA_ENTRY_LATER T#weapprof 13 (col + 1) 2
					SET_2DA_ENTRY_LATER T#weapprof 17 (col + 1) 2
					SET_2DA_ENTRY_LATER T#weapprof 18 (col + 1) 2
					SET_2DA_ENTRY_LATER T#weapprof 20 (col + 1) 2
					SET_2DA_ENTRY_LATER T#weapprof 25 (col + 1) 2
					SET_2DA_ENTRY_LATER T#weapprof 26 (col + 1) 2
					SET_2DA_ENTRY_LATER T#weapprof 28 (col + 1) 2
					SET_2DA_ENTRY_LATER T#weapprof 30 (col + 1) 2
					SET_2DA_ENTRY_LATER T#weapprof 31 (col + 1) 0
					SET_2DA_ENTRY_LATER T#weapprof 32 (col + 1) 0
					SET_2DA_ENTRY_LATER T#weapprof 33 (col + 1) 2
					SET_2DA_ENTRY_LATER T#weapprof 34 (col + 1) 3
				END
			END
		END
		SET_2DA_ENTRIES_NOW T#weapprof 1
		PRETTY_PRINT_2DA
	BUT_ONLY
END

LAF mod_thief_profs END
//__________________________________________________________________________________


//PROFICIENCIES FOR MOD BARDS_______________________________________________________
//
DEFINE_ACTION_FUNCTION mod_bard_profs BEGIN
	OUTER_SET count = 0

	ACTION_FOR_EACH class IN
                  bard

	BEGIN
		OUTER_SPRINT $bards("%count%") "%class%"
		OUTER_SET ++count
	END

	COPY_EXISTING kitlist.2da override
		READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 31; row < kitlist; ++row) BEGIN // Skip past the vanilla kits
			READ_2DA_ENTRY_FORMER kitlist row 1 label
			READ_2DA_ENTRY_FORMER kitlist row 8 class
			PATCH_IF class = 5 BEGIN // bard
				SPRINT $bards("%count%") "%label%"
				++count
			END
		END
	BUT_ONLY

	COPY_EXISTING ~WEAPPROF.2DA~ override
		READ_2DA_ENTRIES_NOW weapprof 3
		COUNT_2DA_COLS cols
		PHP_EACH bards AS _ => name BEGIN
			FOR (col = 0; col < cols - 1; ++col) BEGIN
				READ_2DA_ENTRY_FORMER weapprof 0 col column_name
				PATCH_IF "%column_name%" STRING_EQUAL_CASE "%name%" BEGIN
					SET_2DA_ENTRY_LATER B#weapprof 12 (col + 1) 2
					SET_2DA_ENTRY_LATER B#weapprof 13 (col + 1) 2
					SET_2DA_ENTRY_LATER B#weapprof 14 (col + 1) 2
					SET_2DA_ENTRY_LATER B#weapprof 15 (col + 1) 0
					SET_2DA_ENTRY_LATER B#weapprof 17 (col + 1) 2
					SET_2DA_ENTRY_LATER B#weapprof 18 (col + 1) 2
					SET_2DA_ENTRY_LATER B#weapprof 19 (col + 1) 2
					SET_2DA_ENTRY_LATER B#weapprof 20 (col + 1) 2
					SET_2DA_ENTRY_LATER B#weapprof 21 (col + 1) 0
					SET_2DA_ENTRY_LATER B#weapprof 23 (col + 1) 2
//					SET_2DA_ENTRY_LATER B#weapprof 24 (col + 1) 2
					SET_2DA_ENTRY_LATER B#weapprof 25 (col + 1) 0
					SET_2DA_ENTRY_LATER B#weapprof 26 (col + 1) 2
					SET_2DA_ENTRY_LATER B#weapprof 28 (col + 1) 2
					SET_2DA_ENTRY_LATER B#weapprof 30 (col + 1) 2
					SET_2DA_ENTRY_LATER B#weapprof 31 (col + 1) 2
					SET_2DA_ENTRY_LATER B#weapprof 32 (col + 1) 2
					SET_2DA_ENTRY_LATER B#weapprof 33 (col + 1) 2
					SET_2DA_ENTRY_LATER B#weapprof 34 (col + 1) 3
				END
			END
		END
		SET_2DA_ENTRIES_NOW B#weapprof 1
		PRETTY_PRINT_2DA
	BUT_ONLY
END

LAF mod_bard_profs END
//__________________________________________________________________________________


//PROFICIENCIES FOR MOD RANGERS_____________________________________________________
//
DEFINE_ACTION_FUNCTION mod_ranger_profs BEGIN
	OUTER_SET count = 0

	ACTION_FOR_EACH class IN
                  ranger

	BEGIN
		OUTER_SPRINT $rangers("%count%") "%class%"
		OUTER_SET ++count
	END

	COPY_EXISTING kitlist.2da override
		READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 31; row < kitlist; ++row) BEGIN // Skip past the vanilla kits
			READ_2DA_ENTRY_FORMER kitlist row 1 label
			READ_2DA_ENTRY_FORMER kitlist row 8 class
			PATCH_IF class = 12 BEGIN // ranger
				SPRINT $rangers("%count%") "%label%"
				++count
			END
		END
	BUT_ONLY

	COPY_EXISTING ~WEAPPROF.2DA~ override
		READ_2DA_ENTRIES_NOW weapprof 3
		COUNT_2DA_COLS cols
		PHP_EACH rangers AS _ => name BEGIN
			FOR (col = 0; col < cols - 1; ++col) BEGIN
				READ_2DA_ENTRY_FORMER weapprof 0 col column_name
				PATCH_IF "%column_name%" STRING_EQUAL_CASE "%name%" BEGIN
					SET_2DA_ENTRY_LATER R#weapprof 12 (col + 1) 3
					SET_2DA_ENTRY_LATER R#weapprof 13 (col + 1) 3
					SET_2DA_ENTRY_LATER R#weapprof 14 (col + 1) 3
					SET_2DA_ENTRY_LATER R#weapprof 17 (col + 1) 3
					SET_2DA_ENTRY_LATER R#weapprof 18 (col + 1) 3
					SET_2DA_ENTRY_LATER R#weapprof 21 (col + 1) 3
					SET_2DA_ENTRY_LATER R#weapprof 25 (col + 1) 3
					SET_2DA_ENTRY_LATER R#weapprof 28 (col + 1) 3
					SET_2DA_ENTRY_LATER R#weapprof 31 (col + 1) 2
					SET_2DA_ENTRY_LATER R#weapprof 32 (col + 1) 0
					SET_2DA_ENTRY_LATER R#weapprof 33 (col + 1) 2
					SET_2DA_ENTRY_LATER R#weapprof 34 (col + 1) 3
				END
			END
		END
		SET_2DA_ENTRIES_NOW R#weapprof 1
		PRETTY_PRINT_2DA
	BUT_ONLY
END

LAF mod_ranger_profs END
//__________________________________________________________________________________


//PROFICIENCIES FOR MOD PALADINS____________________________________________________
//
DEFINE_ACTION_FUNCTION mod_paladin_profs BEGIN
	OUTER_SET count = 0

	ACTION_FOR_EACH class IN
                  paladin

	BEGIN
		OUTER_SPRINT $paladins("%count%") "%class%"
		OUTER_SET ++count
	END

	COPY_EXISTING kitlist.2da override
		READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 31; row < kitlist; ++row) BEGIN // Skip past the vanilla kits
			READ_2DA_ENTRY_FORMER kitlist row 1 label
			READ_2DA_ENTRY_FORMER kitlist row 8 class
			PATCH_IF class = 6 BEGIN // paladin
				SPRINT $paladins("%count%") "%label%"
				++count
			END
		END
	BUT_ONLY

	COPY_EXISTING ~WEAPPROF.2DA~ override
		READ_2DA_ENTRIES_NOW weapprof 3
		COUNT_2DA_COLS cols
		PHP_EACH paladins AS _ => name BEGIN
			FOR (col = 0; col < cols - 1; ++col) BEGIN
				READ_2DA_ENTRY_FORMER weapprof 0 col column_name
				PATCH_IF "%column_name%" STRING_EQUAL_CASE "%name%" BEGIN
					SET_2DA_ENTRY_LATER P#weapprof 31 (col + 1) 2
					SET_2DA_ENTRY_LATER P#weapprof 32 (col + 1) 2
					SET_2DA_ENTRY_LATER P#weapprof 33 (col + 1) 2
					SET_2DA_ENTRY_LATER P#weapprof 34 (col + 1) 3
				END
			END
		END
		SET_2DA_ENTRIES_NOW P#weapprof 1
		PRETTY_PRINT_2DA
	BUT_ONLY
END

LAF mod_paladin_profs END
//__________________________________________________________________________________


//PROFICIENCIES FOR MOD FIGHTERS____________________________________________________
//
DEFINE_ACTION_FUNCTION mod_fighter_profs BEGIN
	OUTER_SET count = 0

	ACTION_FOR_EACH class IN
                  fighter

	BEGIN
		OUTER_SPRINT $fighters("%count%") "%class%"
		OUTER_SET ++count
	END

	COPY_EXISTING kitlist.2da override
		READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 31; row < kitlist; ++row) BEGIN // Skip past the vanilla kits
			READ_2DA_ENTRY_FORMER kitlist row 1 label
			READ_2DA_ENTRY_FORMER kitlist row 8 class
			PATCH_IF class = 2 BEGIN // fighter
				SPRINT $fighters("%count%") "%label%"
				++count
			END
		END
	BUT_ONLY

	COPY_EXISTING ~WEAPPROF.2DA~ override
		READ_2DA_ENTRIES_NOW weapprof 3
		COUNT_2DA_COLS cols
		PHP_EACH fighters AS _ => name BEGIN
			FOR (col = 0; col < cols - 1; ++col) BEGIN
				READ_2DA_ENTRY_FORMER weapprof 0 col column_name
				PATCH_IF "%column_name%" STRING_EQUAL_CASE "%name%" BEGIN
					SET_2DA_ENTRY_LATER F#weapprof 31 (col + 1) 2
					SET_2DA_ENTRY_LATER F#weapprof 32 (col + 1) 2
					SET_2DA_ENTRY_LATER F#weapprof 33 (col + 1) 2
					SET_2DA_ENTRY_LATER F#weapprof 34 (col + 1) 3
				END
			END
		END
		SET_2DA_ENTRIES_NOW F#weapprof 1
		PRETTY_PRINT_2DA
	BUT_ONLY
END

LAF mod_fighter_profs END
//__________________________________________________________________________________


//MIGHT & GUILE KITS________________________________________________________________
//
COPY_EXISTING ~weapprof.2da~ ~override~
	COUNT_2DA_COLS num_cols
	READ_2DA_ENTRIES_NOW ~r2en_mng~ (num_cols - 1)
	FOR (col = 3; col < (num_cols - 1); col += 1) BEGIN
		READ_2DA_ENTRY_FORMER ~r2en_mng~ 0 col kitname
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~D5CORSA~) BEGIN
			SET_2DA_ENTRY_LATER ~s2el_mng~ 12 (col + 1) 4
			SET_2DA_ENTRY_LATER ~s2el_mng~ 13 (col + 1) 4
			SET_2DA_ENTRY_LATER ~s2el_mng~ 17 (col + 1) 4
			SET_2DA_ENTRY_LATER ~s2el_mng~ 18 (col + 1) 4
			SET_2DA_ENTRY_LATER ~s2el_mng~ 14 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 19 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 20 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 25 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 15 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 21 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 23 (col + 1) 0
//			SET_2DA_ENTRY_LATER ~s2el_mng~ 24 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 26 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 28 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 30 (col + 1) 2
		END
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~D5MARKS~) BEGIN
			SET_2DA_ENTRY_LATER ~s2el_mng~ 12 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 13 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 14 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 15 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 17 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 18 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 19 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 20 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 21 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 23 (col + 1) 2
//			SET_2DA_ENTRY_LATER ~s2el_mng~ 24 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 25 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 26 (col + 1) 4
			SET_2DA_ENTRY_LATER ~s2el_mng~ 28 (col + 1) 4
			SET_2DA_ENTRY_LATER ~s2el_mng~ 30 (col + 1) 1
		END
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~D5EARCH~) BEGIN
			SET_2DA_ENTRY_LATER ~s2el_mng~ 12 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 13 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 14 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 15 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 17 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 18 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 19 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 20 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 21 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 23 (col + 1) 2
//			SET_2DA_ENTRY_LATER ~s2el_mng~ 24 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 25 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 26 (col + 1) 1
			SET_2DA_ENTRY_LATER ~s2el_mng~ 28 (col + 1) 4
			SET_2DA_ENTRY_LATER ~s2el_mng~ 30 (col + 1) 1
		END
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~D5SLING~) BEGIN
			SET_2DA_ENTRY_LATER ~s2el_mng~ 12 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 13 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 14 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 15 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 17 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 18 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 19 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 20 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 21 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 23 (col + 1) 2
//			SET_2DA_ENTRY_LATER ~s2el_mng~ 24 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 25 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 26 (col + 1) 1
			SET_2DA_ENTRY_LATER ~s2el_mng~ 28 (col + 1) 1
			SET_2DA_ENTRY_LATER ~s2el_mng~ 30 (col + 1) 5
		END
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~D5SNIPE~) BEGIN
			SET_2DA_ENTRY_LATER ~s2el_mng~ 12 (col + 1) 1
			SET_2DA_ENTRY_LATER ~s2el_mng~ 13 (col + 1) 1
			SET_2DA_ENTRY_LATER ~s2el_mng~ 17 (col + 1) 1
			SET_2DA_ENTRY_LATER ~s2el_mng~ 18 (col + 1) 1
			SET_2DA_ENTRY_LATER ~s2el_mng~ 20 (col + 1) 1
			SET_2DA_ENTRY_LATER ~s2el_mng~ 25 (col + 1) 1
			SET_2DA_ENTRY_LATER ~s2el_mng~ 26 (col + 1) 4
			SET_2DA_ENTRY_LATER ~s2el_mng~ 28 (col + 1) 4
			SET_2DA_ENTRY_LATER ~s2el_mng~ 30 (col + 1) 4
		END
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~D5SWASH~) BEGIN
			SET_2DA_ENTRY_LATER ~s2el_mng~ 12 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 13 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 17 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 18 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 14 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 19 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 20 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 23 (col + 1) 2
//			SET_2DA_ENTRY_LATER ~s2el_mng~ 24 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 25 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 15 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 21 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 26 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 28 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 30 (col + 1) 2
		END
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~D5JONGL~) BEGIN
			SET_2DA_ENTRY_LATER ~s2el_mng~ 12 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 13 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 14 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 15 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 17 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 18 (col + 1) 4
			SET_2DA_ENTRY_LATER ~s2el_mng~ 19 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 20 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 21 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 23 (col + 1) 0
//			SET_2DA_ENTRY_LATER ~s2el_mng~ 24 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 25 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 26 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 28 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 30 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 31 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 32 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 33 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 34 (col + 1) 3
		END
	END
	SET_2DA_ENTRIES_NOW ~s2el_mng~ 1
BUT_ONLY
//__________________________________________________________________________________


//COPY PROFICIENCY FILES____________________________________________________________
//
COPY ~scales_of_balance/profs/d5_caxe1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_caxe2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_caxe3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cdag1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cdag2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cdag3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cbow1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cbow2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cbow3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_clsw1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_clsw2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_clsw3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cssw1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cssw2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cssw3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_c2sw1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_c2sw2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_c2sw3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_csci1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_csci2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_csci3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cspe1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cspe2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cspe3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_csli1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_csli2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_csli3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cclu1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cclu2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cclu3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cfla1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cfla2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cfla3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cmac1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cmac2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cmac3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cham1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cham2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cham3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_csta1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_csta2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_csta3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_pano.itm~ ~override~
	SAY NAME2 @1254
	SAY DESC @1255
COPY ~scales_of_balance/profs/d5_pimo.itm~ ~override~
	SAY NAME2 @1256
	SAY DESC @1257
COPY ~scales_of_balance/profs/d5_pnal.itm~ ~override~
	SAY NAME2 @1258
	SAY DESC @1259
COPY ~scales_of_balance/profs/d5_pano.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_pimo.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_pnal.spl~ ~override~
	SAY NAME1 @1248
//__________________________________________________________________________________


//AMEND WARRIOR CLAB FILES__________________________________________________________
//
COPY_EXISTING ~clabfi01.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabfi02.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabfi03.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabfi04.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabfi05.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
ACTION_IF FILE_EXISTS_IN_GAME ~clabfi06.2da~ THEN BEGIN
	COPY_EXISTING ~clabfi06.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
		REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
		BUT_ONLY
	END
COPY_EXISTING ~clabpa01.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabpa02.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabpa03.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabpa04.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabpa05.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
ACTION_IF FILE_EXISTS_IN_GAME ~clabpa06.2da~ THEN BEGIN
	COPY_EXISTING ~clabpa06.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
		REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
		BUT_ONLY
	END
COPY_EXISTING ~clabrn01.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabrn02.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabrn03.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabrn04.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabrn05.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY

/*
//AMEND CLERIC CLAB FILES____________________________________________________________
//
COPY_EXISTING ~clabpr02.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~scales_of_balance/profs/pcspea.txt~
	BUT_ONLY
COPY_EXISTING ~clabpr03.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~scales_of_balance/profs/pc2swo.txt~
	BUT_ONLY
COPY_EXISTING ~clabpr04.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~scales_of_balance/profs/pcmace.txt~
	BUT_ONLY
ACTION_IF FILE_EXISTS_IN_GAME ~ohtyr.2da~ THEN BEGIN
	COPY_EXISTING ~ohtyr.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pclswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~ohtempus.2da~ THEN BEGIN
	COPY_EXISTING ~ohtempus.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcaxe.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#cyric.2da~ THEN BEGIN
	COPY_EXISTING ~a#cyric.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcsswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#feyw.2da~ THEN BEGIN
	COPY_EXISTING ~a#feyw.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pclswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#koss.2da~ THEN BEGIN
	COPY_EXISTING ~a#koss.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcflai.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#ogma.2da~ THEN BEGIN
	COPY_EXISTING ~a#ogma.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pclswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#red.2da~ THEN BEGIN
	COPY_EXISTING ~a#red.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pclswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#shar.2da~ THEN BEGIN
	COPY_EXISTING ~a#shar.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcdagg.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#temp.2da~ THEN BEGIN
	COPY_EXISTING ~a#temp.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcaxe.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~cdilmatr.2da~ THEN BEGIN
	COPY_EXISTING ~cdilmatr.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcflai.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~cdselune.2da~ THEN BEGIN
	COPY_EXISTING ~cdselune.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcmace.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~cdxvim.2da~ THEN BEGIN
	COPY_EXISTING ~cdxvim.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcscim.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabeart.2da~ THEN BEGIN
	COPY_EXISTING ~clabeart.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pchamm.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabgruu.2da~ THEN BEGIN
	COPY_EXISTING ~clabgruu.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcaxe.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabluth.2da~ THEN BEGIN
	COPY_EXISTING ~clabluth.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcsswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabauri.2da~ THEN BEGIN
	COPY_EXISTING ~clabauri.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcdagg.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabiceg.2da~ THEN BEGIN
	COPY_EXISTING ~clabiceg.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcspea.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clableaf.2da~ THEN BEGIN
	COPY_EXISTING ~clableaf.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcclub.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5_tymor.2da~ THEN BEGIN
	COPY_EXISTING ~d5_tymor.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcslin.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5_cllei.2da~ THEN BEGIN
	COPY_EXISTING ~d5_cllei.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcdagg.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~b_cllov.2da~ THEN BEGIN
	COPY_EXISTING ~b_cllov.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcflai.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~b_acilm.2da~ THEN BEGIN
	COPY_EXISTING ~b_acilm.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcstaf.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5_acmas.2da~ THEN BEGIN
	COPY_EXISTING ~d5_acmas.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcsswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5_acsha.2da~ THEN BEGIN
	COPY_EXISTING ~d5_acsha.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcdagg.txt~
		BUT_ONLY
END
//__________________________________________________________________________________
*/

//UNIVERSAL CLUBS___________________________________________________________________
//
DEFINE_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
  INT_VAR
    offset = 0
  STR_VAR
    desc = ~~
    unusable_regexp = ~~
    unusable_replacement = ~~
    class_regexp = ~~ //
    class_prefix = ~~ //
BEGIN
  INNER_PATCH_SAVE desc ~%desc%~ BEGIN
    REPLACE_TEXTUALLY ~%unusable_regexp%~ ~%unusable_replacement%~
  END
  PATCH_IF ((~%desc%~ STRING_CONTAINS_REGEXP ~^%unusable_replacement%~) == 0) BEGIN
    INNER_PATCH_SAVE usab_block ~%desc%~ BEGIN
      REPLACE_TEXTUALLY ~\(.*[%LNL%%MNL%%WNL%]\)*%unusable_replacement%~ ~~
    END
    INNER_PATCH_SAVE usab_block_new ~%usab_block%~ BEGIN
      REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%][- %TAB%]*$~ ~~
      REPLACE_TEXTUALLY ~^[- %TAB%]*~ ~%class_prefix%~
      REPLACE_TEXTUALLY ~%mage_regexp%~ ~~
    END
    INNER_PATCH_SAVE desc ~%desc%~ BEGIN
      REPLACE_TEXTUALLY EXACT_MATCH ~%usab_block%~ ~%usab_block_new%~
    END
    INNER_PATCH_SAVE compare ~%desc%~ BEGIN 
      REPLACE_TEXTUALLY ~^%unusable_replacement%.*[%LNL%%MNL%%WNL%]%class_prefix%[^- %TAB%]~ ~~
    END
    PATCH_IF (~%desc%~ STRING_EQUAL ~%compare%~) BEGIN
      INNER_PATCH_SAVE desc ~%desc%~ BEGIN
        REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]%unusable_replacement%.*~ ~~
      END
    END
    SAY_EVALUATED ~%offset%~ ~%desc%~
  END
END

COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
    READ_BYTE 0x31 "prof" ELSE 0
    PATCH_IF ("%prof%" = 115) BEGIN
      READ_BYTE 0x1f "fighter"
      PATCH_IF (("%fighter%" BAND "0b00001000") = "0b00000000") BEGIN
        READ_BYTE   0x20 "mage"
        WRITE_BYTE 0x20 ("%mage%" BAND "0b11111011")
        PATCH_FOR_EACH offset IN
          ~0x50~
          ~0x54~
        BEGIN
          READ_LONG ~%offset%~ desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF ~%offset%~ desc
           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
           	  STR_VAR
           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
           	    unusable_replacement = ~Not Usable By:~
           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bMage.*~
           	    class_prefix = ~ ~
           	END
          END
        END
      END
    END
  END
  BUT_ONLY_IF_IT_CHANGES
//__________________________________________________________________________________

//UNIVERSAL CROSSBOWS________________________________________________________________
//
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
    READ_BYTE 0x31 "prof" ELSE 0
    PATCH_IF ("%prof%" = 103) BEGIN
      READ_BYTE 0x1f "fighter"
      PATCH_IF (("%fighter%" BAND "0b00001000") = "0b00000000") BEGIN
        READ_BYTE   0x20 "mage"
        WRITE_BYTE 0x20 ("%mage%" BAND "0b11111011")
        PATCH_FOR_EACH offset IN
          ~0x50~
          ~0x54~
        BEGIN
          READ_LONG ~%offset%~ desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF ~%offset%~ desc
           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
           	  STR_VAR
           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
           	    unusable_replacement = ~Not Usable By:~
           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bMage.*~
           	    class_prefix = ~ ~
           	END
          END
        END
      END
    END
    READ_SHORT ~0x1c~ ~type~
    PATCH_IF (~%type%~ = ~31~) BEGIN
      READ_BYTE 0x1f "fighter"
      PATCH_IF (("%fighter%" BAND "0b00001000") = "0b00000000") BEGIN
        READ_BYTE   0x20 "mage"
        WRITE_BYTE 0x20 ("%mage%" BAND "0b11111011")
        PATCH_FOR_EACH offset IN
          ~0x50~
          ~0x54~
        BEGIN
          READ_LONG ~%offset%~ desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF ~%offset%~ desc
           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
           	  STR_VAR
           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
           	    unusable_replacement = ~Not Usable By:~
           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bMage.*~
           	    class_prefix = ~ ~
           	END
          END
        END
      END
    END
  END
  BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
    READ_BYTE 0x31 "prof" ELSE 0
    PATCH_IF ("%prof%" = 103) BEGIN
      READ_BYTE 0x1f "fighter"
      PATCH_IF (("%fighter%" BAND "0b00001000") = "0b00000000") BEGIN
        READ_BYTE   0x1E "cleric"
        WRITE_BYTE 0x1E ("%cleric%" BAND "0b01111111")
        READ_BYTE   0x1F "cleric-mage"
        WRITE_BYTE 0x1F ("%cleric-mage%" BAND "0b00111000")
        PATCH_FOR_EACH offset IN
          ~0x50~
          ~0x54~
        BEGIN
          READ_LONG ~%offset%~ desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF ~%offset%~ desc
           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
           	  STR_VAR
           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
           	    unusable_replacement = ~Not Usable By:~
           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
           	    class_prefix = ~ ~
           	END
          END
        END
      END
    END
    READ_SHORT ~0x1c~ ~type~
    PATCH_IF (~%type%~ = ~31~) BEGIN
      READ_BYTE 0x1f "fighter"
      PATCH_IF (("%fighter%" BAND "0b00001000") = "0b00000000") BEGIN
        READ_BYTE   0x1E "cleric"
        WRITE_BYTE 0x1E ("%cleric%" BAND "0b01111111")
        READ_BYTE   0x1F "cleric-mage"
        WRITE_BYTE 0x1F ("%cleric-mage%" BAND "0b00111000")
        PATCH_FOR_EACH offset IN
          ~0x50~
          ~0x54~
        BEGIN
          READ_LONG ~%offset%~ desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF ~%offset%~ desc
           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
           	  STR_VAR
           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
           	    unusable_replacement = ~Not Usable By:~
           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
           	    class_prefix = ~ ~
           	END
          END
        END
      END
    END
  END
  BUT_ONLY_IF_IT_CHANGES
//__________________________________________________________________________________


//CLERIC WEAPON USABILITY___________________________________________________________
//
//ACTION_IF NOT MOD_IS_INSTALLED "faiths_and_powers.tp2" "101" "skipping"
// ACTION_IF NOT MOD_IS_INSTALLED "faiths_and_powers.tp2" "105" "skipping"

COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1e cleric 
		READ_BYTE  0x1f mcler 
		READ_SHORT  ~0x1c~ type 
		PATCH_IF (type = 15 || type = 5 || type = 31 || type = 29 || type = 25 || type = 19 || type = 20 || type = 16) BEGIN // bows, spears, axes, small swords, large swords, daggers
			WRITE_BYTE 0x1e (cleric BAND 0b01111111)
			WRITE_BYTE 0x1f (mcler BAND 0b00111000)
  	      PATCH_FOR_EACH offset IN
  	        ~0x50~
  	        ~0x54~
  	      BEGIN
  	        READ_LONG ~%offset%~ desc_strref
  	        PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
  	          READ_STRREF ~%offset%~ desc
  	         	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
  	         	  STR_VAR
  	         	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
  	         	    unusable_replacement = ~Not Usable By:~
  	         	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
  	         	    class_prefix = ~ ~
  	         	END	
	          END
  	        END
		END
	END
BUT_ONLY
/*
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1e cleric 
		READ_BYTE  0x1f mcler 
		PATCH_IF (type = 29) BEGIN // spears
			WRITE_BYTE 0x1e (cleric BAND 0b01111111)
			WRITE_BYTE 0x1f (mcler BAND 0b00111000)
	        PATCH_FOR_EACH offset IN
	          ~0x50~
	          ~0x54~
	        BEGIN
	          READ_LONG ~%offset%~ desc_strref
	          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
	            READ_STRREF ~%offset%~ desc
	           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
	           	  STR_VAR
	           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
	           	    unusable_replacement = ~Not Usable By:~
	           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
	           	    class_prefix = ~ ~
	           	END
	          END
	        END
		END
	END
BUT_ONLY
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1e cleric 
		READ_BYTE  0x1f mcler 
		PATCH_IF (type = 25) BEGIN // axes
			WRITE_BYTE 0x1e (cleric BAND 0b01111111)
			WRITE_BYTE 0x1f (mcler BAND 0b00111000)
	        PATCH_FOR_EACH offset IN
	          ~0x50~
	          ~0x54~
	        BEGIN
	          READ_LONG ~%offset%~ desc_strref
	          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
	            READ_STRREF ~%offset%~ desc
	           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
	           	  STR_VAR
	           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
	           	    unusable_replacement = ~Not Usable By:~
	           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
	           	    class_prefix = ~ ~
	           	END
	          END
	        END
		END
	END
BUT_ONLY
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1e cleric 
		READ_BYTE  0x1f mcler 
		PATCH_IF (type = 19) BEGIN // small swords
			WRITE_BYTE 0x1e (cleric BAND 0b01111111)
			WRITE_BYTE 0x1f (mcler BAND 0b00111000)
	        PATCH_FOR_EACH offset IN
	          ~0x50~
	          ~0x54~
	        BEGIN
	          READ_LONG ~%offset%~ desc_strref
	          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
	            READ_STRREF ~%offset%~ desc
	           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
	           	  STR_VAR
	           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
	           	    unusable_replacement = ~Not Usable By:~
	           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
	           	    class_prefix = ~ ~
	           	END
	          END
	        END
		END
	END
BUT_ONLY
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1e cleric 
		READ_BYTE  0x1f mcler 
		PATCH_IF (type = 20) BEGIN // large swords
			WRITE_BYTE 0x1e (cleric BAND 0b01111111)
			WRITE_BYTE 0x1f (mcler BAND 0b00111000)
	        PATCH_FOR_EACH offset IN
	          ~0x50~
	          ~0x54~
	        BEGIN
	          READ_LONG ~%offset%~ desc_strref
	          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
	            READ_STRREF ~%offset%~ desc
	           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
	           	  STR_VAR
	           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
	           	    unusable_replacement = ~Not Usable By:~
	           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
	           	    class_prefix = ~ ~
	           	END
	          END
	        END
		END
	END
BUT_ONLY
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1e cleric 
		READ_BYTE  0x1f mcler 
		PATCH_IF (type = 16) BEGIN // daggers
			WRITE_BYTE 0x1e (cleric BAND 0b01111111)
			WRITE_BYTE 0x1f (mcler BAND 0b00111000)
	        PATCH_FOR_EACH offset IN
	          ~0x50~
	          ~0x54~
	        BEGIN
	          READ_LONG ~%offset%~ desc_strref
	          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
	            READ_STRREF ~%offset%~ desc
	           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
	           	  STR_VAR
	           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
	           	    unusable_replacement = ~Not Usable By:~
	           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
	           	    class_prefix = ~ ~
	           	END
	          END
	        END
		END
	END
BUT_ONLY
*/
// END
//END
//__________________________________________________________________________________


//DELETE NPCS' PROFICIENCIES________________________________________________________
//
COPY_EXISTING_REGEXP GLOB ~^.+\.cre$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
	READ_LONG 0x1cc biography
	PATCH_IF (biography > 0 && biography < 2147483647) BEGIN // party-joinable NPC
	  LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	END
  END
BUT_ONLY
//__________________________________________________________________________________


//SET NPCS TO LEVEL 1_______________________________________________________________
//
COPY_EXISTING_REGEXP GLOB ~^.+\.cre$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
	READ_LONG 0x1cc biography
	PATCH_IF (biography > 0 && biography < 2147483647) BEGIN // party-joinable NPC
	  READ_BYTE 0x23d npc_con
	  READ_BYTE 0x273 npc_class
	  PATCH_IF (npc_class = 2) BEGIN 	//	fighter
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 10
		  WRITE_SHORT 0x0026 10
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 11
		  WRITE_SHORT 0x0026 11
		END
		PATCH_IF (npc_con = 16) BEGIN
		  WRITE_SHORT 0x0024 12
		  WRITE_SHORT 0x0026 12
		END
		PATCH_IF (npc_con = 17) BEGIN
		  WRITE_SHORT 0x0024 13
		  WRITE_SHORT 0x0026 13
		END
		PATCH_IF (npc_con > 17) BEGIN
		  WRITE_SHORT 0x0024 14
		  WRITE_SHORT 0x0026 14
		END
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 111 1
		SET_BG2_PROFICIENCY 113 1
		SET_BG2_PROFICIENCY 114 1
	  END
	  PATCH_IF (npc_class = 6) BEGIN 	//	paladin
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 10
		  WRITE_SHORT 0x0026 10
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 11
		  WRITE_SHORT 0x0026 11
		END
		PATCH_IF (npc_con = 16) BEGIN
		  WRITE_SHORT 0x0024 12
		  WRITE_SHORT 0x0026 12
		END
		PATCH_IF (npc_con = 17) BEGIN
		  WRITE_SHORT 0x0024 13
		  WRITE_SHORT 0x0026 13
		END
		PATCH_IF (npc_con > 17) BEGIN
		  WRITE_SHORT 0x0024 14
		  WRITE_SHORT 0x0026 14
		END
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
		SET_BG2_PROFICIENCY 112 1
	  END
	  PATCH_IF (npc_class = 12) BEGIN 	//	ranger
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 10
		  WRITE_SHORT 0x0026 10
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 11
		  WRITE_SHORT 0x0026 11
		END
		PATCH_IF (npc_con = 16) BEGIN
		  WRITE_SHORT 0x0024 12
		  WRITE_SHORT 0x0026 12
		END
		PATCH_IF (npc_con = 17) BEGIN
		  WRITE_SHORT 0x0024 13
		  WRITE_SHORT 0x0026 13
		END
		PATCH_IF (npc_con > 17) BEGIN
		  WRITE_SHORT 0x0024 14
		  WRITE_SHORT 0x0026 14
		END
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 2
	  END
	  PATCH_IF (npc_class = 4) BEGIN 	//	thief
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 6
		  WRITE_SHORT 0x0026 6
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 7
		  WRITE_SHORT 0x0026 7
		END
		PATCH_IF (npc_con > 15) BEGIN
		  WRITE_SHORT 0x0024 8
		  WRITE_SHORT 0x0026 8
		END
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
	  END
	  PATCH_IF (npc_class = 5) BEGIN 	//	bard
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 6
		  WRITE_SHORT 0x0026 6
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 7
		  WRITE_SHORT 0x0026 7
		END
		PATCH_IF (npc_con > 15) BEGIN
		  WRITE_SHORT 0x0024 8
		  WRITE_SHORT 0x0026 8
		END
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
	  END
	  PATCH_IF (npc_class = 3) BEGIN 	//	cleric
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 8
		  WRITE_SHORT 0x0026 8
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 9
		  WRITE_SHORT 0x0026 9
		END
		PATCH_IF (npc_con > 15) BEGIN
		  WRITE_SHORT 0x0024 10
		  WRITE_SHORT 0x0026 10
		END
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
	  END
	  PATCH_IF (npc_class = 11) BEGIN 	//	druid
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 8
		  WRITE_SHORT 0x0026 8
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 9
		  WRITE_SHORT 0x0026 9
		END
		PATCH_IF (npc_con > 15) BEGIN
		  WRITE_SHORT 0x0024 10
		  WRITE_SHORT 0x0026 10
		END
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 111 1
		SET_BG2_PROFICIENCY 113 1
	  END
	  PATCH_IF (npc_class = 20) BEGIN 	//	monk
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 8
		  WRITE_SHORT 0x0026 8
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 9
		  WRITE_SHORT 0x0026 9
		END
		PATCH_IF (npc_con = 16) BEGIN
		  WRITE_SHORT 0x0024 10
		  WRITE_SHORT 0x0026 10
		END
		PATCH_IF (npc_con = 17) BEGIN
		  WRITE_SHORT 0x0024 11
		  WRITE_SHORT 0x0026 11
		END
		PATCH_IF (npc_con > 17) BEGIN
		  WRITE_SHORT 0x0024 12
		  WRITE_SHORT 0x0026 12
		END
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 113 1
	  END
	  PATCH_IF (npc_class = 1) BEGIN 	// 	mage
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
	  END
	  PATCH_IF (npc_class = 19) BEGIN 	//	sorcerer
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
	  END
	  PATCH_IF (npc_class = 21) BEGIN 	//	shaman
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 8
		  WRITE_SHORT 0x0026 8
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 9
		  WRITE_SHORT 0x0026 9
		END
		PATCH_IF (npc_con > 15) BEGIN
		  WRITE_SHORT 0x0024 10
		  WRITE_SHORT 0x0026 10
		END
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 113 1
	  END
	  PATCH_IF (%npc_class% = 7) BEGIN 	//	fighter/mage
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 7
		  WRITE_SHORT 0x0026 7
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 8
		  WRITE_SHORT 0x0026 8
		END
		PATCH_IF (npc_con = 16) BEGIN
		  WRITE_SHORT 0x0024 9
		  WRITE_SHORT 0x0026 9
		END
		PATCH_IF (npc_con = 17) BEGIN
		  WRITE_SHORT 0x0024 10
		  WRITE_SHORT 0x0026 10
		END
		PATCH_IF (npc_con > 17) BEGIN
		  WRITE_SHORT 0x0024 11
		  WRITE_SHORT 0x0026 11
		END
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
	  END
	  PATCH_IF (%npc_class% = 8) BEGIN 	//	fighter/cleric
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 9
		  WRITE_SHORT 0x0026 9
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 10
		  WRITE_SHORT 0x0026 10
		END
		PATCH_IF (npc_con = 16) BEGIN
		  WRITE_SHORT 0x0024 11
		  WRITE_SHORT 0x0026 11
		END
		PATCH_IF (npc_con = 17) BEGIN
		  WRITE_SHORT 0x0024 12
		  WRITE_SHORT 0x0026 12
		END
		PATCH_IF (npc_con > 17) BEGIN
		  WRITE_SHORT 0x0024 13
		  WRITE_SHORT 0x0026 13
		END
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
		SET_BG2_PROFICIENCY 113 1
	  END
	  PATCH_IF (%npc_class% = 9) BEGIN 	//	fighter/thief
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 8
		  WRITE_SHORT 0x0026 8
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 9
		  WRITE_SHORT 0x0026 9
		END
		PATCH_IF (npc_con = 16) BEGIN
		  WRITE_SHORT 0x0024 10
		  WRITE_SHORT 0x0026 10
		END
		PATCH_IF (npc_con = 17) BEGIN
		  WRITE_SHORT 0x0024 11
		  WRITE_SHORT 0x0026 11
		END
		PATCH_IF (npc_con > 17) BEGIN
		  WRITE_SHORT 0x0024 12
		  WRITE_SHORT 0x0026 12
		END
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
	  END
	  PATCH_IF (%npc_class% = 10) BEGIN	//	fighter/mage/thief
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 7
		  WRITE_SHORT 0x0026 7
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 8
		  WRITE_SHORT 0x0026 8
		END
		PATCH_IF (npc_con = 16) BEGIN
		  WRITE_SHORT 0x0024 9
		  WRITE_SHORT 0x0026 9
		END
		PATCH_IF (npc_con = 17) BEGIN
		  WRITE_SHORT 0x0024 10
		  WRITE_SHORT 0x0026 10
		END
		PATCH_IF (npc_con > 17) BEGIN
		  WRITE_SHORT 0x0024 11
		  WRITE_SHORT 0x0026 11
		END
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
	  END
	  PATCH_IF (%npc_class% = 13) BEGIN	//	mage/thief
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 6
		  WRITE_SHORT 0x0026 6
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 7
		  WRITE_SHORT 0x0026 7
		END
		PATCH_IF (npc_con > 15) BEGIN
		  WRITE_SHORT 0x0024 8
		  WRITE_SHORT 0x0026 8
		END
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
	  END
	  PATCH_IF (%npc_class% = 14) BEGIN	//	cleric/mage
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 6
		  WRITE_SHORT 0x0026 6
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 7
		  WRITE_SHORT 0x0026 7
		END
		PATCH_IF (npc_con > 15) BEGIN
		  WRITE_SHORT 0x0024 8
		  WRITE_SHORT 0x0026 8
		END
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
	  END
	  PATCH_IF (%npc_class% = 15) BEGIN	//	cleric/thief
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 7
		  WRITE_SHORT 0x0026 7
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 8
		  WRITE_SHORT 0x0026 8
		END
		PATCH_IF (npc_con > 15) BEGIN
		  WRITE_SHORT 0x0024 9
		  WRITE_SHORT 0x0026 9
		END
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
	  END
	  PATCH_IF (%npc_class% = 16) BEGIN	//	fighter/druid
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 9
		  WRITE_SHORT 0x0026 9
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 10
		  WRITE_SHORT 0x0026 10
		END
		PATCH_IF (npc_con = 16) BEGIN
		  WRITE_SHORT 0x0024 11
		  WRITE_SHORT 0x0026 11
		END
		PATCH_IF (npc_con = 17) BEGIN
		  WRITE_SHORT 0x0024 12
		  WRITE_SHORT 0x0026 12
		END
		PATCH_IF (npc_con > 17) BEGIN
		  WRITE_SHORT 0x0024 13
		  WRITE_SHORT 0x0026 13
		END
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 111 1
		SET_BG2_PROFICIENCY 113 1
	  END
	  PATCH_IF (%npc_class% = 17) BEGIN	//	fighter/mage/cleric
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 7
		  WRITE_SHORT 0x0026 7
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 8
		  WRITE_SHORT 0x0026 8
		END
		PATCH_IF (npc_con = 16) BEGIN
		  WRITE_SHORT 0x0024 9
		  WRITE_SHORT 0x0026 9
		END
		PATCH_IF (npc_con = 17) BEGIN
		  WRITE_SHORT 0x0024 10
		  WRITE_SHORT 0x0026 10
		END
		PATCH_IF (npc_con > 17) BEGIN
		  WRITE_SHORT 0x0024 11
		  WRITE_SHORT 0x0026 11
		END
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 113 1
	  END
	  PATCH_IF (%npc_class% = 18) BEGIN	//	cleric/ranger
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		PATCH_IF (npc_con < 15) BEGIN
		  WRITE_SHORT 0x0024 9
		  WRITE_SHORT 0x0026 9
		END
		PATCH_IF (npc_con = 15) BEGIN
		  WRITE_SHORT 0x0024 10
		  WRITE_SHORT 0x0026 10
		END
		PATCH_IF (npc_con = 16) BEGIN
		  WRITE_SHORT 0x0024 11
		  WRITE_SHORT 0x0026 11
		END
		PATCH_IF (npc_con = 17) BEGIN
		  WRITE_SHORT 0x0024 12
		  WRITE_SHORT 0x0026 12
		END
		PATCH_IF (npc_con > 17) BEGIN
		  WRITE_SHORT 0x0024 13
		  WRITE_SHORT 0x0026 13
		END
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 2
	  END
	END
  END
BUT_ONLY
//__________________________________________________________________________________


//MnG KENSAI________________________________________________________________________
// 
ACTION_IF FILE_EXISTS_IN_GAME ~d5_kensai.d5~ BEGIN
	COPY ~scales_of_balance/profs/d5_kenf.spl~ ~override~
		SAY NAME1 @2632
		SAY UNIDENTIFIED_DESC @2632
	COPY ~scales_of_balance/profs/d5_kens.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_klswo.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_ksswo.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_kdagg.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_kscim.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_k2swo.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_kspea.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_kstaf.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_kclub.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_kmace.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_kflai.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_khamm.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_kbaxe.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_kenf.cre~ ~override~
	COMPILE ~scales_of_balance/profs/d5_kenf2.baf~
	COPY_EXISTING ~d5_klswo.2da~ ~override~
				~d5_ksswo.2da~ ~override~
				~d5_kdagg.2da~ ~override~
				~d5_kscim.2da~ ~override~
				~d5_kkata.2da~ ~override~
				~d5_kbswo.2da~ ~override~
				~d5_k2swo.2da~ ~override~
				~d5_khalb.2da~ ~override~
				~d5_kspea.2da~ ~override~
				~d5_kstaf.2da~ ~override~
				~d5_kclub.2da~ ~override~
				~d5_kmace.2da~ ~override~
				~d5_kflai.2da~ ~override~
				~d5_khamm.2da~ ~override~
				~d5_kbaxe.2da~ ~override~
		REPLACE_TEXTUALLY ~D5_KENF2~ ~****    ~
		REPLACE_TEXTUALLY ~D5_KENF3~ ~****    ~
		REPLACE_TEXTUALLY ~D5_KENF4~ ~****    ~
		REPLACE_TEXTUALLY ~D5_KENF5~ ~****    ~
		REPLACE_TEXTUALLY ~D5_KENF6~ ~****    ~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/kensai_focus.txt~

  ACTION_IF (FILE_EXISTS_IN_GAME ~clastext.2da~) BEGIN
	COPY_EXISTING ~clastext.2da~ ~override~
		SET_2DA_ENTRY 6 4 1 RESOLVE_STR_REF (@2648)
	BUT_ONLY
  END
  ACTION_IF (FILE_EXISTS_IN_GAME ~sodcltxt.2da~) BEGIN
	COPY_EXISTING ~sodcltxt.2da~ ~override~
		SET_2DA_ENTRY 6 4 1 RESOLVE_STR_REF (@2648)
	BUT_ONLY
  END
  ACTION_IF ENGINE_IS ~tob~ BEGIN
	STRING_SET 25204 @2648
  END
END
//__________________________________________________________________________________


//WEAPONS OF FOCUS__________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ BEGIN

  INCLUDE ~scales_of_balance/ini/stats.ini~

  COPY ~scales_of_balance/profs/d5_lswo.spl~ ~override~
  COPY ~scales_of_balance/profs/d5_sswo.spl~ ~override~
  COPY ~scales_of_balance/profs/d5_dagg.spl~ ~override~
  COPY ~scales_of_balance/profs/d5_scim.spl~ ~override~
  COPY ~scales_of_balance/profs/d5_2swo.spl~ ~override~
  COPY ~scales_of_balance/profs/d5_spea.spl~ ~override~
  COPY ~scales_of_balance/profs/d5_staf.spl~ ~override~
  COPY ~scales_of_balance/profs/d5_club.spl~ ~override~
  COPY ~scales_of_balance/profs/d5_flai.spl~ ~override~
  COPY ~scales_of_balance/profs/d5_hamm.spl~ ~override~
  COPY ~scales_of_balance/profs/d5_baxe.spl~ ~override~
  COPY ~scales_of_balance/profs/d5_bows.spl~ ~override~
  COPY ~scales_of_balance/profs/d5_slin.spl~ ~override~
  COPY ~scales_of_balance/profs/d5_xbow.spl~ ~override~

  COPY ~scales_of_balance/profs/d5wepf1.spl~ ~override~
  COPY ~scales_of_balance/profs/d5wepf1.eff~ ~override~
  COPY ~scales_of_balance/profs/d5wepfa.spl~ ~override~
	SAY NAME1 @12300
	SAY UNIDENTIFIED_DESC @12300
	WRITE_ASCII 0x3a ~d5_wepfo~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wepfo~ END
  COPY ~scales_of_balance/profs/d5wepf2.spl~ ~override~
  COPY ~scales_of_balance/profs/d5wepf2.eff~ ~override~
  COPY ~scales_of_balance/profs/d5wepfb.spl~ ~override~
	SAY NAME1 @12300
	SAY UNIDENTIFIED_DESC @12300
	WRITE_ASCII 0x3a ~d5_wepfo~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wepfo~ END
  COPY ~scales_of_balance/profs/d5wepf3.spl~ ~override~
  COPY ~scales_of_balance/profs/d5wepf3.eff~ ~override~
  COPY ~scales_of_balance/profs/d5wepfc.spl~ ~override~
	SAY NAME1 @12300
	SAY UNIDENTIFIED_DESC @12300
	WRITE_ASCII 0x3a ~d5_wepfo~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wepfo~ END
  COPY ~scales_of_balance/profs/d5wepf4.spl~ ~override~
  COPY ~scales_of_balance/profs/d5wepf4.eff~ ~override~
  COPY ~scales_of_balance/profs/d5wepfd.spl~ ~override~
	SAY NAME1 @12300
	SAY UNIDENTIFIED_DESC @12300
	WRITE_ASCII 0x3a ~d5_wepfo~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wepfo~ END
  COPY ~scales_of_balance/profs/d5wepf5.spl~ ~override~
  COPY ~scales_of_balance/profs/d5wepf5.eff~ ~override~
  COPY ~scales_of_balance/profs/d5wepfe.spl~ ~override~
	SAY NAME1 @12300
	SAY UNIDENTIFIED_DESC @12300
	WRITE_ASCII 0x3a ~d5_wepfo~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wepfo~ END
  COPY ~scales_of_balance/profs/d5_wepfo.bam~ ~override~
  COPY ~scales_of_balance/profs/d5_wepfo.eff~ ~override~
  COPY ~scales_of_balance/profs/d5_wepfo.cre~ ~override~
  COMPILE ~scales_of_balance/profs/d5_wepfo.baf~
  COMPILE ~scales_of_balance/profs/d5_wepfo.d~

  APPEND ~splprot.2da~ ~D5_INT_GTEQ%TAB%38%TAB%-1%TAB%4~

  COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	COUNT_2DA_ROWS cols rows // amount of rows
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
      READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_INT_GTEQ~ BEGIN
    	SET int_gteq_row = %row%
      END
	END
  BUT_ONLY

  COPY ~scales_of_balance/profs/d5iprf5.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = %int_prof_1% parameter2 = %int_gteq_row% END
  COPY ~scales_of_balance/profs/d5iprf4.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = %int_prof_2% parameter2 = %int_gteq_row% END


  ACTION_IF FILE_EXISTS_IN_GAME ~clabfi01.2da~ BEGIN
	COPY_EXISTING ~clabfi01.2da~ ~override~
		APPEND_FILE ~scales_of_balance/profs/fighter_focus_2.txt~
		APPEND_FILE ~scales_of_balance/profs/warrior_intprof.txt~
		APPEND_FILE ~scales_of_balance/profs/warrior_apr.txt~
	BUT_ONLY
  END
  ACTION_IF FILE_EXISTS_IN_GAME ~clabrn01.2da~ BEGIN
	COPY_EXISTING ~clabfi01.2da~ ~override~
		APPEND_FILE ~scales_of_balance/profs/warrior_intprof.txt~
		APPEND_FILE ~scales_of_balance/profs/warrior_apr.txt~
	BUT_ONLY
  END
  ACTION_IF FILE_EXISTS_IN_GAME ~clabpa01.2da~ BEGIN
	COPY_EXISTING ~clabfi01.2da~ ~override~
		APPEND_FILE ~scales_of_balance/profs/warrior_intprof.txt~
		APPEND_FILE ~scales_of_balance/profs/warrior_apr.txt~
	BUT_ONLY
  END

  COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS ~9~ "rows"
	FOR ( index = 2 ; index < rows ; index = index + 1 ) BEGIN
		READ_2DA_ENTRY %index% 5 9 modclab
		READ_2DA_ENTRY %index% 8 9 modclass
		DEFINE_ASSOCIATIVE_ARRAY d5_feat_array BEGIN "%modclab%" => "%modclass%" END
	END
  BUT_ONLY
/*
  ACTION_PHP_EACH d5_feat_array AS hu => lu BEGIN
	ACTION_IF (%lu% = 2) AND (FILE_EXISTS_IN_GAME ~%hu%.2da~) BEGIN
		COPY_EXISTING ~%hu%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~scales_of_balance/profs/warrior_intprof.txt~
			APPEND_FILE ~scales_of_balance/profs/warrior_apr.txt~
		BUT_ONLY
	END
	ACTION_IF (%lu% = 6) AND (FILE_EXISTS_IN_GAME ~%hu%.2da~) BEGIN
		COPY_EXISTING ~%hu%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~scales_of_balance/profs/warrior_intprof.txt~
			APPEND_FILE ~scales_of_balance/profs/warrior_apr.txt~
		BUT_ONLY
	END
	ACTION_IF (%lu% = 12) AND (FILE_EXISTS_IN_GAME ~%hu%.2da~) BEGIN
		COPY_EXISTING ~%hu%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~scales_of_balance/profs/warrior_intprof.txt~
			APPEND_FILE ~scales_of_balance/profs/warrior_apr.txt~
		BUT_ONLY
	END
  END
*/
  ACTION_IF FILE_EXISTS_IN_GAME ~d5_marks.2da~ BEGIN
	COPY_EXISTING ~d5_marks.2da~ ~override~
		APPEND_FILE ~scales_of_balance/profs/warrior_focus.txt~
		REPLACE_TEXTUALLY ~AP_D5WEPF1~ ~AP_D5_XBOW~
		APPEND_FILE ~scales_of_balance/profs/warrior_focus.txt~
		REPLACE_TEXTUALLY ~AP_D5WEPF1~ ~AP_D5_BOWS~
	BUT_ONLY
  END
  ACTION_IF FILE_EXISTS_IN_GAME ~d5_earch.2da~ BEGIN
	COPY_EXISTING ~d5_earch.2da~ ~override~
		APPEND_FILE ~scales_of_balance/profs/warrior_focus.txt~
		REPLACE_TEXTUALLY ~AP_D5WEPF1~ ~AP_D5_BOWS~
	BUT_ONLY
  END
  ACTION_IF FILE_EXISTS_IN_GAME ~d5_sling.2da~ BEGIN
	COPY_EXISTING ~d5_sling.2da~ ~override~
		APPEND_FILE ~scales_of_balance/profs/warrior_focus.txt~
		REPLACE_TEXTUALLY ~AP_D5WEPF1~ ~AP_D5_SLIN~
	BUT_ONLY
  END

END
//__________________________________________________________________________________



//UPDATE SoA STARTING XP____________________________________________________________
// 
ACTION_IF GAME_IS ~tob~ AND NOT GAME_IS ~bgt~ THEN BEGIN
	ACTION_IF FILE_EXISTS ~bgmain.exe~ BEGIN
		COPY ~bgmain.exe~ ~bgmain.exe~
			SET i = 1
			WHILE (i>0) BEGIN
				SET i += 4
				READ_LONG (0x6b0000 + "%i%" - 1) long_value //start at offset 0x6b0000
				READ_LONG (0x6b0000 + "%i%" - 5) long_before_value
				READ_LONG (0x6b0000 + "%i%" + 3) long_after_value
				PATCH_IF ("%long_before_value%" = 0) AND ("%long_after_value%" = 161000) THEN BEGIN //look only for a long value bounded by a previous value of 0, and a next value of 161000
					WRITE_LONG (0x6b0000 + "%i%" - 1) 1 //setting to zero causes thieving skills to isolate from proficiencies and screws up skill types
				END
				PATCH_IF ("%i%" = 0x10001) BEGIN //span a region of 0x10000 bytes
					SET i = 0
				END
			END
	END
	EXTEND_BOTTOM ~ar0602.bcs~ ~scales_of_balance/misc/soaxp.baf~
END

ACTION_IF GAME_IS ~bg2ee~ THEN BEGIN
	COPY_EXISTING ~startare.2da~ ~override~
		SET_2DA_ENTRY 12 1 1 ~1000~
		BUT_ONLY
	EXTEND_BOTTOM ~ar0602.bcs~ ~scales_of_balance/misc/soaxp.baf~
END
//__________________________________________________________________________________


CLEAR_ARRAYS
