
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						WPO - MAJOR OVERHAUL
//__________________________________________________________________________________
//__________________________________________________________________________________


//COPY MARKER FILE_________________________________________________________________
//
COPY ~scales_of_balance/profs/d5_profs.d5~ ~override~
//__________________________________________________________________________________


//RESPECT PROFSMAX!_________________________________________________________________
//
ACTION_IF MOD_IS_INSTALLED "TOBEX.TP2" "100" THEN BEGIN
	COPY ~TobEx_ini/TobExTweak.ini~ ~TobEx_ini~
		REPLACE_TEXTUALLY ~Proficiency Restrictions=0~ ~Proficiency Restrictions=1~
	BUT_ONLY
END
//__________________________________________________________________________________


//PROF BONUSES______________________________________________________________________
//
COPY ~scales_of_balance/profs/wspat3.2da~ ~override/wspatck.2da~

COPY ~scales_of_balance/profs/wspecial2.2da~ ~override/wspecial.2da~
//__________________________________________________________________________________
	

//UPDATE CLASS STRINGS______________________________________________________________
//
STRING_SET 9556 @1214
STRING_SET 9557 @1215
STRING_SET 9558 @1216
STRING_SET 9559 @1217
STRING_SET 9560 @1218
STRING_SET 9561 @1219
STRING_SET 9562 @1220
STRING_SET 9563 @1221
//__________________________________________________________________________________


//UPDATE PROFICIENCY STRINGS_________________________________________________________
//
/*
COPY_EXISTING ~weapprof.2da~ ~override~
	SET_2DA_ENTRY 12 3 1 RESOLVE_STR_REF (@1230)
	SET_2DA_ENTRY 13 3 1 RESOLVE_STR_REF (@1231)
	SET_2DA_ENTRY 14 3 1 RESOLVE_STR_REF (@1232)
	SET_2DA_ENTRY 15 3 1 RESOLVE_STR_REF (@1233)
	SET_2DA_ENTRY 17 3 1 RESOLVE_STR_REF (@1234)
	SET_2DA_ENTRY 18 3 1 RESOLVE_STR_REF (@1235)
	SET_2DA_ENTRY 19 3 1 RESOLVE_STR_REF (@1236)
	SET_2DA_ENTRY 20 3 1 RESOLVE_STR_REF (@1237)
	SET_2DA_ENTRY 21 3 1 RESOLVE_STR_REF (@1238)
	SET_2DA_ENTRY 23 3 1 RESOLVE_STR_REF (@1239)
	SET_2DA_ENTRY 24 3 1 RESOLVE_STR_REF (@1240)
	SET_2DA_ENTRY 25 3 1 RESOLVE_STR_REF (@1241)
	SET_2DA_ENTRY 26 3 1 RESOLVE_STR_REF (@1242)
	SET_2DA_ENTRY 28 3 1 RESOLVE_STR_REF (@1243)
	SET_2DA_ENTRY 30 3 1 RESOLVE_STR_REF (@1244)
BUT_ONLY
*/

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25025 @1230
	STRING_SET 25026 @1231
	STRING_SET 25027 @1232
	STRING_SET 25028 @1233
	STRING_SET 25030 @1234
	STRING_SET 25031 @1235
	STRING_SET 25032 @1236
	STRING_SET 25033 @1237
	STRING_SET 25034 @1238
	STRING_SET 25036 @1239
	STRING_SET 25037 @1240
	STRING_SET 25038 @1241
	STRING_SET 25039 @1242
	STRING_SET 25041 @1243
	STRING_SET 25043 @1244
END
ACTION_IF GAME_IS ~tob bgt tutu bg2ee eet~ THEN BEGIN
	STRING_SET 34147 @1230
	STRING_SET 34148 @1231
	STRING_SET 34149 @1232
	STRING_SET 34150 @1233
	STRING_SET 34152 @1234
	STRING_SET 34153 @1235
	STRING_SET 34156 @1236
	STRING_SET 35442 @1237
	STRING_SET 34157 @1238
	STRING_SET 34159 @1239
	STRING_SET 34160 @1240
	STRING_SET 34161 @1241
	STRING_SET 34162 @1242
	STRING_SET 34164 @1243
	STRING_SET 34166 @1244
END
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
	STRING_SET 36802 @1230 // long sw
	STRING_SET 36804 @1231 // short sw
	STRING_SET 36806 @1232 // axe
	STRING_SET 36808 @1233 // 2-H sw
	STRING_SET 36812 @1234 // scimitar
	STRING_SET 36814 @1235 // dagger
	STRING_SET 36816 @1236 // hammer
	STRING_SET 36818 @1237 // club
	STRING_SET 36820 @1238 // spear
	STRING_SET 37712 @1239 // flail
	STRING_SET 37714 @1240 // mace
	STRING_SET 37716 @1241 // staff
	STRING_SET 37718 @1242 // xbow
	STRING_SET 37722 @1243 // shortbow
	STRING_SET 37726 @1244 // sling
END
//__________________________________________________________________________________


//AMEND WEAPPROF.2da_______________________________________________________________
//
COPY_EXISTING ~weapprof.2da~ ~override~
	REPLACE_TEXTUALLY ~ ID ~ ~ TYPE ID ~
	REPLACE_TEXTUALLY ~ 2 ~ ~ 4 ~
	REPLACE_TEXTUALLY ~ 3 ~ ~ 4 ~
	SET_2DA_ENTRY_LATER ~#weapprof~ 5 1 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 8 1 5
	// Fighter
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 5 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 5 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 5 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 5 3
	// Cleric
	SET_2DA_ENTRY_LATER ~#weapprof~ 7 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 8 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 10 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 6 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 6 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 6 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 6 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 6 0
	// Thief
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 7 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 7 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 7 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 7 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 7 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 7 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 7 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 7 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 7 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 7 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 7 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 7 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 7 3
	// Bard
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 8 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 8 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 8 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 8 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 8 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 8 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 8 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 8 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 8 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 8 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 8 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 8 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 8 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 8 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 8 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 8 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 8 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 8 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 8 2
	// Paladin
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 9 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 9 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 9 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 9 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 9 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 9 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 9 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 9 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 9 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 9 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 9 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 9 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 9 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 9 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 9 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 9 2
	// Druid
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 10 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 10 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 10 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 10 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 10 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 10 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 10 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 10 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 10 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 10 2
	// Ranger
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 11 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 11 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 11 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 11 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 11 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 11 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 11 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 11 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 11 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 11 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 11 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 11 3
	// Fighter/Mage
//	SET_2DA_ENTRY_LATER ~#weapprof~ 12 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 13 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 14 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 15 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 17 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 18 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 19 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 20 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 21 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 23 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 25 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 26 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 28 12 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 30 12 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 12 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 12 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 12 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 12 0
	// Fighter/Cleric
//	SET_2DA_ENTRY_LATER ~#weapprof~ 12 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 13 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 14 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 15 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 17 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 18 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 19 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 20 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 21 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 23 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 24 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 25 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 26 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 28 13 3
//	SET_2DA_ENTRY_LATER ~#weapprof~ 30 13 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 13 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 13 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 13 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 13 0
	// Fighter/Thief
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 14 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 14 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 14 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 15 3
	// Fighter/Mage/Thief
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 15 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 15 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 15 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 15 3
	// Mage/Thief
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 16 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 16 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 16 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 16 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 16 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 16 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 16 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 16 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 16 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 16 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 16 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 16 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 16 3
	// Cleric/Mage
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 17 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 17 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 17 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 17 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 17 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 17 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 17 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 17 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 17 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 17 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 17 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 17 0
	// Cleric/Thief
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 18 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 18 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 18 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 18 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 18 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 18 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 18 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 18 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 18 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 18 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 18 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 18 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 18 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 18 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 18 3
	// Fighter/Druid
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 19 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 19 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 19 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 19 3
	// Fighter/Mage/Cleric
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 20 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 20 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 20 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 20 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 20 0
	// Ranger/Cleric
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 21 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 21 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 21 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 21 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 21 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 21 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 21 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 21 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 21 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 21 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 21 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 21 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 21 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 21 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 21 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 21 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 21 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 21 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 21 3
	// Wizards
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 4 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 4 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 22 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 22 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 23 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 23 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 24 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 24 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 25 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 25 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 26 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 26 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 27 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 27 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 28 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 28 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 29 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 29 1
	// Berserker
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 30 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 30 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 30 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 30 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 30 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 30 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 30 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 30 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 30 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 30 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 30 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 30 3
	// Wizard Slayer
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 31 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 31 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 31 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 31 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 31 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 31 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 31 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 31 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 31 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 31 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 31 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 31 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 31 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 31 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 31 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 31 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 31 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 31 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 31 3
	// Kensai
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 32 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 32 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 32 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 32 3
	// Cavalier
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 33 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 33 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 33 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 33 2
	// Inquisitor
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 34 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 34 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 34 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 34 2
	// Undead Hunter
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 35 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 35 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 35 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 35 2
	// Archer
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 36 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 36 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 36 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 36 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 36 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 36 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 36 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 36 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 36 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 36 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 36 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 36 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 36 5
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 36 5
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 36 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 36 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 36 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 36 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 36 2
	// Stalker
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 37 5
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 37 5
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 37 5
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 37 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 37 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 37 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 37 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 37 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 37 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 37 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 37 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 37 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 37 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 37 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 37 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 37 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 37 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 37 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 37 3
	// Beastmaster
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 38 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 38 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 38 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 38 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 38 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 38 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 38 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 38 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 38 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 38 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 38 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 38 3
	// Assassin
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 39 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 39 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 39 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 39 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 39 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 39 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 39 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 39 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 39 3
	// Bounty Hunter
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 40 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 40 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 40 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 40 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 40 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 40 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 40 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 40 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 40 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 40 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 40 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 40 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 40 3
	// Swashbuckler
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 41 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 41 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 41 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 41 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 41 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 41 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 41 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 41 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 41 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 41 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 41 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 41 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 41 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 41 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 41 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 41 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 41 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 41 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 41 3
	// Blade
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 42 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 42 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 42 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 42 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 42 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 42 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 42 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 42 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 42 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 42 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 42 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 42 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 42 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 42 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 42 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 42 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 42 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 42 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 42 3
	// Jester
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 43 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 43 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 43 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 43 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 43 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 43 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 43 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 43 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 43 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 43 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 43 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 43 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 43 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 43 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 43 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 43 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 43 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 43 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 43 2
	// Skald
	SET_2DA_ENTRY_LATER ~#weapprof~ 12 44 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 13 44 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 44 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 44 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 44 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 44 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 44 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 44 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 44 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 44 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 44 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 44 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 44 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 28 44 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 44 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 44 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 44 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 44 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 44 2
	// Totemic Driud
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 45 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 45 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 45 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 45 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 45 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 45 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 45 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 45 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 45 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 45 2
	// Shapeshifter
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 46 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 46 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 46 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 46 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 46 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 46 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 46 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 46 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 46 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 46 2
	// Avenger
	SET_2DA_ENTRY_LATER ~#weapprof~ 17 47 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 18 47 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 47 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 47 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 47 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 47 3
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 47 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 47 0
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 47 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 47 2
	// Talos
	SET_2DA_ENTRY_LATER ~#weapprof~ 7 48 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 8 48 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 10 48 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 48 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 48 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 48 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 48 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 48 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 48 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 48 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 48 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 48 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 48 0
	// Helm
	SET_2DA_ENTRY_LATER ~#weapprof~ 7 49 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 8 49 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 10 49 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 49 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 49 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 49 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 49 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 49 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 49 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 49 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 49 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 49 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 49 0
	// Lathander
	SET_2DA_ENTRY_LATER ~#weapprof~ 7 50 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 8 50 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 10 50 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 19 50 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 23 50 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 50 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 25 50 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 30 50 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 50 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 49 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 49 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 49 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 49 0
	// Monk
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 51 1
	// Barbarian
	SET_2DA_ENTRY_LATER ~#weapprof~ 14 52 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 15 52 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 52 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 21 52 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 24 52 4
	SET_2DA_ENTRY_LATER ~#weapprof~ 31 52 2
	SET_2DA_ENTRY_LATER ~#weapprof~ 32 52 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 33 52 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 34 52 1
	// Wild Mage	
	SET_2DA_ENTRY_LATER ~#weapprof~ 20 53 1
	SET_2DA_ENTRY_LATER ~#weapprof~ 26 53 1
	SET_2DA_ENTRIES_NOW ~#weapprof~ 1
	REPLACE_TEXTUALLY ~TYPE ~ ~      ~

ACTION_IF GAME_IS ~bgee bg2ee iwdee eet~ THEN BEGIN
	COPY_EXISTING ~weapprof.2da~ ~override~
		// Blackguard
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 20 54 4
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 31 54 1
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 32 54 1
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 33 54 1
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 34 54 2
		// Shadowdancer
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 12 55 3
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 13 55 3
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 17 55 3
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 18 55 3
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 20 55 3
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 25 55 3
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 26 55 3
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 28 55 3
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 30 55 3
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 31 55 0
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 32 55 0
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 33 55 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 34 55 3
		// Dwarven Defender
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 12 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 13 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 14 56 5
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 15 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 17 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 18 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 19 56 5
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 20 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 21 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 23 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 24 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 25 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 26 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 28 56 0
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 30 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 31 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 32 56 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 33 56 0
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 34 56 3
		// Dragon Disciple
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 20 57 1
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 26 57 1
		// Dark Moon Monk
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 20 58 1
		// Sun Soul Monk
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 20 59 1
		// Tyr
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 7 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 8 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 10 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 19 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 23 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 24 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 25 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 30 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 20 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 26 61 2
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 31 61 1
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 32 61 1
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 33 61 1
		SET_2DA_ENTRY_LATER ~EE#weapprof~ 34 61 0
	SET_2DA_ENTRIES_NOW ~EE#weapprof~ 1
END

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	COPY_EXISTING ~weapprof.2da~ ~override~
		// Shaman
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 9 60 3
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 14 60 3
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 17 60 0
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 18 60 3
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 20 60 3
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 21 60 3
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 25 60 3
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 28 60 3
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 30 60 3
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 31 60 1
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 32 60 0
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 33 60 1
		SET_2DA_ENTRY_LATER ~BEE#weapprof~ 34 60 2
	SET_2DA_ENTRIES_NOW ~BEE#weapprof~ 1
END
ACTION_IF GAME_IS ~bg2ee~ THEN BEGIN
	COPY_EXISTING ~weapprof.2da~ ~override~
		// Shaman
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 9 62 3
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 14 62 3
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 17 62 0
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 18 62 3
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 20 62 3
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 21 62 3
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 25 62 3
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 28 62 3
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 30 62 3
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 31 62 1
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 32 62 0
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 33 62 1
		SET_2DA_ENTRY_LATER ~2EE#weapprof~ 34 62 2
	SET_2DA_ENTRIES_NOW ~2EE#weapprof~ 1
END
	
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
	COPY_EXISTING ~weapprof.2da~ ~override~
/*
		// Tyr
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 7 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 8 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 10 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 19 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 23 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 24 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 25 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 30 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 20 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 26 61 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 31 61 1
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 32 61 1
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 33 61 1
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 34 61 0
*/
		// Tempus
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 7 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 8 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 10 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 19 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 23 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 24 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 25 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 30 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 20 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 26 62 2
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 31 62 1
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 32 62 1
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 33 62 1
		SET_2DA_ENTRY_LATER ~IEE#weapprof~ 34 62 0
	SET_2DA_ENTRIES_NOW ~IEE#weapprof~ 1
END
//__________________________________________________________________________________


//PROFICIENCIES FOR MOD CLERICS_____________________________________________________
//
DEFINE_ACTION_FUNCTION mod_cleric_profs BEGIN
	OUTER_SET count = 0

	ACTION_FOR_EACH class IN
                  cleric

	BEGIN
		OUTER_SPRINT $clerics("%count%") "%class%"
		OUTER_SET ++count
	END

	COPY_EXISTING kitlist.2da override
		READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 31; row < kitlist; ++row) BEGIN // Skip past the vanilla kits
			READ_2DA_ENTRY_FORMER kitlist row 1 label
			READ_2DA_ENTRY_FORMER kitlist row 8 class
			PATCH_IF class = 3 BEGIN // cleric
				SPRINT $clerics("%count%") "%label%"
				++count
			END
		END
	BUT_ONLY

	COPY_EXISTING ~WEAPPROF.2DA~ override
		READ_2DA_ENTRIES_NOW weapprof 3
		COUNT_2DA_COLS cols
		PHP_EACH clerics AS _ => name BEGIN
			FOR (col = 0; col < cols - 1; ++col) BEGIN
				READ_2DA_ENTRY_FORMER weapprof 0 col column_name
				PATCH_IF "%column_name%" STRING_EQUAL_CASE "%name%" BEGIN
					SET_2DA_ENTRY_LATER C#weapprof 7 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 8 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 10 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 18 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 19 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 20 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 21 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 23 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 24 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 25 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 26 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 30 (col + 1) 2
					SET_2DA_ENTRY_LATER C#weapprof 31 (col + 1) 1
					SET_2DA_ENTRY_LATER C#weapprof 32 (col + 1) 1
					SET_2DA_ENTRY_LATER C#weapprof 33 (col + 1) 1
					SET_2DA_ENTRY_LATER C#weapprof 34 (col + 1) 0
				END
			END
		END
		SET_2DA_ENTRIES_NOW C#weapprof 1
		PRETTY_PRINT_2DA
	BUT_ONLY
END

LAF mod_cleric_profs END
//__________________________________________________________________________________


//PROFICIENCIES FOR MOD DRUIDS_______________________________________________________
//
DEFINE_ACTION_FUNCTION mod_druid_profs BEGIN
	OUTER_SET count = 0

	ACTION_FOR_EACH class IN
                  druid

	BEGIN
		OUTER_SPRINT $druids("%count%") "%class%"
		OUTER_SET ++count
	END

	COPY_EXISTING kitlist.2da override
		READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 31; row < kitlist; ++row) BEGIN // Skip past the vanilla kits
			READ_2DA_ENTRY_FORMER kitlist row 1 label
			READ_2DA_ENTRY_FORMER kitlist row 8 class
			PATCH_IF class = 11 BEGIN // druid
				SPRINT $druids("%count%") "%label%"
				++count
			END
		END
	BUT_ONLY

	COPY_EXISTING ~WEAPPROF.2DA~ override
		READ_2DA_ENTRIES_NOW weapprof 3
		COUNT_2DA_COLS cols
		PHP_EACH druids AS _ => name BEGIN
			FOR (col = 0; col < cols - 1; ++col) BEGIN
				READ_2DA_ENTRY_FORMER weapprof 0 col column_name
				PATCH_IF "%column_name%" STRING_EQUAL_CASE "%name%" BEGIN
					SET_2DA_ENTRY_LATER D#weapprof 17 (col + 1) 3
					SET_2DA_ENTRY_LATER D#weapprof 18 (col + 1) 3
					SET_2DA_ENTRY_LATER D#weapprof 20 (col + 1) 3
					SET_2DA_ENTRY_LATER D#weapprof 21 (col + 1) 3
					SET_2DA_ENTRY_LATER D#weapprof 25 (col + 1) 3
					SET_2DA_ENTRY_LATER D#weapprof 28 (col + 1) 3
					SET_2DA_ENTRY_LATER D#weapprof 30 (col + 1) 3
					SET_2DA_ENTRY_LATER D#weapprof 31 (col + 1) 2
					SET_2DA_ENTRY_LATER D#weapprof 32 (col + 1) 0
					SET_2DA_ENTRY_LATER D#weapprof 33 (col + 1) 2
					SET_2DA_ENTRY_LATER D#weapprof 34 (col + 1) 2
				END
			END
		END
		SET_2DA_ENTRIES_NOW D#weapprof 1
		PRETTY_PRINT_2DA
	BUT_ONLY
END

LAF mod_druid_profs END
//__________________________________________________________________________________


//PROFICIENCIES FOR MOD THIEVES_____________________________________________________
//
DEFINE_ACTION_FUNCTION mod_thief_profs BEGIN
	OUTER_SET count = 0

	ACTION_FOR_EACH class IN
                  thief

	BEGIN
		OUTER_SPRINT $thiefs("%count%") "%class%"
		OUTER_SET ++count
	END

	COPY_EXISTING kitlist.2da override
		READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 31; row < kitlist; ++row) BEGIN // Skip past the vanilla kits
			READ_2DA_ENTRY_FORMER kitlist row 1 label
			READ_2DA_ENTRY_FORMER kitlist row 8 class
			PATCH_IF class = 4 BEGIN // thief
				SPRINT $thiefs("%count%") "%label%"
				++count
			END
		END
	BUT_ONLY

	COPY_EXISTING ~WEAPPROF.2DA~ override
		READ_2DA_ENTRIES_NOW weapprof 3
		COUNT_2DA_COLS cols
		PHP_EACH thiefs AS _ => name BEGIN
			FOR (col = 0; col < cols - 1; ++col) BEGIN
				READ_2DA_ENTRY_FORMER weapprof 0 col column_name
				PATCH_IF "%column_name%" STRING_EQUAL_CASE "%name%" BEGIN
					SET_2DA_ENTRY_LATER T#weapprof 12 (col + 1) 3
					SET_2DA_ENTRY_LATER T#weapprof 13 (col + 1) 3
					SET_2DA_ENTRY_LATER T#weapprof 17 (col + 1) 3
					SET_2DA_ENTRY_LATER T#weapprof 18 (col + 1) 3
					SET_2DA_ENTRY_LATER T#weapprof 20 (col + 1) 3
					SET_2DA_ENTRY_LATER T#weapprof 25 (col + 1) 3
					SET_2DA_ENTRY_LATER T#weapprof 26 (col + 1) 3
					SET_2DA_ENTRY_LATER T#weapprof 28 (col + 1) 3
					SET_2DA_ENTRY_LATER T#weapprof 30 (col + 1) 3
					SET_2DA_ENTRY_LATER T#weapprof 31 (col + 1) 0
					SET_2DA_ENTRY_LATER T#weapprof 32 (col + 1) 0
					SET_2DA_ENTRY_LATER T#weapprof 33 (col + 1) 2
					SET_2DA_ENTRY_LATER T#weapprof 34 (col + 1) 3
				END
			END
		END
		SET_2DA_ENTRIES_NOW T#weapprof 1
		PRETTY_PRINT_2DA
	BUT_ONLY
END

LAF mod_thief_profs END
//__________________________________________________________________________________


//PROFICIENCIES FOR MOD BARDS_______________________________________________________
//
DEFINE_ACTION_FUNCTION mod_bard_profs BEGIN
	OUTER_SET count = 0

	ACTION_FOR_EACH class IN
                  bard

	BEGIN
		OUTER_SPRINT $bards("%count%") "%class%"
		OUTER_SET ++count
	END

	COPY_EXISTING kitlist.2da override
		READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 31; row < kitlist; ++row) BEGIN // Skip past the vanilla kits
			READ_2DA_ENTRY_FORMER kitlist row 1 label
			READ_2DA_ENTRY_FORMER kitlist row 8 class
			PATCH_IF class = 5 BEGIN // bard
				SPRINT $bards("%count%") "%label%"
				++count
			END
		END
	BUT_ONLY

	COPY_EXISTING ~WEAPPROF.2DA~ override
		READ_2DA_ENTRIES_NOW weapprof 3
		COUNT_2DA_COLS cols
		PHP_EACH bards AS _ => name BEGIN
			FOR (col = 0; col < cols - 1; ++col) BEGIN
				READ_2DA_ENTRY_FORMER weapprof 0 col column_name
				PATCH_IF "%column_name%" STRING_EQUAL_CASE "%name%" BEGIN
					SET_2DA_ENTRY_LATER B#weapprof 12 (col + 1) 3
					SET_2DA_ENTRY_LATER B#weapprof 13 (col + 1) 3
					SET_2DA_ENTRY_LATER B#weapprof 14 (col + 1) 3
					SET_2DA_ENTRY_LATER B#weapprof 15 (col + 1) 0
					SET_2DA_ENTRY_LATER B#weapprof 17 (col + 1) 3
					SET_2DA_ENTRY_LATER B#weapprof 18 (col + 1) 3
					SET_2DA_ENTRY_LATER B#weapprof 19 (col + 1) 3
					SET_2DA_ENTRY_LATER B#weapprof 20 (col + 1) 3
					SET_2DA_ENTRY_LATER B#weapprof 21 (col + 1) 0
					SET_2DA_ENTRY_LATER B#weapprof 23 (col + 1) 3
					SET_2DA_ENTRY_LATER B#weapprof 24 (col + 1) 3
					SET_2DA_ENTRY_LATER B#weapprof 25 (col + 1) 0
					SET_2DA_ENTRY_LATER B#weapprof 26 (col + 1) 3
					SET_2DA_ENTRY_LATER B#weapprof 28 (col + 1) 3
					SET_2DA_ENTRY_LATER B#weapprof 30 (col + 1) 3
					SET_2DA_ENTRY_LATER B#weapprof 31 (col + 1) 1
					SET_2DA_ENTRY_LATER B#weapprof 32 (col + 1) 1
					SET_2DA_ENTRY_LATER B#weapprof 33 (col + 1) 1
					SET_2DA_ENTRY_LATER B#weapprof 34 (col + 1) 2
				END
			END
		END
		SET_2DA_ENTRIES_NOW B#weapprof 1
		PRETTY_PRINT_2DA
	BUT_ONLY
END

LAF mod_bard_profs END
//__________________________________________________________________________________


//PROFICIENCIES FOR MOD RANGERS_____________________________________________________
//
DEFINE_ACTION_FUNCTION mod_ranger_profs BEGIN
	OUTER_SET count = 0

	ACTION_FOR_EACH class IN
                  ranger

	BEGIN
		OUTER_SPRINT $rangers("%count%") "%class%"
		OUTER_SET ++count
	END

	COPY_EXISTING kitlist.2da override
		READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 31; row < kitlist; ++row) BEGIN // Skip past the vanilla kits
			READ_2DA_ENTRY_FORMER kitlist row 1 label
			READ_2DA_ENTRY_FORMER kitlist row 8 class
			PATCH_IF class = 12 BEGIN // ranger
				SPRINT $rangers("%count%") "%label%"
				++count
			END
		END
	BUT_ONLY

	COPY_EXISTING ~WEAPPROF.2DA~ override
		READ_2DA_ENTRIES_NOW weapprof 3
		COUNT_2DA_COLS cols
		PHP_EACH rangers AS _ => name BEGIN
			FOR (col = 0; col < cols - 1; ++col) BEGIN
				READ_2DA_ENTRY_FORMER weapprof 0 col column_name
				PATCH_IF "%column_name%" STRING_EQUAL_CASE "%name%" BEGIN
					SET_2DA_ENTRY_LATER R#weapprof 12 (col + 1) 4
					SET_2DA_ENTRY_LATER R#weapprof 13 (col + 1) 4
					SET_2DA_ENTRY_LATER R#weapprof 14 (col + 1) 4
					SET_2DA_ENTRY_LATER R#weapprof 17 (col + 1) 4
					SET_2DA_ENTRY_LATER R#weapprof 18 (col + 1) 4
					SET_2DA_ENTRY_LATER R#weapprof 21 (col + 1) 4
					SET_2DA_ENTRY_LATER R#weapprof 25 (col + 1) 4
					SET_2DA_ENTRY_LATER R#weapprof 28 (col + 1) 4
					SET_2DA_ENTRY_LATER R#weapprof 31 (col + 1) 2
					SET_2DA_ENTRY_LATER R#weapprof 32 (col + 1) 0
					SET_2DA_ENTRY_LATER R#weapprof 33 (col + 1) 2
					SET_2DA_ENTRY_LATER R#weapprof 34 (col + 1) 3
				END
			END
		END
		SET_2DA_ENTRIES_NOW R#weapprof 1
		PRETTY_PRINT_2DA
	BUT_ONLY
END

LAF mod_ranger_profs END
//__________________________________________________________________________________


//PROFICIENCIES FOR MOD PALADINS____________________________________________________
//
DEFINE_ACTION_FUNCTION mod_paladin_profs BEGIN
	OUTER_SET count = 0

	ACTION_FOR_EACH class IN
                  paladin

	BEGIN
		OUTER_SPRINT $paladins("%count%") "%class%"
		OUTER_SET ++count
	END

	COPY_EXISTING kitlist.2da override
		READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 31; row < kitlist; ++row) BEGIN // Skip past the vanilla kits
			READ_2DA_ENTRY_FORMER kitlist row 1 label
			READ_2DA_ENTRY_FORMER kitlist row 8 class
			PATCH_IF class = 6 BEGIN // paladin
				SPRINT $paladins("%count%") "%label%"
				++count
			END
		END
	BUT_ONLY

	COPY_EXISTING ~WEAPPROF.2DA~ override
		READ_2DA_ENTRIES_NOW weapprof 3
		COUNT_2DA_COLS cols
		PHP_EACH paladins AS _ => name BEGIN
			FOR (col = 0; col < cols - 1; ++col) BEGIN
				READ_2DA_ENTRY_FORMER weapprof 0 col column_name
				PATCH_IF "%column_name%" STRING_EQUAL_CASE "%name%" BEGIN
					SET_2DA_ENTRY_LATER P#weapprof 31 (col + 1) 1
					SET_2DA_ENTRY_LATER P#weapprof 32 (col + 1) 1
					SET_2DA_ENTRY_LATER P#weapprof 33 (col + 1) 1
					SET_2DA_ENTRY_LATER P#weapprof 34 (col + 1) 2
				END
			END
		END
		SET_2DA_ENTRIES_NOW P#weapprof 1
		PRETTY_PRINT_2DA
	BUT_ONLY
END

LAF mod_paladin_profs END
//__________________________________________________________________________________


//PROFICIENCIES FOR MOD FIGHTERS____________________________________________________
//
DEFINE_ACTION_FUNCTION mod_fighter_profs BEGIN
	OUTER_SET count = 0

	ACTION_FOR_EACH class IN
                  fighter

	BEGIN
		OUTER_SPRINT $fighters("%count%") "%class%"
		OUTER_SET ++count
	END

	COPY_EXISTING kitlist.2da override
		READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 31; row < kitlist; ++row) BEGIN // Skip past the vanilla kits
			READ_2DA_ENTRY_FORMER kitlist row 1 label
			READ_2DA_ENTRY_FORMER kitlist row 8 class
			PATCH_IF class = 2 BEGIN // fighter
				SPRINT $fighters("%count%") "%label%"
				++count
			END
		END
	BUT_ONLY

	COPY_EXISTING ~WEAPPROF.2DA~ override
		READ_2DA_ENTRIES_NOW weapprof 3
		COUNT_2DA_COLS cols
		PHP_EACH fighters AS _ => name BEGIN
			FOR (col = 0; col < cols - 1; ++col) BEGIN
				READ_2DA_ENTRY_FORMER weapprof 0 col column_name
				PATCH_IF "%column_name%" STRING_EQUAL_CASE "%name%" BEGIN
					SET_2DA_ENTRY_LATER F#weapprof 31 (col + 1) 2
					SET_2DA_ENTRY_LATER F#weapprof 32 (col + 1) 2
					SET_2DA_ENTRY_LATER F#weapprof 33 (col + 1) 2
					SET_2DA_ENTRY_LATER F#weapprof 34 (col + 1) 3
				END
			END
		END
		SET_2DA_ENTRIES_NOW F#weapprof 1
		PRETTY_PRINT_2DA
	BUT_ONLY
END

LAF mod_fighter_profs END
//__________________________________________________________________________________


//MIGHT & GUILE KITS________________________________________________________________
//
COPY_EXISTING ~weapprof.2da~ ~override~
	COUNT_2DA_COLS num_cols
	READ_2DA_ENTRIES_NOW ~r2en_mng~ (num_cols - 1)
	FOR (col = 3; col < (num_cols - 1); col += 1) BEGIN
		READ_2DA_ENTRY_FORMER ~r2en_mng~ 0 col kitname
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~D5CORSA~) BEGIN
			SET_2DA_ENTRY_LATER ~s2el_mng~ 12 (col + 1) 5
			SET_2DA_ENTRY_LATER ~s2el_mng~ 13 (col + 1) 5
			SET_2DA_ENTRY_LATER ~s2el_mng~ 17 (col + 1) 5
			SET_2DA_ENTRY_LATER ~s2el_mng~ 18 (col + 1) 5
			SET_2DA_ENTRY_LATER ~s2el_mng~ 14 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 19 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 20 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 25 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 15 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 21 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 23 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 24 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 26 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 28 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 30 (col + 1) 2
		END
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~D5MARKS~) BEGIN
			SET_2DA_ENTRY_LATER ~s2el_mng~ 12 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 13 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 14 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 15 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 17 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 18 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 19 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 20 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 21 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 23 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 24 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 25 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 26 (col + 1) 5
			SET_2DA_ENTRY_LATER ~s2el_mng~ 28 (col + 1) 5
			SET_2DA_ENTRY_LATER ~s2el_mng~ 30 (col + 1) 1
		END
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~D5EARCH~) BEGIN
			SET_2DA_ENTRY_LATER ~s2el_mng~ 12 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 13 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 14 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 15 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 17 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 18 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 19 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 20 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 21 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 23 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 24 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 25 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 26 (col + 1) 1
			SET_2DA_ENTRY_LATER ~s2el_mng~ 28 (col + 1) 5
			SET_2DA_ENTRY_LATER ~s2el_mng~ 30 (col + 1) 1
		END
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~D5SLING~) BEGIN
			SET_2DA_ENTRY_LATER ~s2el_mng~ 12 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 13 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 14 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 15 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 17 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 18 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 19 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 20 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 21 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 23 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 24 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 25 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 26 (col + 1) 1
			SET_2DA_ENTRY_LATER ~s2el_mng~ 28 (col + 1) 1
			SET_2DA_ENTRY_LATER ~s2el_mng~ 30 (col + 1) 5
		END
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~D5SNIPE~) BEGIN
			SET_2DA_ENTRY_LATER ~s2el_mng~ 12 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 13 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 17 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 18 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 20 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 25 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 26 (col + 1) 4
			SET_2DA_ENTRY_LATER ~s2el_mng~ 28 (col + 1) 4
			SET_2DA_ENTRY_LATER ~s2el_mng~ 30 (col + 1) 4
		END
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~D5SWASH~) BEGIN
			SET_2DA_ENTRY_LATER ~s2el_mng~ 12 (col + 1) 4
			SET_2DA_ENTRY_LATER ~s2el_mng~ 13 (col + 1) 4
			SET_2DA_ENTRY_LATER ~s2el_mng~ 17 (col + 1) 4
			SET_2DA_ENTRY_LATER ~s2el_mng~ 18 (col + 1) 4
			SET_2DA_ENTRY_LATER ~s2el_mng~ 14 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 19 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 20 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 23 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 24 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 25 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 15 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 21 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 26 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 28 (col + 1) 3
			SET_2DA_ENTRY_LATER ~s2el_mng~ 30 (col + 1) 3
		END
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~D5JONGL~) BEGIN
			SET_2DA_ENTRY_LATER ~s2el_mng~ 12 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 13 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 14 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 15 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 17 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 18 (col + 1) 5
			SET_2DA_ENTRY_LATER ~s2el_mng~ 19 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 20 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 21 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 23 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 24 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 25 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 26 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 28 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 30 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 31 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 32 (col + 1) 0
			SET_2DA_ENTRY_LATER ~s2el_mng~ 33 (col + 1) 2
			SET_2DA_ENTRY_LATER ~s2el_mng~ 34 (col + 1) 3
		END
	END
	SET_2DA_ENTRIES_NOW ~s2el_mng~ 1
BUT_ONLY
//__________________________________________________________________________________


//COPY PROFICIENCY FILES____________________________________________________________
//
COPY ~scales_of_balance/profs/d5_caxe1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_caxe2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_caxe3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cdag1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cdag2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cdag3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cbow1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cbow2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cbow3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_clsw1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_clsw2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_clsw3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cssw1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cssw2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cssw3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_c2sw1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_c2sw2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_c2sw3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_csci1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_csci2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_csci3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cspe1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cspe2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cspe3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_csli1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_csli2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_csli3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cclu1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cclu2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cclu3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cfla1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cfla2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cfla3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cmac1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cmac2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cmac3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cham1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cham2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_cham3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_csta1.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_csta2.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_csta3.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_pano.itm~ ~override~
	SAY NAME2 @1254
	SAY DESC @1255
COPY ~scales_of_balance/profs/d5_pimo.itm~ ~override~
	SAY NAME2 @1256
	SAY DESC @1257
COPY ~scales_of_balance/profs/d5_pnal.itm~ ~override~
	SAY NAME2 @1258
	SAY DESC @1259
COPY ~scales_of_balance/profs/d5_pano.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_pimo.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/d5_pnal.spl~ ~override~
	SAY NAME1 @1248
COPY ~scales_of_balance/profs/thac0.2da~ ~override~
ACTION_IF GAME_IS ~iwdee tob bgt~ BEGIN
	COPY ~scales_of_balance/profs/profsmax_i.2da~ ~override/profsmax.2da~
END
ACTION_IF GAME_IS ~bgee bg2ee~ BEGIN
	COPY ~scales_of_balance/profs/profsmax.2da~ ~override~
END
COPY ~scales_of_balance/profs/profs.2da~ ~override~
COPY ~scales_of_balance/misc/d5_numat.spl~ ~override~
//__________________________________________________________________________________


//AMEND CLAB FILES___________________________________________________________________
//
COPY_EXISTING ~clabfi01.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabfi02.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabfi03.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabfi04.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabfi05.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
ACTION_IF FILE_EXISTS_IN_GAME ~clabfi06.2da~ THEN BEGIN
	COPY_EXISTING ~clabfi06.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
		REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
		BUT_ONLY
	END
COPY_EXISTING ~clabpa01.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabpa02.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabpa03.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabpa04.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabpa05.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
ACTION_IF FILE_EXISTS_IN_GAME ~clabpa06.2da~ THEN BEGIN
	COPY_EXISTING ~clabpa06.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
		REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
		BUT_ONLY
	END
COPY_EXISTING ~clabrn01.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabrn02.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabrn03.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabrn04.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY
COPY_EXISTING ~clabrn05.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_TB#TATT~ ~****      ~
	REPLACE_TEXTUALLY ~AP_d5_NUMAT~ ~****       ~
	BUT_ONLY

COPY_EXISTING ~clabpr02.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~scales_of_balance/profs/pcspea.txt~
	BUT_ONLY
COPY_EXISTING ~clabpr03.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~scales_of_balance/profs/pc2swo.txt~
	BUT_ONLY
COPY_EXISTING ~clabpr04.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~scales_of_balance/profs/pcmace.txt~
	BUT_ONLY
ACTION_IF FILE_EXISTS_IN_GAME ~ohtyr.2da~ THEN BEGIN
	COPY_EXISTING ~ohtyr.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pclswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~ohtempus.2da~ THEN BEGIN
	COPY_EXISTING ~ohtempus.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcaxe.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#cyric.2da~ THEN BEGIN
	COPY_EXISTING ~a#cyric.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcsswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#feyw.2da~ THEN BEGIN
	COPY_EXISTING ~a#feyw.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pclswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#koss.2da~ THEN BEGIN
	COPY_EXISTING ~a#koss.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcflai.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#ogma.2da~ THEN BEGIN
	COPY_EXISTING ~a#ogma.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pclswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#red.2da~ THEN BEGIN
	COPY_EXISTING ~a#red.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pclswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#shar.2da~ THEN BEGIN
	COPY_EXISTING ~a#shar.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcdagg.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#temp.2da~ THEN BEGIN
	COPY_EXISTING ~a#temp.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcaxe.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~cdilmatr.2da~ THEN BEGIN
	COPY_EXISTING ~cdilmatr.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcflai.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~cdselune.2da~ THEN BEGIN
	COPY_EXISTING ~cdselune.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcmace.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~cdxvim.2da~ THEN BEGIN
	COPY_EXISTING ~cdxvim.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcscim.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabeart.2da~ THEN BEGIN
	COPY_EXISTING ~clabeart.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pchamm.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabgruu.2da~ THEN BEGIN
	COPY_EXISTING ~clabgruu.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcaxe.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabluth.2da~ THEN BEGIN
	COPY_EXISTING ~clabluth.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcsswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabauri.2da~ THEN BEGIN
	COPY_EXISTING ~clabauri.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcdagg.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabiceg.2da~ THEN BEGIN
	COPY_EXISTING ~clabiceg.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcspea.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clableaf.2da~ THEN BEGIN
	COPY_EXISTING ~clableaf.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcclub.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5_tymor.2da~ THEN BEGIN
	COPY_EXISTING ~d5_tymor.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcslin.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5_cllei.2da~ THEN BEGIN
	COPY_EXISTING ~d5_cllei.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcdagg.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~b_cllov.2da~ THEN BEGIN
	COPY_EXISTING ~b_cllov.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcflai.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~b_acilm.2da~ THEN BEGIN
	COPY_EXISTING ~b_acilm.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcstaf.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5_acmas.2da~ THEN BEGIN
	COPY_EXISTING ~d5_acmas.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcsswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5_acsha.2da~ THEN BEGIN
	COPY_EXISTING ~d5_acsha.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcdagg.txt~
		BUT_ONLY
END
//__________________________________________________________________________________


//UNIVERSAL CLUBS___________________________________________________________________
//
DEFINE_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
  INT_VAR
    offset = 0
  STR_VAR
    desc = ~~
    unusable_regexp = ~~
    unusable_replacement = ~~
    class_regexp = ~~ //
    class_prefix = ~~ //
BEGIN
  INNER_PATCH_SAVE desc ~%desc%~ BEGIN
    REPLACE_TEXTUALLY ~%unusable_regexp%~ ~%unusable_replacement%~
  END
  PATCH_IF ((~%desc%~ STRING_CONTAINS_REGEXP ~^%unusable_replacement%~) == 0) BEGIN
    INNER_PATCH_SAVE usab_block ~%desc%~ BEGIN
      REPLACE_TEXTUALLY ~\(.*[%LNL%%MNL%%WNL%]\)*%unusable_replacement%~ ~~
    END
    INNER_PATCH_SAVE usab_block_new ~%usab_block%~ BEGIN
      REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%][- %TAB%]*$~ ~~
      REPLACE_TEXTUALLY ~^[- %TAB%]*~ ~%class_prefix%~
      REPLACE_TEXTUALLY ~%mage_regexp%~ ~~
    END
    INNER_PATCH_SAVE desc ~%desc%~ BEGIN
      REPLACE_TEXTUALLY EXACT_MATCH ~%usab_block%~ ~%usab_block_new%~
    END
    INNER_PATCH_SAVE compare ~%desc%~ BEGIN 
      REPLACE_TEXTUALLY ~^%unusable_replacement%.*[%LNL%%MNL%%WNL%]%class_prefix%[^- %TAB%]~ ~~
    END
    PATCH_IF (~%desc%~ STRING_EQUAL ~%compare%~) BEGIN
      INNER_PATCH_SAVE desc ~%desc%~ BEGIN
        REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]%unusable_replacement%.*~ ~~
      END
    END
    SAY_EVALUATED ~%offset%~ ~%desc%~
  END
END

COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
    READ_BYTE 0x31 "prof" ELSE 0
    PATCH_IF ("%prof%" = 115) BEGIN
      READ_BYTE 0x1f "fighter"
      PATCH_IF (("%fighter%" BAND "0b00001000") = "0b00000000") BEGIN
        READ_BYTE   0x20 "mage"
        WRITE_BYTE 0x20 ("%mage%" BAND "0b11111011")
        PATCH_FOR_EACH offset IN
          ~0x50~
          ~0x54~
        BEGIN
          READ_LONG ~%offset%~ desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF ~%offset%~ desc
           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
           	  STR_VAR
           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
           	    unusable_replacement = ~Not Usable By:~
           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bMage.*~
           	    class_prefix = ~ ~
           	END
          END
        END
      END
    END
  END
  BUT_ONLY_IF_IT_CHANGES
//__________________________________________________________________________________

//UNIVERSAL CROSSBOWS________________________________________________________________
//
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
    READ_BYTE 0x31 "prof" ELSE 0
    PATCH_IF ("%prof%" = 103) BEGIN
      READ_BYTE 0x1f "fighter"
      PATCH_IF (("%fighter%" BAND "0b00001000") = "0b00000000") BEGIN
        READ_BYTE   0x20 "mage"
        WRITE_BYTE 0x20 ("%mage%" BAND "0b11111011")
        PATCH_FOR_EACH offset IN
          ~0x50~
          ~0x54~
        BEGIN
          READ_LONG ~%offset%~ desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF ~%offset%~ desc
           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
           	  STR_VAR
           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
           	    unusable_replacement = ~Not Usable By:~
           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bMage.*~
           	    class_prefix = ~ ~
           	END
          END
        END
      END
    END
    READ_SHORT ~0x1c~ ~type~
    PATCH_IF (~%type%~ = ~31~) BEGIN
      READ_BYTE 0x1f "fighter"
      PATCH_IF (("%fighter%" BAND "0b00001000") = "0b00000000") BEGIN
        READ_BYTE   0x20 "mage"
        WRITE_BYTE 0x20 ("%mage%" BAND "0b11111011")
        PATCH_FOR_EACH offset IN
          ~0x50~
          ~0x54~
        BEGIN
          READ_LONG ~%offset%~ desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF ~%offset%~ desc
           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
           	  STR_VAR
           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
           	    unusable_replacement = ~Not Usable By:~
           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bMage.*~
           	    class_prefix = ~ ~
           	END
          END
        END
      END
    END
  END
  BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
    READ_BYTE 0x31 "prof" ELSE 0
    PATCH_IF ("%prof%" = 103) BEGIN
      READ_BYTE 0x1f "fighter"
      PATCH_IF (("%fighter%" BAND "0b00001000") = "0b00000000") BEGIN
        READ_BYTE   0x1E "cleric"
        WRITE_BYTE 0x1E ("%cleric%" BAND "0b01111111")
        READ_BYTE   0x1F "cleric-mage"
        WRITE_BYTE 0x1F ("%cleric-mage%" BAND "0b00111000")
        PATCH_FOR_EACH offset IN
          ~0x50~
          ~0x54~
        BEGIN
          READ_LONG ~%offset%~ desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF ~%offset%~ desc
           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
           	  STR_VAR
           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
           	    unusable_replacement = ~Not Usable By:~
           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
           	    class_prefix = ~ ~
           	END
          END
        END
      END
    END
    READ_SHORT ~0x1c~ ~type~
    PATCH_IF (~%type%~ = ~31~) BEGIN
      READ_BYTE 0x1f "fighter"
      PATCH_IF (("%fighter%" BAND "0b00001000") = "0b00000000") BEGIN
        READ_BYTE   0x1E "cleric"
        WRITE_BYTE 0x1E ("%cleric%" BAND "0b01111111")
        READ_BYTE   0x1F "cleric-mage"
        WRITE_BYTE 0x1F ("%cleric-mage%" BAND "0b00111000")
        PATCH_FOR_EACH offset IN
          ~0x50~
          ~0x54~
        BEGIN
          READ_LONG ~%offset%~ desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF ~%offset%~ desc
           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
           	  STR_VAR
           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
           	    unusable_replacement = ~Not Usable By:~
           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
           	    class_prefix = ~ ~
           	END
          END
        END
      END
    END
  END
  BUT_ONLY_IF_IT_CHANGES
//__________________________________________________________________________________


//CLERIC WEAPON USABILITY___________________________________________________________
//
//ACTION_IF NOT MOD_IS_INSTALLED "faiths_and_powers.tp2" "___"

COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1e cleric 
		READ_BYTE  0x1f mcler 
		READ_SHORT  ~0x1c~ type 
		PATCH_IF (type = 15 || type = 5 || type = 31 || type = 29 || type = 25 || type = 19 || type = 20 || type = 16) BEGIN // bows, spears, axes, small swords, large swords, daggers
			WRITE_BYTE 0x1e (cleric BAND 0b01111111)
			WRITE_BYTE 0x1f (mcler BAND 0b00111000)
  	      PATCH_FOR_EACH offset IN
  	        ~0x50~
  	        ~0x54~
  	      BEGIN
  	        READ_LONG ~%offset%~ desc_strref
  	        PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
  	          READ_STRREF ~%offset%~ desc
  	         	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
  	         	  STR_VAR
  	         	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
  	         	    unusable_replacement = ~Not Usable By:~
  	         	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
  	         	    class_prefix = ~ ~
  	         	END	
	          END
  	        END
		END
	END
BUT_ONLY
/*
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1e cleric 
		READ_BYTE  0x1f mcler 
		PATCH_IF (type = 29) BEGIN // spears
			WRITE_BYTE 0x1e (cleric BAND 0b01111111)
			WRITE_BYTE 0x1f (mcler BAND 0b00111000)
	        PATCH_FOR_EACH offset IN
	          ~0x50~
	          ~0x54~
	        BEGIN
	          READ_LONG ~%offset%~ desc_strref
	          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
	            READ_STRREF ~%offset%~ desc
	           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
	           	  STR_VAR
	           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
	           	    unusable_replacement = ~Not Usable By:~
	           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
	           	    class_prefix = ~ ~
	           	END
	          END
	        END
		END
	END
BUT_ONLY
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1e cleric 
		READ_BYTE  0x1f mcler 
		PATCH_IF (type = 25) BEGIN // axes
			WRITE_BYTE 0x1e (cleric BAND 0b01111111)
			WRITE_BYTE 0x1f (mcler BAND 0b00111000)
	        PATCH_FOR_EACH offset IN
	          ~0x50~
	          ~0x54~
	        BEGIN
	          READ_LONG ~%offset%~ desc_strref
	          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
	            READ_STRREF ~%offset%~ desc
	           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
	           	  STR_VAR
	           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
	           	    unusable_replacement = ~Not Usable By:~
	           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
	           	    class_prefix = ~ ~
	           	END
	          END
	        END
		END
	END
BUT_ONLY
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1e cleric 
		READ_BYTE  0x1f mcler 
		PATCH_IF (type = 19) BEGIN // small swords
			WRITE_BYTE 0x1e (cleric BAND 0b01111111)
			WRITE_BYTE 0x1f (mcler BAND 0b00111000)
	        PATCH_FOR_EACH offset IN
	          ~0x50~
	          ~0x54~
	        BEGIN
	          READ_LONG ~%offset%~ desc_strref
	          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
	            READ_STRREF ~%offset%~ desc
	           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
	           	  STR_VAR
	           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
	           	    unusable_replacement = ~Not Usable By:~
	           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
	           	    class_prefix = ~ ~
	           	END
	          END
	        END
		END
	END
BUT_ONLY
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1e cleric 
		READ_BYTE  0x1f mcler 
		PATCH_IF (type = 20) BEGIN // large swords
			WRITE_BYTE 0x1e (cleric BAND 0b01111111)
			WRITE_BYTE 0x1f (mcler BAND 0b00111000)
	        PATCH_FOR_EACH offset IN
	          ~0x50~
	          ~0x54~
	        BEGIN
	          READ_LONG ~%offset%~ desc_strref
	          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
	            READ_STRREF ~%offset%~ desc
	           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
	           	  STR_VAR
	           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
	           	    unusable_replacement = ~Not Usable By:~
	           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
	           	    class_prefix = ~ ~
	           	END
	          END
	        END
		END
	END
BUT_ONLY
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1e cleric 
		READ_BYTE  0x1f mcler 
		PATCH_IF (type = 16) BEGIN // daggers
			WRITE_BYTE 0x1e (cleric BAND 0b01111111)
			WRITE_BYTE 0x1f (mcler BAND 0b00111000)
	        PATCH_FOR_EACH offset IN
	          ~0x50~
	          ~0x54~
	        BEGIN
	          READ_LONG ~%offset%~ desc_strref
	          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
	            READ_STRREF ~%offset%~ desc
	           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
	           	  STR_VAR
	           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
	           	    unusable_replacement = ~Not Usable By:~
	           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
	           	    class_prefix = ~ ~
	           	END
	          END
	        END
		END
	END
BUT_ONLY
*/
//END
//__________________________________________________________________________________


//DELETE NPCS' PROFICIENCIES________________________________________________________
//
ACTION_IF GAME_IS ~bgee tutu bgt eet~ THEN BEGIN
	COPY_EXISTING ~%tutu_var%ajanti.cre~ ~override~
				~%tutu_var%ajanti4.cre~ ~override~
				~%tutu_var%ajanti6.cre~ ~override~
				~%tutu_var%alora.cre~ ~override~
				~%tutu_var%alora6.cre~ ~override~
				~%tutu_var%imoen1.cre~ ~override~
				~%tutu_var%imoen2.cre~ ~override~
				~%tutu_var%imoen4.cre~ ~override~
				~%tutu_var%%imoen6_var%.cre~ ~override~
				~%tutu_var%safana.cre~ ~override~
				~%tutu_var%safana4.cre~ ~override~
				~%tutu_var%safana6.cre~ ~override~
				~%tutu_var%coran.cre~ ~override~
				~%tutu_var%coran5.cre~ ~override~
				~%tutu_var%skie.cre~ ~override~
				~%tutu_var%skie6.cre~ ~override~
				~%tutu_var%montar.cre~ ~override~
				~%tutu_var%montar2.cre~ ~override~
				~%tutu_var%montar4.cre~ ~override~
				~%tutu_var%montar6.cre~ ~override~
				~%tutu_var%garric.cre~ ~override~
				~%tutu_var%garric2.cre~ ~override~
				~%tutu_var%garric4.cre~ ~override~
				~%tutu_var%garric6.cre~ ~override~
				~%tutu_var%eldoth.cre~ ~override~
				~%tutu_var%eldoth5.cre~ ~override~
				~%tutu_var%dynahe.cre~ ~override~
				~%tutu_var%dynahe2.cre~ ~override~
				~%tutu_var%dynahe4.cre~ ~override~
				~%tutu_var%dynahe6.cre~ ~override~
				~%tutu_var%edwin.cre~ ~override~
				~%tutu_var%edwin2.cre~ ~override~
				~%tutu_var%edwin4.cre~ ~override~
				~%tutu_var%edwin6.cre~ ~override~
				~%tutu_var%%xan_var%.cre~ ~override~
				~%tutu_var%xan4.cre~ ~override~
				~%tutu_var%xan6.cre~ ~override~
				~%tutu_var%%xzar_var%.cre~ ~override~
				~%tutu_var%xzar2.cre~ ~override~
				~%tutu_var%xzar4.cre~ ~override~
				~%tutu_var%xzar6.cre~ ~override~
				~%tutu_var%jaheir.cre~ ~override~
				~%tutu_var%jaheir2.cre~ ~override~
				~%tutu_var%jaheir4.cre~ ~override~
				~%tutu_var%jaheir6.cre~ ~override~
				~%tutu_var%faldor.cre~ ~override~
				~%tutu_var%faldor5.cre~ ~override~
				~%tutu_var%yeslic.cre~ ~override~
				~%tutu_var%yeslic5.cre~ ~override~
				~%tutu_var%branwe.cre~ ~override~
				~%tutu_var%branwe5.cre~ ~override~
				~%tutu_var%%quayle_var%.cre~ ~override~
				~%tutu_var%quayle4.cre~ ~override~
				~%tutu_var%quayle6.cre~ ~override~
				~%tutu_var%viconi.cre~ ~override~
				~%tutu_var%viconi4.cre~ ~override~
				~%tutu_var%%viconi6_var%.cre~ ~override~
				~%tutu_var%tiax.cre~ ~override~
				~%tutu_var%tiax4.cre~ ~override~
				~%tutu_var%tiax6.cre~ ~override~
				~%tutu_var%minsc.cre~ ~override~
				~%tutu_var%minsc2.cre~ ~override~
				~%tutu_var%minsc4.cre~ ~override~
				~%tutu_var%minsc6.cre~ ~override~
				~%tutu_var%kivan.cre~ ~override~
				~%tutu_var%kivan4.cre~ ~override~
				~%tutu_var%kivan6.cre~ ~override~
				~%tutu_var%khalid.cre~ ~override~
				~%tutu_var%khalid2.cre~ ~override~
				~%tutu_var%khalid4.cre~ ~override~
				~%tutu_var%khalid6.cre~ ~override~
				~%tutu_var%kagain.cre~ ~override~
				~%tutu_var%kagain2.cre~ ~override~
				~%tutu_var%kagain4.cre~ ~override~
				~%tutu_var%kagain6.cre~ ~override~
				~%tutu_var%sharte.cre~ ~override~
				~%tutu_var%sharte4.cre~ ~override~
				~%tutu_var%sharte6.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
		BUT_ONLY
END

/*
ACTION_IF FILE_EXISTS_IN_GAME ~xan.cre~ THEN BEGIN
	COPY_EXISTING ~xan.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
		BUT_ONLY
END
ACTION_IF GAME_IS ~bgt~ THEN BEGIN
	COPY_EXISTING ~viconi61.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
		BUT_ONLY
END
*/

ACTION_IF GAME_IS ~bgee eet~ THEN BEGIN
	COPY_EXISTING ~dorn.cre~ ~override~
				~dorn2.cre~ ~override~
				~dorn4.cre~ ~override~
				~dorn6.cre~ ~override~
				~baeloth.cre~ ~override~
				~neera.cre~ ~override~
				~neera2.cre~ ~override~
				~neera4.cre~ ~override~
				~neera6.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
		BUT_ONLY
END

ACTION_IF GAME_IS ~tob bgt bg2ee eet~ THEN BEGIN
	COPY_EXISTING ~keldor8.cre~ ~override~
				~keldor9.cre~ ~override~
				~keldor10.cre~ ~override~
				~keldor12.cre~ ~override~
				~keldor14.cre~ ~override~
				~yoshi7.cre~ ~override~
				~yoshi8.cre~ ~override~
				~yoshi10.cre~ ~override~
				~yoshi11.cre~ ~override~
				~yoshi12.cre~ ~override~
				~jan8.cre~ ~override~
				~jan10.cre~ ~override~
				~jan11.cre~ ~override~
				~jan12.cre~ ~override~
				~jan15.cre~ ~override~
				~haer10.cre~ ~override~
				~haer11.cre~ ~override~
				~haer13.cre~ ~override~
				~haer15.cre~ ~override~
				~haer19.cre~ ~override~
				~edwin7.cre~ ~override~
				~edwin9.cre~ ~override~
				~edwin11.cre~ ~override~
				~edwin12.cre~ ~override~
				~edwin13.cre~ ~override~
				~edwin15.cre~ ~override~
				~aerie6.cre~ ~override~
				~aerie7.cre~ ~override~
				~aerie9.cre~ ~override~
				~aerie10.cre~ ~override~
				~aerie11.cre~ ~override~
				~aerie12.cre~ ~override~
				~viconi6.cre~ ~override~
				~viconi8.cre~ ~override~
				~viconi9.cre~ ~override~
				~viconi11.cre~ ~override~
				~viconi13.cre~ ~override~
				~viconi16.cre~ ~override~
				~jaheir7.cre~ ~override~
				~jaheir8.cre~ ~override~
				~jaheir11.cre~ ~override~
				~jaheir12.cre~ ~override~
				~jahei12b.cre~ ~override~
				~jahei14.cre~ ~override~
				~cernd10.cre~ ~override~
				~cernd12.cre~ ~override~
				~cernd13.cre~ ~override~
				~cernd13b.cre~ ~override~
				~cernd14.cre~ ~override~
				~minsc7.cre~ ~override~
				~minsc8.cre~ ~override~
				~minsc9.cre~ ~override~
				~minsc10.cre~ ~override~
				~minsc12.cre~ ~override~
				~minsc14.cre~ ~override~
				~valyg8.cre~ ~override~
				~valyg9.cre~ ~override~
				~valyg11.cre~ ~override~
				~valyg12.cre~ ~override~
				~valyg14.cre~ ~override~
				~korgan8.cre~ ~override~
				~korgan9.cre~ ~override~
				~korgan11.cre~ ~override~
				~korgan12.cre~ ~override~
				~korgan15.cre~ ~override~
				~sarevok.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
		BUT_ONLY
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN
	COPY_EXISTING ~dorn8.cre~ ~override~
				~dorn9.cre~ ~override~
				~dorn10.cre~ ~override~
				~dorn12.cre~ ~override~
				~dorn14.cre~ ~override~
				~neera8.cre~ ~override~
				~neera10.cre~ ~override~
				~neera15.cre~ ~override~
				~OHHEX8.cre~ ~override~
				~OHHEX9.cre~ ~override~
				~OHHEX10.cre~ ~override~
				~OHHEX11.cre~ ~override~
				~OHHEX13.cre~ ~override~
				~OHHEX15.cre~ ~override~
				~OHHEX25.cre~ ~override~
				~OHHFAK8.cre~ ~override~
				~OHHFAK9.cre~ ~override~
				~OHHFAK10.cre~ ~override~
				~OHHFAK11.cre~ ~override~
				~OHHFAK13.cre~ ~override~
				~OHHFAK15.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
		BUT_ONLY
END
//__________________________________________________________________________________

/*
wizard:
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
fighter/mage:
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
fighter:
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 111 1
		SET_BG2_PROFICIENCY 112 1
		SET_BG2_PROFICIENCY 113 1
		SET_BG2_PROFICIENCY 114 1
paladin:
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
ranger:
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 2
stalker:
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
		SET_BG2_PROFICIENCY 114 2
druid:
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 107 1
cleric:
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
bard:
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
thief:
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
*/


//ADD PROFICIENCIES TO BG1 NPCS_____________________________________________________
//
ACTION_IF GAME_IS ~bgee tutu bgt eet~ THEN BEGIN
	COPY_EXISTING ~%tutu_var%ajanti.cre~ ~override~
				~%tutu_var%ajanti4.cre~ ~override~
				~%tutu_var%ajanti6.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%alora.cre~ ~override~
				~%tutu_var%alora6.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 114 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%imoen1.cre~ ~override~
				~%tutu_var%imoen2.cre~ ~override~
				~%tutu_var%imoen4.cre~ ~override~
				~%tutu_var%%imoen6_var%.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 113 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%safana.cre~ ~override~
				~%tutu_var%safana4.cre~ ~override~
				~%tutu_var%safana6.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 114 1
		SET_BG2_PROFICIENCY 113 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%coran.cre~ ~override~
				~%tutu_var%coran5.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 9
		WRITE_SHORT 0x0026 9
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 105 2
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 114 1
		SET_BG2_PROFICIENCY 113 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%skie.cre~ ~override~
				~%tutu_var%skie6.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 114 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%montar.cre~ ~override~
				~%tutu_var%montar2.cre~ ~override~
				~%tutu_var%montar4.cre~ ~override~
				~%tutu_var%montar6.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 114 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%garric.cre~ ~override~
				~%tutu_var%garric2.cre~ ~override~
				~%tutu_var%garric4.cre~ ~override~
				~%tutu_var%garric6.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%eldoth.cre~ ~override~
				~%tutu_var%eldoth5.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%dynahe.cre~ ~override~
				~%tutu_var%dynahe2.cre~ ~override~
				~%tutu_var%dynahe4.cre~ ~override~
				~%tutu_var%dynahe6.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%edwin.cre~ ~override~
				~%tutu_var%edwin2.cre~ ~override~
				~%tutu_var%edwin4.cre~ ~override~
				~%tutu_var%edwin6.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%%xan_var%.cre~ ~override~
				~%tutu_var%xan4.cre~ ~override~
				~%tutu_var%xan6.cre~ ~override~
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		BUT_ONLY
	COPY_EXISTING ~sw1h13.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			READ_BYTE 0x31 prof
			PATCH_IF prof = 96 BEGIN
				WRITE_BYTE 0x31 90
				READ_LONG 0x54 "valid"
				PATCH_IF (%valid% >= 0) BEGIN // verify name is valid
					READ_STRREF 0x54 "desc"
					INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
						REPLACE_TEXTUALLY ~Small Sword~ ~Longsword~
					END
					SAY_EVALUATED 0x54 ~%new_desc%~
				END
			END
		END
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%%xzar_var%.cre~ ~override~
				~%tutu_var%xzar2.cre~ ~override~
				~%tutu_var%xzar4.cre~ ~override~
				~%tutu_var%xzar6.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%jaheir.cre~ ~override~
				~%tutu_var%jaheir2.cre~ ~override~
				~%tutu_var%jaheir4.cre~ ~override~
				~%tutu_var%jaheir6.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 9
		WRITE_SHORT 0x0026 9
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 111 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%faldor.cre~ ~override~
				~%tutu_var%faldor5.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 107 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%yeslic.cre~ ~override~
				~%tutu_var%yeslic5.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%branwe.cre~ ~override~
				~%tutu_var%branwe5.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%%quayle_var%.cre~ ~override~
				~%tutu_var%quayle4.cre~ ~override~
				~%tutu_var%quayle6.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 5
		WRITE_SHORT 0x0026 5
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 102 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%viconi.cre~ ~override~
				~%tutu_var%viconi4.cre~ ~override~
				~%tutu_var%%viconi6_var%.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%tiax.cre~ ~override~
				~%tutu_var%tiax4.cre~ ~override~
				~%tutu_var%tiax6.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 6
		WRITE_SHORT 0x0026 6
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%minsc.cre~ ~override~
				~%tutu_var%minsc2.cre~ ~override~
				~%tutu_var%minsc4.cre~ ~override~
				~%tutu_var%minsc6.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 114 2
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 103 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%kivan.cre~ ~override~
				~%tutu_var%kivan4.cre~ ~override~
				~%tutu_var%kivan6.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 114 2
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%khalid.cre~ ~override~
				~%tutu_var%khalid2.cre~ ~override~
				~%tutu_var%khalid4.cre~ ~override~
				~%tutu_var%khalid6.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 112 1
		SET_BG2_PROFICIENCY 113 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%kagain.cre~ ~override~
				~%tutu_var%kagain2.cre~ ~override~
				~%tutu_var%kagain4.cre~ ~override~
				~%tutu_var%kagain6.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		WRITE_SHORT 0x0024 11
		WRITE_SHORT 0x0026 11
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 114 1
		BUT_ONLY
	COPY_EXISTING ~%tutu_var%sharte.cre~ ~override~
				~%tutu_var%sharte4.cre~ ~override~
				~%tutu_var%sharte6.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
		BUT_ONLY
END
/*
ACTION_IF FILE_EXISTS_IN_GAME ~xan.cre~ THEN BEGIN
	COPY_EXISTING ~xan.cre~ ~override~
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 107 1
		BUT_ONLY
	END
ACTION_IF GAME_IS ~bgt~ THEN BEGIN
	COPY_EXISTING ~imoen61.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 113 1
		BUT_ONLY
	COPY_EXISTING ~viconi61.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		BUT_ONLY
END
*/
ACTION_IF GAME_IS ~bgee eet~ THEN BEGIN
	COPY_EXISTING ~dorn.cre~ ~override~
				~dorn2.cre~ ~override~
				~dorn4.cre~ ~override~
				~dorn6.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
		BUT_ONLY
	COPY_EXISTING ~baeloth.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		BUT_ONLY
	COPY_EXISTING ~neera.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 96 1
		BUT_ONLY
	COPY_EXISTING ~neera2.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 96 1
		BUT_ONLY
	COPY_EXISTING ~neera4.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 96 1
		BUT_ONLY
	COPY_EXISTING ~neera6.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 96 1
		BUT_ONLY
END
//__________________________________________________________________________________

//ADD PROFICIENCIES TO BG2 NPCS______________________________________________________
//
ACTION_IF GAME_IS ~tob bgt bg2ee eet~ THEN BEGIN
	COPY_EXISTING ~edwin7.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		BUT_ONLY
	COPY_EXISTING ~edwin9.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		BUT_ONLY
	COPY_EXISTING ~edwin11.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		BUT_ONLY
	COPY_EXISTING ~edwin12.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		BUT_ONLY
	COPY_EXISTING ~edwin13.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		BUT_ONLY
	COPY_EXISTING ~edwin15.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 103 1
		BUT_ONLY
	COPY_EXISTING ~korgan8.cre~ ~override~
				~korgan9.cre~ ~override~
				~korgan11.cre~ ~override~
				~korgan12.cre~ ~override~
				~korgan15.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		WRITE_SHORT 0x0024 11
		WRITE_SHORT 0x0026 11
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 112 1
		SET_BG2_PROFICIENCY 114 1
		BUT_ONLY
	COPY_EXISTING ~sarevok.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		WRITE_SHORT 0x0024 11
		WRITE_SHORT 0x0026 11
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 111 1
		SET_BG2_PROFICIENCY 113 1
		BUT_ONLY
	COPY_EXISTING ~keldor8.cre~ ~override~
				~keldor9.cre~ ~override~
				~keldor10.cre~ ~override~
				~keldor12.cre~ ~override~
				~keldor14.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
		BUT_ONLY
	COPY_EXISTING ~minsc7.cre~ ~override~
				~minsc8.cre~ ~override~
				~minsc9.cre~ ~override~
				~minsc10.cre~ ~override~
				~minsc12.cre~ ~override~
				~minsc14.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
		SET_BG2_PROFICIENCY 114 2
		BUT_ONLY
	COPY_EXISTING ~valyg8.cre~ ~override~
				~valyg9.cre~ ~override~
				~valyg11.cre~ ~override~
				~valyg12.cre~ ~override~
				~valyg14.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 2
		BUT_ONLY
	COPY_EXISTING ~anomen6.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 97 2
		SET_BG2_PROFICIENCY 100 2
		SET_BG2_PROFICIENCY 101 2
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
		ADD_CRE_ITEM ~d5_pano.itm~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
	COPY_EXISTING ~anomen7.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 97 2
		SET_BG2_PROFICIENCY 100 2
		SET_BG2_PROFICIENCY 101 2
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
		ADD_CRE_ITEM ~d5_pano.itm~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
	COPY_EXISTING ~anomen8.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 97 2
		SET_BG2_PROFICIENCY 100 2
		SET_BG2_PROFICIENCY 101 2
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
		ADD_CRE_ITEM ~d5_pano.itm~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
	COPY_EXISTING ~anomen9.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 97 2
		SET_BG2_PROFICIENCY 100 2
		SET_BG2_PROFICIENCY 101 2
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
		ADD_CRE_ITEM ~d5_pano.itm~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
	COPY_EXISTING ~anomen10.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 97 2
		SET_BG2_PROFICIENCY 100 2
		SET_BG2_PROFICIENCY 101 2
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
		ADD_CRE_ITEM ~d5_pano.itm~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
	COPY_EXISTING ~anomen12.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 97 2
		SET_BG2_PROFICIENCY 100 2
		SET_BG2_PROFICIENCY 101 2
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
		ADD_CRE_ITEM ~d5_pano.itm~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
	COPY_EXISTING ~viconi6.cre~ ~override~
				~viconi8.cre~ ~override~
				~viconi9.cre~ ~override~
				~viconi11.cre~ ~override~
				~viconi13.cre~ ~override~
				~viconi16.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
		BUT_ONLY
	COPY_EXISTING ~aerie6.cre~ ~override~
				~aerie7.cre~ ~override~
				~aerie9.cre~ ~override~
				~aerie10.cre~ ~override~
				~aerie11.cre~ ~override~
				~aerie12.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
		BUT_ONLY
	COPY_EXISTING ~jaheir7.cre~ ~override~
				~jaheir8.cre~ ~override~
				~jaheir11.cre~ ~override~
				~jaheir12.cre~ ~override~
				~jahei12b.cre~ ~override~
				~jahei14.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 9
		WRITE_SHORT 0x0026 9
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 107 1
		BUT_ONLY
	COPY_EXISTING ~cernd10.cre~ ~override~
				~cernd12.cre~ ~override~
				~cernd13.cre~ ~override~
				~cernd13b.cre~ ~override~
				~cernd14.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 107 1
		BUT_ONLY
	COPY_EXISTING ~imoen6.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 2
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 2
		SET_BG2_PROFICIENCY 114 1		
		ADD_CRE_ITEM ~d5_pimo.itm~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
	COPY_EXISTING ~imoen10.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 2
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 2
		SET_BG2_PROFICIENCY 114 1		
		ADD_CRE_ITEM ~d5_pimo.itm~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
	COPY_EXISTING ~imoen15.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 2
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 2
		SET_BG2_PROFICIENCY 114 1		
		ADD_CRE_ITEM ~d5_pimo.itm~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
	COPY_EXISTING ~imoen211.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 2
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 2
		SET_BG2_PROFICIENCY 114 1		
		ADD_CRE_ITEM ~d5_pimo.itm~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
	COPY_EXISTING ~imoen213.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 2
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 2
		SET_BG2_PROFICIENCY 114 1		
		ADD_CRE_ITEM ~d5_pimo.itm~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
	COPY_EXISTING ~nalia8.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 2
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
		ADD_CRE_ITEM ~d5_pnal.itm~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
	COPY_EXISTING ~nalia10.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 2
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
		ADD_CRE_ITEM ~d5_pnal.itm~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
	COPY_EXISTING ~nalia11.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 2
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
		ADD_CRE_ITEM ~d5_pnal.itm~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
	COPY_EXISTING ~nalia13.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 2
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
		ADD_CRE_ITEM ~d5_pnal.itm~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
	COPY_EXISTING ~nalia15.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 2
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
		ADD_CRE_ITEM ~d5_pnal.itm~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
	COPY_EXISTING ~nalia18.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 2
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
		ADD_CRE_ITEM ~d5_pnal.itm~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
	COPY_EXISTING ~jan8.cre~ ~override~
				~jan10.cre~ ~override~
				~jan11.cre~ ~override~
				~jan12.cre~ ~override~
				~jan15.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 6
		WRITE_SHORT 0x0026 6
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 114 1
		BUT_ONLY
	COPY_EXISTING ~yoshi7.cre~ ~override~
				~yoshi8.cre~ ~override~
				~yoshi10.cre~ ~override~
				~yoshi11.cre~ ~override~
				~yoshi12.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
		SET_BG2_PROFICIENCY 114 1
		BUT_ONLY
	COPY_EXISTING ~haer10.cre~ ~override~
				~haer11.cre~ ~override~
				~haer13.cre~ ~override~
				~haer15.cre~ ~override~
				~haer19.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 113 1
		SET_BG2_PROFICIENCY 114 1
		BUT_ONLY
END
ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN
	COPY_EXISTING ~dorn8.cre~ ~override~
				~dorn9.cre~ ~override~
				~dorn10.cre~ ~override~
				~dorn12.cre~ ~override~
				~dorn14.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
		BUT_ONLY
	COPY_EXISTING ~neera8.cre~ ~override~
				~neera10.cre~ ~override~
				~neera11.cre~ ~override~
				~neera12.cre~ ~override~
				~neera13.cre~ ~override~
				~neera15.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
	COPY_EXISTING ~ohhex8.cre~ ~override~
				~ohhex9.cre~ ~override~
				~ohhex10.cre~ ~override~
				~ohhex11.cre~ ~override~
				~ohhex13.cre~ ~override~
				~ohhex15.cre~ ~override~
				~ohhex25.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 2
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
	COPY_EXISTING ~ohhfak8.cre~ ~override~
				~ohhfak9.cre~ ~override~
				~ohhfak10.cre~ ~override~
				~ohhfak11.cre~ ~override~
				~ohhfak13.cre~ ~override~
				~ohhfak15.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 2
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END
//__________________________________________________________________________________


//ADD PROFICIENCIES TO MOD NPCS______________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~lk#arath.cre~ THEN BEGIN
	COPY_EXISTING ~lk#arath.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~lk#arath.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 98 2
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~chloe7.cre~ THEN BEGIN
	COPY_EXISTING ~chloe7.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~chloe7.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 9
		WRITE_SHORT 0x0026 9
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 111 1
		SET_BG2_PROFICIENCY 113 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~chloe9.cre~ THEN BEGIN
	COPY_EXISTING ~chloe9.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~chloe9.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 9
		WRITE_SHORT 0x0026 9
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 111 1
		SET_BG2_PROFICIENCY 113 1
		SET_BG2_PROFICIENCY 114 2
END	

ACTION_IF FILE_EXISTS_IN_GAME ~chloe13.cre~ THEN BEGIN
	COPY_EXISTING ~chloe13.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~chloe13.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 9
		WRITE_SHORT 0x0026 9
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 111 1
		SET_BG2_PROFICIENCY 113 1
		SET_BG2_PROFICIENCY 114 2
END	

ACTION_IF FILE_EXISTS_IN_GAME ~chloe15.cre~ THEN BEGIN
	COPY_EXISTING ~chloe15.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~chloe15.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 9
		WRITE_SHORT 0x0026 9
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 111 1
		SET_BG2_PROFICIENCY 113 1
		SET_BG2_PROFICIENCY 114 3
END	

ACTION_IF FILE_EXISTS_IN_GAME ~nath07.cre~ THEN BEGIN
	COPY_EXISTING ~nath07.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~nath07.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 111 1
		SET_BG2_PROFICIENCY 113 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~nath08.cre~ THEN BEGIN
	COPY_EXISTING ~nath08.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~nath08.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 111 1
		SET_BG2_PROFICIENCY 113 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~nath10.cre~ THEN BEGIN
	COPY_EXISTING ~nath10.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~nath10.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 111 1
		SET_BG2_PROFICIENCY 113 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~nath25.cre~ THEN BEGIN
	COPY_EXISTING ~nath25.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~nath25.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 111 1
		SET_BG2_PROFICIENCY 113 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~rh#adr1.cre~ THEN BEGIN
	COPY_EXISTING ~rh#adr1.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~rh#adr1.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~rh#adr2.cre~ THEN BEGIN
	COPY_EXISTING ~rh#adr2.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~rh#adr2.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~rh#adr25.cre~ THEN BEGIN
	COPY_EXISTING ~rh#adr25.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~rh#adr25.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~p#deher.cre~ THEN BEGIN
	COPY_EXISTING ~p#deher.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~p#deher.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~p#dehdiv.cre~ THEN BEGIN
	COPY_EXISTING ~p#dehdiv.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~p#dehdiv.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~p#dehenc.cre~ THEN BEGIN
	COPY_EXISTING ~p#dehenc.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~p#dehenc.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~lk#nind.cre~ THEN BEGIN
	COPY_EXISTING ~lk#nind.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~lk#nind.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~lk#ni25.cre~ THEN BEGIN
	COPY_EXISTING ~lk#ni25.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~lk#ni25.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~j#klsy09.cre~ THEN BEGIN
	COPY_EXISTING ~j#klsy09.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~j#klsy09.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~j#klsy09.cre~ THEN BEGIN
	COPY_EXISTING ~j#klsy09.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~j#klsy09.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~j#klsy11.cre~ THEN BEGIN
	COPY_EXISTING ~j#klsy11.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~j#klsy11.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~j#klsy13.cre~ THEN BEGIN
	COPY_EXISTING ~j#klsy13.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~j#klsy13.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~j#klsy25.cre~ THEN BEGIN
	COPY_EXISTING ~j#klsy25.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~j#klsy25.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~vxvar01.cre~ THEN BEGIN
	COPY_EXISTING ~vxvar01.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~vxvar01.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 96 2
END	

ACTION_IF FILE_EXISTS_IN_GAME ~vxvar25.cre~ THEN BEGIN
	COPY_EXISTING ~vxvar25.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~VXvar25.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 96 2
END	

ACTION_IF FILE_EXISTS_IN_GAME ~tashia.cre~ THEN BEGIN
	COPY_EXISTING ~tashia.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~tashia.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~tsujath.cre~ THEN BEGIN
	COPY_EXISTING ~tsujath.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~tsujath.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~t2val.cre~ THEN BEGIN
	COPY_EXISTING ~t2val.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~t2val.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~o#xan09.cre~ THEN BEGIN
	COPY_EXISTING ~o#xan09.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~o#xan09.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~o#xan25.cre~ THEN BEGIN
	COPY_EXISTING ~o#xan25.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~o#xan25.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~o#xanm9.cre~ THEN BEGIN
	COPY_EXISTING ~o#xanm9.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~o#xanm9.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~o#xan25m.cre~ THEN BEGIN
	COPY_EXISTING ~o#xan25m.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~o#xan25m.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~o#xanw9.cre~ THEN BEGIN
	COPY_EXISTING ~o#xanw9.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~o#xanw9.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~o#xan25w.cre~ THEN BEGIN
	COPY_EXISTING ~o#xan25w.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~o#xan25w.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~o#xans9.cre~ THEN BEGIN
	COPY_EXISTING ~o#xans9.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~o#xans9.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~o#xan25s.cre~ THEN BEGIN
	COPY_EXISTING ~o#xan25s.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~o#xan25s.cre~ ~override~
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~o#xanf9.cre~ THEN BEGIN
	COPY_EXISTING ~o#xanf9.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~o#xanf9.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~o#xan25f.cre~ THEN BEGIN
	COPY_EXISTING ~o#xan25f.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~o#xan25f.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~adangel.cre~ THEN BEGIN
	COPY_EXISTING ~adangel.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~adangel.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~adang25.cre~ THEN BEGIN
	COPY_EXISTING ~adang25.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~adang25.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~j#indi01.cre~ THEN BEGIN
	COPY_EXISTING ~j#indi01.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~J#indi01.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~j#indi03.cre~ THEN BEGIN
	COPY_EXISTING ~j#indi03.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~j#indi03.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~j#indi04.cre~ THEN BEGIN
	COPY_EXISTING ~j#indi04.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~j#indi04.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~kiyone.cre~ THEN BEGIN
	COPY_EXISTING ~kiyone.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~kiyone.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~z#kywed.cre~ THEN BEGIN
	COPY_EXISTING ~z#kywed.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~z#kywed.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~zikhalidm.cre~ THEN BEGIN
	COPY_EXISTING ~zikhalidm.cre~ ~override~
				~zikhalid25m.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~zikhalidm.cre~ ~override~
				~zikhalid25m.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~zikhalid.cre~ THEN BEGIN
	COPY_EXISTING ~zikhalid.cre~ ~override~
				~zikhalid25.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~zikhalid.cre~ ~override~
				~zikhalid25.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 112 1
		SET_BG2_PROFICIENCY 113 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~auren.cre~ THEN BEGIN
	COPY_EXISTING ~auren.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~auren.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~auren1.cre~ THEN BEGIN
	COPY_EXISTING ~auren1.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~auren1.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~b!hal.cre~ THEN BEGIN
	COPY_EXISTING ~b!hal.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~b!hal.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 111 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~g#tyrs8.cre~ THEN BEGIN
	COPY_EXISTING ~g#tyrs8.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~g#tyrs8.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~g#tyrs10.cre~ THEN BEGIN
	COPY_EXISTING ~g#tyrs10.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~g#tyrs10.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~g#tyrs11.cre~ THEN BEGIN
	COPY_EXISTING ~g#tyrs11.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~g#tyrs11.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~g#tyrs13.cre~ THEN BEGIN
	COPY_EXISTING ~g#tyrs13.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~g#tyrs13.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~g#tyrs16.cre~ THEN BEGIN
	COPY_EXISTING ~g#tyrs16.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~g#tyrs16.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 113 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~c#ajan08.cre~ THEN BEGIN
	COPY_EXISTING ~c#ajan08.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~c#ajan08.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~c#ajan09.cre~ THEN BEGIN
	COPY_EXISTING ~c#ajan09.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~C#ajan09.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~c#ajan10.cre~ THEN BEGIN
	COPY_EXISTING ~c#ajan10.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~c#ajan10.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~c#ajan12.cre~ THEN BEGIN
	COPY_EXISTING ~c#ajan12.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~c#ajan12.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~c#ajan14.cre~ THEN BEGIN
	COPY_EXISTING ~c#ajan14.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~c#ajan14.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~c#ajan16.cre~ THEN BEGIN
	COPY_EXISTING ~c#ajan16.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~c#ajan16.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~c#ajatob.cre~ THEN BEGIN
	COPY_EXISTING ~c#ajatob.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~c#ajatob.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~rh#isra.cre~ THEN BEGIN
	COPY_EXISTING ~rh#isra.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~rh#isra.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~rh#isr.cre~ THEN BEGIN
	COPY_EXISTING ~rh#isr.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~rh#isr.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~rh#is25.cre~ THEN BEGIN
	COPY_EXISTING ~rh#is25.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~rh#is25.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~saerilet.cre~ THEN BEGIN
	COPY_EXISTING ~saerilet.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~saerilet.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 111 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~p#kivan.cre~ THEN BEGIN
	COPY_EXISTING ~p#kivan.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~p#kivan.cre~ ~override~
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 2
END	

ACTION_IF FILE_EXISTS_IN_GAME ~k#sarah.cre~ THEN BEGIN
	COPY_EXISTING ~k#sarah.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~k#sarah.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 2
END	

ACTION_IF FILE_EXISTS_IN_GAME ~k#sarah1.cre~ THEN BEGIN
	COPY_EXISTING ~k#sarah1.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~k#sarah1.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 2
END	

ACTION_IF FILE_EXISTS_IN_GAME ~t1dar.cre~ THEN BEGIN
	COPY_EXISTING ~t1dar.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~t1dar.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 9
		WRITE_SHORT 0x0026 9
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 2
END	

ACTION_IF FILE_EXISTS_IN_GAME ~t1dar1.cre~ THEN BEGIN
	COPY_EXISTING ~t1dar1.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~t1dar1.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 9
		WRITE_SHORT 0x0026 9
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 2
END	

ACTION_IF FILE_EXISTS_IN_GAME ~t1dar2.cre~ THEN BEGIN
	COPY_EXISTING ~t1dar2.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~t1dar2.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 9
		WRITE_SHORT 0x0026 9
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 2
END	

ACTION_IF FILE_EXISTS_IN_GAME ~t1dar3.cre~ THEN BEGIN
	COPY_EXISTING ~t1dar3.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~t1dar3.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 9
		WRITE_SHORT 0x0026 9
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 2
END	

ACTION_IF FILE_EXISTS_IN_GAME ~v#1whi.cre~ THEN BEGIN
	COPY_EXISTING ~v#1whi.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~v#1whi.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 93 1
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 98 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 107 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~o#bran.cre~ THEN BEGIN
	COPY_EXISTING ~o#bran.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~o#bran.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~o#bran25.cre~ THEN BEGIN
	COPY_EXISTING ~o#bran25.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~o#bran25.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~b!gavin.cre~ THEN BEGIN
	COPY_EXISTING ~b!gavin.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~b!gavin.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~b!gavin2.cre~ THEN BEGIN
	COPY_EXISTING ~b!gavin2.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~b!gavin2.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~b!gav08.cre~ THEN BEGIN
	COPY_EXISTING ~b!gav08.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~b!gav08.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~b!gav13.cre~ THEN BEGIN
	COPY_EXISTING ~b!gav13.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~b!gav13.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~tenya.cre~ THEN BEGIN
	COPY_EXISTING ~tenya.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~tenya.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~lk#neph.cre~ THEN BEGIN
	COPY_EXISTING ~lk#neph.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~lk#neph.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~lk#yesl.cre~ THEN BEGIN
	COPY_EXISTING ~lk#yesl.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~lk#yesl.cre~ ~override~
		WRITE_BYTE 0x0234 1 // sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 92 1
		SET_BG2_PROFICIENCY 97 1
		SET_BG2_PROFICIENCY 100 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 102 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 107 1
		SET_BG2_PROFICIENCY 112 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~k-rose.cre~ THEN BEGIN
	COPY_EXISTING ~k-rose.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~k-rose.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~keto08.cre~ THEN BEGIN
	COPY_EXISTING ~keto08.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~keto08.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~keto10.cre~ THEN BEGIN
	COPY_EXISTING ~keto10.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~keto10.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~keto12.cre~ THEN BEGIN
	COPY_EXISTING ~keto12.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~keto12.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 90 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 101 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~alora09.cre~ THEN BEGIN
	COPY_EXISTING ~alora09.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~alora09.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~alora25.cre~ THEN BEGIN
	COPY_EXISTING ~alora25.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~alora25.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~o#coran.cre~ THEN BEGIN
	COPY_EXISTING ~o#coran.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~o#coran.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~o#cor25.cre~ THEN BEGIN
	COPY_EXISTING ~o#cor25.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~o#cor25.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~t#dace8.cre~ THEN BEGIN
	COPY_EXISTING ~t#dace8.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~t#dace8.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~t#dace12.cre~ THEN BEGIN
	COPY_EXISTING ~t#dace12.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~t#dace12.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~t#dace14.cre~ THEN BEGIN
	COPY_EXISTING ~t#dace14.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~t#dace14.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~e3fade13.cre~ THEN BEGIN
	COPY_EXISTING ~e3fade13.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~e3fade13.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~e3fade25.cre~ THEN BEGIN
	COPY_EXISTING ~e3fade25.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~e3fade25.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~m#ambr10.cre~ THEN BEGIN
	COPY_EXISTING ~m#ambr10.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~m#ambr10.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~m#ambr12.cre~ THEN BEGIN
	COPY_EXISTING ~m#ambr12.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~m#ambr12.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~m#ambr14.cre~ THEN BEGIN
	COPY_EXISTING ~m#ambr14.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~m#ambr14.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~m#ambr15.cre~ THEN BEGIN
	COPY_EXISTING ~m#ambr15.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~m#ambr15.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~mfrn09.cre~ THEN BEGIN
	COPY_EXISTING ~mfrn09.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~mfrn09.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~mfrn11.cre~ THEN BEGIN
	COPY_EXISTING ~mfrn11.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~mfrn11.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~mfrn12.cre~ THEN BEGIN
	COPY_EXISTING ~mfrn12.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~mfrn12.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~mfrn13.cre~ THEN BEGIN
	COPY_EXISTING ~mfrn13.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~mfrn13.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~mfrn14.cre~ THEN BEGIN
	COPY_EXISTING ~mfrn14.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~mfrn14.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~mfrn25.cre~ THEN BEGIN
	COPY_EXISTING ~mfrn25.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~mfrn25.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~rofrn09.cre~ THEN BEGIN
	COPY_EXISTING ~rofrn09.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~rofrn09.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~rofrn11.cre~ THEN BEGIN
	COPY_EXISTING ~rofrn11.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~rofrn11.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~rofrn12.cre~ THEN BEGIN
	COPY_EXISTING ~rofrn12.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~rofrn12.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~rofrn13.cre~ THEN BEGIN
	COPY_EXISTING ~rofrn13.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~rofrn13.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~rofrn14.cre~ THEN BEGIN
	COPY_EXISTING ~rofrn14.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~rofrn14.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~rofrn25.cre~ THEN BEGIN
	COPY_EXISTING ~rofrn25.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~rofrn25.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~kova.cre~ THEN BEGIN
	COPY_EXISTING ~kova.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~kova.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~z#kvwed.cre~ THEN BEGIN
	COPY_EXISTING ~z#kvwed.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~z#kvwed.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~l3petsy.cre~ THEN BEGIN
	COPY_EXISTING ~l3petsy.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~l3petsy.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~l3pet25.cre~ THEN BEGIN
	COPY_EXISTING ~l3pet25.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~l3pet25.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 8
		WRITE_SHORT 0x0026 8
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~1xskie2.cre~ THEN BEGIN
	COPY_EXISTING ~1xskie2.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~1xskie2.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~1xskie3.cre~ THEN BEGIN
	COPY_EXISTING ~1xskie3.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~1xskie3.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~gv#vynd.cre~ THEN BEGIN
	COPY_EXISTING ~gv#vynd.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~gv#vynd.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~o#tiax.cre~ THEN BEGIN
	COPY_EXISTING ~o#tiax.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~o#tiax.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	

ACTION_IF FILE_EXISTS_IN_GAME ~o#tiax25.cre~ THEN BEGIN
	COPY_EXISTING ~o#tiax25.cre~ ~override~
		LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
	COPY_EXISTING ~o#tiax25.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		SET_BG2_PROFICIENCY 115 1
		SET_BG2_PROFICIENCY 91 1
		SET_BG2_PROFICIENCY 95 1
		SET_BG2_PROFICIENCY 96 1
		SET_BG2_PROFICIENCY 103 1
		SET_BG2_PROFICIENCY 105 1
		SET_BG2_PROFICIENCY 114 1
END	
//__________________________________________________________________________________


//MnG KENSAI________________________________________________________________________
// 
ACTION_IF FILE_EXISTS_IN_GAME ~d5_kensai.d5~ BEGIN
	COPY ~scales_of_balance/profs/d5_kenf.spl~ ~override~
		SAY NAME1 @2632
		SAY UNIDENTIFIED_DESC @2632
	COPY ~scales_of_balance/profs/d5_kens.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_klswo.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_ksswo.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_kdagg.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_kscim.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_k2swo.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_kspea.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_kstaf.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_kclub.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_kmace.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_kflai.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_khamm.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_kbaxe.spl~ ~override~
	COPY ~scales_of_balance/profs/d5_kenf.cre~ ~override~
	COMPILE ~scales_of_balance/profs/d5_kenf2.baf~
	COPY_EXISTING ~d5_klswo.2da~ ~override~
				~d5_ksswo.2da~ ~override~
				~d5_kdagg.2da~ ~override~
				~d5_kscim.2da~ ~override~
				~d5_kkata.2da~ ~override~
				~d5_kbswo.2da~ ~override~
				~d5_k2swo.2da~ ~override~
				~d5_khalb.2da~ ~override~
				~d5_kspea.2da~ ~override~
				~d5_kstaf.2da~ ~override~
				~d5_kclub.2da~ ~override~
				~d5_kmace.2da~ ~override~
				~d5_kflai.2da~ ~override~
				~d5_khamm.2da~ ~override~
				~d5_kbaxe.2da~ ~override~
		REPLACE_TEXTUALLY ~D5_KENF2~ ~****    ~
		REPLACE_TEXTUALLY ~D5_KENF3~ ~****    ~
		REPLACE_TEXTUALLY ~D5_KENF4~ ~****    ~
		REPLACE_TEXTUALLY ~D5_KENF5~ ~****    ~
		REPLACE_TEXTUALLY ~D5_KENF6~ ~****    ~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/kensai_focus.txt~

  ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25362 @2648
  END
  ACTION_IF ENGINE_IS ~tob bg2ee eet~ THEN BEGIN
	STRING_SET 25204 @2648
  END
  ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37100 @2648
  END
END
//__________________________________________________________________________________


//UPDATE SoA STARTING XP____________________________________________________________
// 
ACTION_IF GAME_IS ~tob~ AND NOT GAME_IS ~bgt~ THEN BEGIN
	ACTION_IF FILE_EXISTS ~bgmain.exe~ BEGIN
		COPY ~bgmain.exe~ ~bgmain.exe~
			SET i = 1
			WHILE (i>0) BEGIN
				SET i += 4
				READ_LONG (0x6b0000 + "%i%" - 1) long_value //start at offset 0x6b0000
				READ_LONG (0x6b0000 + "%i%" - 5) long_before_value
				READ_LONG (0x6b0000 + "%i%" + 3) long_after_value
				PATCH_IF ("%long_before_value%" = 0) AND ("%long_after_value%" = 161000) THEN BEGIN //look only for a long value bounded by a previous value of 0, and a next value of 161000
					WRITE_LONG (0x6b0000 + "%i%" - 1) 1 //setting to zero causes thieving skills to isolate from proficiencies and screws up skill types
				END
				PATCH_IF ("%i%" = 0x10001) BEGIN //span a region of 0x10000 bytes
					SET i = 0
				END
			END
	END
	EXTEND_BOTTOM ~ar0602.bcs~ ~scales_of_balance/misc/soaxp.baf~
END

ACTION_IF GAME_IS ~bg2ee~ THEN BEGIN
	COPY_EXISTING ~startare.2da~ ~override~
		SET_2DA_ENTRY 12 1 1 ~1000~
		BUT_ONLY
	EXTEND_BOTTOM ~ar0602.bcs~ ~scales_of_balance/misc/soaxp.baf~
END
//__________________________________________________________________________________


CLEAR_ARRAYS
