
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						SAVING THROW STANDARDIZATION
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION revise_save_tables BEGIN

//EDIT SAVE TABLES__________________________________________________________________
//
COPY ~scales_of_balance/misc/save_flat.2da~ ~override/savemonk.2da~
COPY ~scales_of_balance/misc/save_flat.2da~ ~override/saveprs.2da~
COPY ~scales_of_balance/misc/save_flat.2da~ ~override/saverog.2da~
COPY ~scales_of_balance/misc/save_flat.2da~ ~override/savewar.2da~
COPY ~scales_of_balance/misc/save_flat.2da~ ~override/savewiz.2da~
//___________________________________________________________________________________


// apply stat bonuses here

END
//___________________________________________________________________________________

