
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						HIT DICE CHANGES
//__________________________________________________________________________________
//__________________________________________________________________________________


//CHANGE HIT DICE TABLES_______________________________________________________________
//
COPY ~scales_of_balance/misc/hpconbon_hc.2da~ ~override/hpconbon.2da~
COPY ~scales_of_balance/misc/hpbarb.2da~ ~override~
COPY ~scales_of_balance/misc/hpcm.2da~ ~override~
COPY ~scales_of_balance/misc/hpct.2da~ ~override~
COPY ~scales_of_balance/misc/hpfc.2da~ ~override~
COPY ~scales_of_balance/misc/hpfm.2da~ ~override~
COPY ~scales_of_balance/misc/hpfmt.2da~ ~override~
COPY ~scales_of_balance/misc/hpft.2da~ ~override~
COPY ~scales_of_balance/misc/hpmt.2da~ ~override~
COPY ~scales_of_balance/misc/hpmonk.2da~ ~override~
COPY ~scales_of_balance/misc/hpprs.2da~ ~override~
COPY ~scales_of_balance/misc/hprog.2da~ ~override~
COPY ~scales_of_balance/misc/hpwar.2da~ ~override~
COPY ~scales_of_balance/misc/hpwiz.2da~ ~override~
//___________________________________________________________________________________


//EDIT CON DESCRIPTION_______________________________________________________________
//
  STRING_SET 9583 @2007 
//___________________________________________________________________________________


//ADD A FEW HP TO NPCs_______________________________________________________________
//
COPY_EXISTING_REGEXP GLOB ~^.+\.cre$~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
		READ_LONG 0x1cc biography
		PATCH_IF (biography > 0 && biography < 2147483647) BEGIN // party-joinable NPC
			LPF ADD_CRE_EFFECT INT_VAR opcode=17 target=1 timing=1 power=1 paramater1=4 parameter2=0 END
			LPF ADD_CRE_EFFECT INT_VAR opcode=18 target=1 timing=9 power=1 paramater1=4 parameter2=0 END
		END
	END
BUT_ONLY
//___________________________________________________________________________________
