
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						HIT DICE CHANGES
//__________________________________________________________________________________
//__________________________________________________________________________________


//CHANGE HIT DICE TABLES_______________________________________________________________
//
COPY ~scales_of_balance/stats/hpconbon_reduced.2da~ ~override/hpconbon.2da~
COPY ~scales_of_balance/stats/hpbarb_reduced.2da~ ~override/hpbarb.2da~
COPY ~scales_of_balance/stats/hpcm_reduced.2da~ ~override/hpcm.2da~
COPY ~scales_of_balance/stats/hpct_reduced.2da~ ~override/hpct.2da~
COPY ~scales_of_balance/stats/hpfc_reduced.2da~ ~override/hpfc.2da~
COPY ~scales_of_balance/stats/hpfm_reduced.2da~ ~override/hpfm.2da~
COPY ~scales_of_balance/stats/hpfmt_reduced.2da~ ~override/hpfmt.2da~
COPY ~scales_of_balance/stats/hpft_reduced.2da~ ~override/hpft.2da~
COPY ~scales_of_balance/stats/hpmt_reduced.2da~ ~override/hpmt.2da~
COPY ~scales_of_balance/stats/hpmonk_reduced.2da~ ~override/hpmonk.2da~
COPY ~scales_of_balance/stats/hpprs_reduced.2da~ ~override/hpprs.2da~
COPY ~scales_of_balance/stats/hprog_reduced.2da~ ~override/hprog.2da~
COPY ~scales_of_balance/stats/hpwar_reduced.2da~ ~override/hpwar.2da~
COPY ~scales_of_balance/stats/hpwiz_reduced.2da~ ~override/hpwiz.2da~
//___________________________________________________________________________________


//EDIT CON DESCRIPTION_______________________________________________________________
//
  STRING_SET 9583 @2010 
//___________________________________________________________________________________


//ADD A FEW HP TO NPCs_______________________________________________________________
//
COPY_EXISTING_REGEXP GLOB ~^.+\.cre$~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
		READ_LONG 0x1cc biography
		PATCH_IF (biography > 0 && biography < 2147483647) BEGIN // party-joinable NPC
			LPF ADD_CRE_EFFECT INT_VAR opcode=17 target=1 timing=1 power=1 paramater1=4 parameter2=0 END
			LPF ADD_CRE_EFFECT INT_VAR opcode=18 target=1 timing=9 power=1 paramater1=4 parameter2=0 END
		END
	END
BUT_ONLY
//___________________________________________________________________________________
