
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						WARRIOR KITS
//__________________________________________________________________________________
//__________________________________________________________________________________


//____________________________HARRIER_______________________________________________

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5FORUN~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5FORUN       3 3 3 2 2 2 2 2~
~D5FORUN       3 3 3 2 2 2 2 2 2 3 3 3 2 2 3 3 2 2 2 2 2 2 3 2 3 3 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FORUN           0   12  9   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FORUN           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FORUN           0   15  15  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FORUN           0   15  15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5FORUN           0  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5FORUN           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/ranger/d5_forun.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_R_E K_R_H K_R_HE K_R_HL K_R_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ra0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @3504
SAY @3505
SAY @3506
//___________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5FORUN~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5FORUN       5 5 2 0 2 2 2 2~
~D5FORUN       5 5 2 0 2 2 2 2 0 5 5 2 0 0 5 5 2 2 0 0 2 2 2 2 0 5 0 2 0 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FORUN           0   12  9   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FORUN           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FORUN           0   15  15  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FORUN           0   15  15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5FORUN           0  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5FORUN           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/ranger/d5_forun.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_R_E K_R_H K_R_HE K_R_HL K_R_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ra0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @3504
SAY @3505
SAY @3508
//___________________________________________________________________________________

END

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@3507)
		STR_VAR
			kit_name = D5FORUN
	END
END
//____________________________________________________________________________________

//HARRIER ABILITY FILES_______________________________________________________________
//
COPY ~scales_of_balance/ranger/d5_trp40.spl~ ~override~
COPY ~scales_of_balance/ranger/d5_trp3.spl~ ~override~
COPY ~scales_of_balance/ranger/d5_forup.spl~ ~override~
COPY ~scales_of_balance/ranger/d5_rnosp.eff~ ~override~
COPY ~scales_of_balance/ranger/d5_rnosp.spl~ ~override~
ACTION_IF FILE_EXISTS_IN_GAME ~d5_strid.d5~ THEN BEGIN
	COPY_EXISTING ~d5_forun.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/misc/strirang.txt~
		BUT_ONLY
END
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
	COPY_EXISTING ~d5_forun.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/ranger/tracking.txt~
		BUT_ONLY
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~d5_apr.d5~) OR (FILE_EXISTS_IN_GAME ~TB#TATT.spl~) THEN BEGIN
		COPY_EXISTING ~d5_forun.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~scales_of_balance/profs/w1apr.txt~
			BUT_ONLY
	END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_taspl.d5~ THEN BEGIN
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_staspl.d5~ THEN BEGIN
	COPY ~scales_of_balance/ranger/d5_staspl.d5~ ~override~
	COPY ~scales_of_balance/misc/mxsplra1.2da~ ~override/mxsplran.2da~
	COPY_EXISTING ~clabrn01.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/ranger/raspl1.txt~
		BUT_ONLY
	COPY_EXISTING ~clabrn02.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/ranger/raspl1.txt~
		BUT_ONLY
	COPY_EXISTING ~clabrn03.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/ranger/raspl1.txt~
		BUT_ONLY
	COPY_EXISTING ~clabrn04.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/ranger/raspl1.txt~
		BUT_ONLY
	ACTION_IF NOT FILE_EXISTS_IN_GAME ~clabrn05.2da~ THEN BEGIN
	COPY_EXISTING ~clabrn05.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/ranger/raspl1.txt~
		BUT_ONLY
	END
	ACTION_IF GAME_IS ~bgee~ THEN BEGIN
		COPY_EXISTING ~kitlist.2da~ ~override~
			COUNT_2DA_ROWS ~10~ "rows"
			PATCH_IF ( rows > 37 ) BEGIN
				FOR ( index = 38 ; index < rows ; index = index + 1 ) BEGIN
					READ_2DA_ENTRY %index% 5 10 modclab
					READ_2DA_ENTRY %index% 8 10 modclass
					DEFINE_ASSOCIATIVE_ARRAY d5_ranspell_clabs BEGIN "%modclab%" => "%modclass%" END
				END
			END
			BUT_ONLY
		ACTION_PHP_EACH d5_ranspell_clabs AS moo => shoo BEGIN
			ACTION_IF (%shoo% = 12) AND (FILE_EXISTS_IN_GAME ~%moo%.2da~) THEN BEGIN
				COPY_EXISTING ~%moo%.2da~ ~override~
					LPM remove_blank_lines
					APPEND_FILE ~scales_of_balance/ranger/raspl1.txt~
					BUT_ONLY
			END
		END
	END
	ACTION_IF GAME_IS ~bg2ee~ THEN BEGIN
		COPY_EXISTING ~kitlist.2da~ ~override~
			COUNT_2DA_ROWS ~10~ "rows"
			PATCH_IF ( rows > 40 ) BEGIN
				FOR ( index = 41 ; index < rows ; index = index + 1 ) BEGIN
					READ_2DA_ENTRY %index% 5 10 modclab
					READ_2DA_ENTRY %index% 8 10 modclass
					DEFINE_ASSOCIATIVE_ARRAY d5_ranspell_clabs BEGIN "%modclab%" => "%modclass%" END
				END
			END
			BUT_ONLY
		ACTION_PHP_EACH d5_ranspell_clabs AS moo => shoo BEGIN
			ACTION_IF (%shoo% = 12) AND (FILE_EXISTS_IN_GAME ~%moo%.2da~) THEN BEGIN
				COPY_EXISTING ~%moo%.2da~ ~override~
					LPM remove_blank_lines
					APPEND_FILE ~scales_of_balance/ranger/raspl1.txt~
					BUT_ONLY
			END
		END
	END
	ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
		COPY_EXISTING ~kitlist.2da~ ~override~
			COUNT_2DA_ROWS ~10~ "rows"
			PATCH_IF ( rows > 41 ) BEGIN
				FOR ( index = 42 ; index < rows ; index = index + 1 ) BEGIN
					READ_2DA_ENTRY %index% 5 10 modclab
					READ_2DA_ENTRY %index% 8 10 modclass
					DEFINE_ASSOCIATIVE_ARRAY d5_ranspell_clabs BEGIN "%modclab%" => "%modclass%" END
				END
			END
			BUT_ONLY
		ACTION_PHP_EACH d5_ranspell_clabs AS moo => shoo BEGIN
			ACTION_IF (%shoo% = 12) AND (FILE_EXISTS_IN_GAME ~%moo%.2da~) THEN BEGIN
				COPY_EXISTING ~%moo%.2da~ ~override~
					LPM remove_blank_lines
					APPEND_FILE ~scales_of_balance/ranger/raspl1.txt~
					BUT_ONLY
			END
		END
	END
	ACTION_IF GAME_IS ~tob bgt tutu~ THEN BEGIN
		COPY_EXISTING ~kitlist.2da~ ~override~
			COUNT_2DA_ROWS ~9~ "rows"
			PATCH_IF ( rows > 31 ) BEGIN
				FOR ( index = 32 ; index < rows ; index = index + 1 ) BEGIN
					READ_2DA_ENTRY %index% 5 9 modclab
					READ_2DA_ENTRY %index% 8 9 modclass
					DEFINE_ASSOCIATIVE_ARRAY d5_ranspell_clabs BEGIN "%modclab%" => "%modclass%" END
				END
			END
			BUT_ONLY
		ACTION_PHP_EACH d5_ranspell_clabs AS moo => shoo BEGIN
			ACTION_IF (%shoo% = 12) AND (FILE_EXISTS_IN_GAME ~%moo%.2da~) THEN BEGIN
				COPY_EXISTING ~%moo%.2da~ ~override~
					LPM remove_blank_lines
					APPEND_FILE ~scales_of_balance/ranger/raspl1.txt~
					BUT_ONLY
			END
		END
	END
END
END

//____________________________________________________________________________________
