
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						     DIVINE TWEAKS
//__________________________________________________________________________________
//__________________________________________________________________________________


//CHANGE PALADINS___________________________________________________________________
// 
COPY - ~scales_of_balance/sob_settings.ini~ ~scales_of_balance/backup~
  COUNT_REGEXP_INSTANCES ~change_paladins=1~ change_paladins

ACTION_IF (change_paladins) THEN BEGIN
	PRINT @107

//__________________________________________________________________________________
STRING_SET 7217 @5001

STRING_SET 10194 @5002

STRING_SET 9558 @5003
//__________________________________________________________________________________

//__________________________________________________________________________________
ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25301 @5004
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25182 @5004
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37132 @5004
END

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25332 @5005
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25154 @5005
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37134 @5005
END

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25363 @5006
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25206 @5006
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37133 @5006
END
//__________________________________________________________________________________

//__________________________________________________________________________________
ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25302 @5007
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25184 @5007
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37136 @5007
END

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25333 @5008
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25155 @5008
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37138 @5008
END
//__________________________________________________________________________________

//__________________________________________________________________________________
ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25303 @5010
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25185 @5010
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37140 @5010
END

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25334 @5011
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25156 @5011
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37142 @5011
END

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25365 @5012
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25208 @5012
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37141 @5012
END
//__________________________________________________________________________________

//MODIFY PALADIN 2DA FILES__________________________________________________________
//
COPY_EXISTING ~clabpa01.2da~ ~override~
	REPLACE_TEXTUALLY ~GA_SPCL212~ ~****      ~
	REPLACE_TEXTUALLY ~GA_SPCL213~ ~****      ~
	LPM remove_blank_lines
	APPEND_FILE ~scales_of_balance/paladin/palclab.txt~
	BUT_ONLY

COPY_EXISTING ~clabpa02.2da~ ~override~
	REPLACE_TEXTUALLY ~GA_SPCL212~ ~****      ~
	LPM remove_blank_lines
	APPEND_FILE ~scales_of_balance/paladin/parclab.txt~
	BUT_ONLY

COPY_EXISTING ~clabpa04.2da~ ~override~
	REPLACE_TEXTUALLY ~GA_SPCL212~ ~****      ~
	REPLACE_TEXTUALLY ~GA_SPCL213~ ~****      ~
	LPM remove_blank_lines
	APPEND_FILE ~scales_of_balance/paladin/palclab.txt~
	BUT_ONLY
//__________________________________________________________________________________

//COPY PALADIN ABILITY FILES________________________________________________________
//
COPY ~scales_of_balance/paladin/d5_paora.spl~ ~override~
	SAY NAME1 @5013
	SAY UNIDENTIFIED_DESC @5013
COPY ~scales_of_balance/paladin/d5_paglo.spl~ ~override~
	SAY NAME1 @5014
	SAY UNIDENTIFIED_DESC @5014
COPY ~scales_of_balance/paladin/d5_pabre.spl~ ~override~
	SAY NAME1 @5018
	SAY UNIDENTIFIED_DESC @5018
COPY ~scales_of_balance/paladin/d5_paspt.spl~ ~override~
	SAY NAME1 @5015
	SAY UNIDENTIFIED_DESC @5015
COPY ~scales_of_balance/paladin/spcl213.spl~ ~override~
	SAY NAME1 @5016
	SAY UNIDENTIFIED_DESC @5016
COPY ~scales_of_balance/paladin/d5_padet.spl~ ~override~
	SAY NAME1 @5017
	SAY UNIDENTIFIED_DESC @5017
//__________________________________________________________________________________

//COPY PALADIN CRE FILES____________________________________________________________
//
ACTION_IF GAME_IS ~tutu bgt bgee~ THEN BEGIN
	COPY_EXISTING ~ajanti.cre~ ~override~
				~ajanti4.cre~ ~override~
				~ajanti6.cre~ ~override~
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PADET~ END
		BUT_ONLY
END
//__________________________________________________________________________________

//CHANGE INQUISITOR_________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25364 @5009
	STRING_SET 24288 @5009
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25207 @5009
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37137 @5009
END

COPY_EXISTING ~clabpa03.2da~ ~override~
	REPLACE_TEXTUALLY ~GA_SPCL212~ ~****      ~
	REPLACE_TEXTUALLY ~GA_SPCL213~ ~****      ~
	REPLACE_TEXTUALLY ~GA_SPCL232~ ~****      ~
	REPLACE_TEXTUALLY ~GA_SPCL231~ ~****      ~
	LPM remove_blank_lines
	APPEND_FILE ~scales_of_balance/paladin/inqclab.txt~
	BUT_ONLY

ACTION_IF GAME_IS ~bgt tob bg2ee~ THEN BEGIN
	COPY_EXISTING ~keldor8.cre~ ~override~
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PADET~ END
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PAORA~ END
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PAGLO~ END
		BUT_ONLY
	COPY_EXISTING ~keldor9.cre~ ~override~
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PADET~ END
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PAORA~ END
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PAGLO~ END
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PAORA~ END
		BUT_ONLY
	COPY_EXISTING ~keldor10.cre~ ~override~
				~keldor12.cre~ ~override~
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PADET~ END
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PAORA~ END
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PAGLO~ END
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PAORA~ END
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PABRE~ END
		BUT_ONLY
	COPY_EXISTING ~keldor14.cre~ ~override~
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PADET~ END
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PAORA~ END
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PAGLO~ END
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PAORA~ END
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PABRE~ END
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PAORA~ END
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_PASPT~ END
		BUT_ONLY
END

//END OF PALADIN CHANGES____________________________________________________________
END
ELSE BEGIN
	PRINT @108
END
//__________________________________________________________________________________


//CHANGE CLERIC STRINGS_____________________________________________________________
//
ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 24256 @5053
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25197 @5053
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37168 @5053
END

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25349 @5054
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25170 @5054
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37170 @5054
END

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25380 @5055
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25223 @5055
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37169 @5055
END

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 24255 @5056
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25196 @5056
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37165 @5056
END

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25348 @5057
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25169 @5057
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37167 @5057
END

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25379 @5058
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25222 @5058
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37166 @5058
END

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 24254 @5059
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25195 @5059
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37162 @5059
END

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25347 @5060
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25168 @5060
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37164 @5060
END

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25378 @5061
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25221 @5061
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37163 @5061
END

ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37428 @5065
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 40681 @5066
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 40682 @5067
END

ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 40774 @5068
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 40775 @5069
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37428 @5070
END
//__________________________________________________________________________________

//MODIFY CLERIC 2DA FILES__________________________________________________________
//
COPY_EXISTING ~clabpr04.2da~ ~override~
	REPLACE_TEXTUALLY ~GA_SPCL741~ ~****      ~
	REPLACE_TEXTUALLY ~GA_SPCL742~ ~****      ~
	LPM remove_blank_lines
	APPEND_FILE ~scales_of_balance/cleric/latclab.txt~
	BUT_ONLY
ACTION_IF FILE_EXISTS_IN_GAME ~dvimhere.mrk~ THEN BEGIN
	COPY_EXISTING ~clabpr04.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/cleric/latsr.txt~
		BUT_ONLY
END
COPY_EXISTING ~clabpr03.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~scales_of_balance/cleric/helclab.txt~
	BUT_ONLY
COPY_EXISTING ~clabpr02.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~scales_of_balance/cleric/talclab.txt~
	BUT_ONLY
//__________________________________________________________________________________

//COPY CLERIC ABILITY FILES________________________________________________________
//
COPY ~scales_of_balance/cleric/d5_latns.spl~ ~override~
COPY ~scales_of_balance/cleric/d5_helns.spl~ ~override~
COPY ~scales_of_balance/cleric/d5_talns.spl~ ~override~
COPY ~scales_of_balance/cleric/d5_latbo.spl~ ~override~
	SAY NAME1 @5062
	SAY UNIDENTIFIED_DESC @5063
COPY ~scales_of_balance/cleric/d5_latre.spl~ ~override~
	SAY NAME1 @5064
	SAY UNIDENTIFIED_DESC @5064
//__________________________________________________________________________________

//CLERIC WEAPONS________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

COPY ~scales_of_balance/cleric/d5_clerics.d5~ ~override~

COPY_EXISTING ~clabpr02.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~scales_of_balance/profs/pcspea.txt~
	BUT_ONLY
COPY_EXISTING ~clabpr03.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~scales_of_balance/profs/pc2swo.txt~
	BUT_ONLY
COPY_EXISTING ~clabpr04.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~scales_of_balance/profs/pcmace.txt~
	BUT_ONLY
ACTION_IF FILE_EXISTS_IN_GAME ~ohtyr.2da~ THEN BEGIN
	COPY_EXISTING ~ohtyr.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pclswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~ohtempus.2da~ THEN BEGIN
	COPY_EXISTING ~ohtempus.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcaxe.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#cyric.2da~ THEN BEGIN
	COPY_EXISTING ~a#cyric.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcsswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#feyw.2da~ THEN BEGIN
	COPY_EXISTING ~a#feyw.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pclswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#koss.2da~ THEN BEGIN
	COPY_EXISTING ~a#koss.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcflai.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#ogma.2da~ THEN BEGIN
	COPY_EXISTING ~a#ogma.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pclswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#red.2da~ THEN BEGIN
	COPY_EXISTING ~a#red.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pclswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#shar.2da~ THEN BEGIN
	COPY_EXISTING ~a#shar.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcdagg.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a#temp.2da~ THEN BEGIN
	COPY_EXISTING ~a#temp.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcaxe.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~cdilmatr.2da~ THEN BEGIN
	COPY_EXISTING ~cdilmatr.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcflai.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~cdselune.2da~ THEN BEGIN
	COPY_EXISTING ~cdselune.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcmace.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~cdxvim.2da~ THEN BEGIN
	COPY_EXISTING ~cdxvim.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcscim.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabeart.2da~ THEN BEGIN
	COPY_EXISTING ~clabeart.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pchamm.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabgruu.2da~ THEN BEGIN
	COPY_EXISTING ~clabgruu.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcaxe.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabluth.2da~ THEN BEGIN
	COPY_EXISTING ~clabluth.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcsswo.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabauri.2da~ THEN BEGIN
	COPY_EXISTING ~clabauri.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcdagg.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabiceg.2da~ THEN BEGIN
	COPY_EXISTING ~clabiceg.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcspea.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clableaf.2da~ THEN BEGIN
	COPY_EXISTING ~clableaf.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcclub.txt~
		BUT_ONLY
END
DEFINE_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
  INT_VAR
    offset = 0
  STR_VAR
    desc = ~~
    unusable_regexp = ~~
    unusable_replacement = ~~
    class_regexp = ~~ //
    class_prefix = ~~ //
BEGIN
  INNER_PATCH_SAVE desc ~%desc%~ BEGIN
    REPLACE_TEXTUALLY ~%unusable_regexp%~ ~%unusable_replacement%~
  END
  PATCH_IF ((~%desc%~ STRING_CONTAINS_REGEXP ~^%unusable_replacement%~) == 0) BEGIN
    INNER_PATCH_SAVE usab_block ~%desc%~ BEGIN
      REPLACE_TEXTUALLY ~\(.*[%LNL%%MNL%%WNL%]\)*%unusable_replacement%~ ~~
    END
    INNER_PATCH_SAVE usab_block_new ~%usab_block%~ BEGIN
      REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%][- %TAB%]*$~ ~~
      REPLACE_TEXTUALLY ~^[- %TAB%]*~ ~%class_prefix%~
      REPLACE_TEXTUALLY ~%mage_regexp%~ ~~
    END
    INNER_PATCH_SAVE desc ~%desc%~ BEGIN
      REPLACE_TEXTUALLY EXACT_MATCH ~%usab_block%~ ~%usab_block_new%~
    END
    INNER_PATCH_SAVE compare ~%desc%~ BEGIN 
      REPLACE_TEXTUALLY ~^%unusable_replacement%.*[%LNL%%MNL%%WNL%]%class_prefix%[^- %TAB%]~ ~~
    END
    PATCH_IF (~%desc%~ STRING_EQUAL ~%compare%~) BEGIN
      INNER_PATCH_SAVE desc ~%desc%~ BEGIN
        REPLACE_TEXTUALLY ~[%LNL%%MNL%%WNL%]%unusable_replacement%.*~ ~~
      END
    END
    SAY_EVALUATED ~%offset%~ ~%desc%~
  END
END
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1e cleric 
		READ_BYTE  0x1f mcler 
		READ_SHORT  ~0x1c~ type 
		PATCH_IF (type = 15) BEGIN // bows
			WRITE_BYTE 0x1e (cleric BAND 0b01111111)
			WRITE_BYTE 0x1f (mcler BAND 0b00111000)
  	      PATCH_FOR_EACH offset IN
  	        ~0x50~
  	        ~0x54~
  	      BEGIN
  	        READ_LONG ~%offset%~ desc_strref
  	        PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
  	          READ_STRREF ~%offset%~ desc
  	         	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
  	         	  STR_VAR
  	         	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
  	         	    unusable_replacement = ~Not Usable By:~
  	         	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
  	         	    class_prefix = ~ ~
  	         	END	
	          END
  	        END
		END
	END
	BUT_ONLY
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1e cleric 
		READ_BYTE  0x1f mcler 
		PATCH_IF (type = 29) BEGIN // spears
			WRITE_BYTE 0x1e (cleric BAND 0b01111111)
			WRITE_BYTE 0x1f (mcler BAND 0b00111000)
	        PATCH_FOR_EACH offset IN
	          ~0x50~
	          ~0x54~
	        BEGIN
	          READ_LONG ~%offset%~ desc_strref
	          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
	            READ_STRREF ~%offset%~ desc
	           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
	           	  STR_VAR
	           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
	           	    unusable_replacement = ~Not Usable By:~
	           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
	           	    class_prefix = ~ ~
	           	END
	          END
	        END
		END
	END
	BUT_ONLY
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1e cleric 
		READ_BYTE  0x1f mcler 
		PATCH_IF (type = 25) BEGIN // axes
			WRITE_BYTE 0x1e (cleric BAND 0b01111111)
			WRITE_BYTE 0x1f (mcler BAND 0b00111000)
	        PATCH_FOR_EACH offset IN
	          ~0x50~
	          ~0x54~
	        BEGIN
	          READ_LONG ~%offset%~ desc_strref
	          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
	            READ_STRREF ~%offset%~ desc
	           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
	           	  STR_VAR
	           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
	           	    unusable_replacement = ~Not Usable By:~
	           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
	           	    class_prefix = ~ ~
	           	END
	          END
	        END
		END
	END
	BUT_ONLY
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1e cleric 
		READ_BYTE  0x1f mcler 
		PATCH_IF (type = 19) BEGIN // small swords
			WRITE_BYTE 0x1e (cleric BAND 0b01111111)
			WRITE_BYTE 0x1f (mcler BAND 0b00111000)
	        PATCH_FOR_EACH offset IN
	          ~0x50~
	          ~0x54~
	        BEGIN
	          READ_LONG ~%offset%~ desc_strref
	          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
	            READ_STRREF ~%offset%~ desc
	           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
	           	  STR_VAR
	           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
	           	    unusable_replacement = ~Not Usable By:~
	           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
	           	    class_prefix = ~ ~
	           	END
	          END
	        END
		END
	END
	BUT_ONLY
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1e cleric 
		READ_BYTE  0x1f mcler 
		PATCH_IF (type = 20) BEGIN // large swords
			WRITE_BYTE 0x1e (cleric BAND 0b01111111)
			WRITE_BYTE 0x1f (mcler BAND 0b00111000)
	        PATCH_FOR_EACH offset IN
	          ~0x50~
	          ~0x54~
	        BEGIN
	          READ_LONG ~%offset%~ desc_strref
	          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
	            READ_STRREF ~%offset%~ desc
	           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
	           	  STR_VAR
	           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
	           	    unusable_replacement = ~Not Usable By:~
	           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
	           	    class_prefix = ~ ~
	           	END
	          END
	        END
		END
	END
	BUT_ONLY
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1e cleric 
		READ_BYTE  0x1f mcler 
		PATCH_IF (type = 16) BEGIN // daggers
			WRITE_BYTE 0x1e (cleric BAND 0b01111111)
			WRITE_BYTE 0x1f (mcler BAND 0b00111000)
	        PATCH_FOR_EACH offset IN
	          ~0x50~
	          ~0x54~
	        BEGIN
	          READ_LONG ~%offset%~ desc_strref
	          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
	            READ_STRREF ~%offset%~ desc
	           	LAUNCH_PATCH_FUNCTION ~REMOVE_CLASS_LINE_FROM_USABILITIES~
	           	  STR_VAR
	           	    unusable_regexp = EVALUATE_BUFFER ~^[ %TAB%]*\(Unusable By\|Not Usable By\).*~
	           	    unusable_replacement = ~Not Usable By:~
	           	    class_regexp = EVALUATE_BUFFER ~[%LNL%%MNL%%WNL%].*\bCleric.*~
	           	    class_prefix = ~ ~
	           	END
	          END
	        END
		END
	END
	BUT_ONLY
END
//__________________________________________________________________________________

//EDIT CLERIC MOD NPCS______________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~b!gavin.cre~ THEN BEGIN
	COPY_EXISTING ~b!gavin.cre~ ~override~
		WRITE_SHORT 0x0234 1 //sets level to 1
		WRITE_SHORT 0x0235 1
		WRITE_SHORT 0x0236 1
		WRITE_SHORT 0x244 0
		WRITE_BYTE 0x247 0x40
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		WRITE_LONG 0x02a0 0x000 //removes known spells
		WRITE_LONG 0x02a4 0x000
		WRITE_LONG 0x02b0 0x000 // removes memorized spells
		WRITE_LONG 0x02b4 0x000
		LPF ADD_CRE_EFFECT INT_VAR opcode=147 target=1 timing=9 power=1 STR_VAR resource=~d5_latbo~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~b!gavin2.cre~ THEN BEGIN
	COPY_EXISTING ~b!gavin2.cre~ ~override~
		WRITE_SHORT 0x0234 1 //sets level to 1
		WRITE_SHORT 0x0235 1
		WRITE_SHORT 0x0236 1
		WRITE_SHORT 0x244 0
		WRITE_BYTE 0x247 0x40
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		WRITE_LONG 0x02a0 0x000 //removes known spells
		WRITE_LONG 0x02a4 0x000
		WRITE_LONG 0x02b0 0x000 // removes memorized spells
		WRITE_LONG 0x02b4 0x000
		LPF ADD_CRE_EFFECT INT_VAR opcode=147 target=1 timing=9 power=1 STR_VAR resource=~d5_latbo~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~b!gav08.cre~ THEN BEGIN
	COPY_EXISTING ~b!gav08.cre~ ~override~
		WRITE_SHORT 0x0234 1 //sets level to 1
		WRITE_SHORT 0x0235 1
		WRITE_SHORT 0x0236 1
		WRITE_SHORT 0x244 0
		WRITE_BYTE 0x247 0x40
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		WRITE_LONG 0x02a0 0x000 //removes known spells
		WRITE_LONG 0x02a4 0x000
		WRITE_LONG 0x02b0 0x000 // removes memorized spells
		WRITE_LONG 0x02b4 0x000
		LPF ADD_CRE_EFFECT INT_VAR opcode=147 target=1 timing=9 power=1 STR_VAR resource=~d5_latbo~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~b!gav013.cre~ THEN BEGIN
	COPY_EXISTING ~b!gav13.cre~ ~override~
		WRITE_SHORT 0x0234 1 //sets level to 1
		WRITE_SHORT 0x0235 1
		WRITE_SHORT 0x0236 1
		WRITE_SHORT 0x244 0
		WRITE_BYTE 0x247 0x40
		WRITE_SHORT 0x0024 7
		WRITE_SHORT 0x0026 7
		WRITE_LONG 0x02a0 0x000 //removes known spells
		WRITE_LONG 0x02a4 0x000
		WRITE_LONG 0x02b0 0x000 // removes memorized spells
		WRITE_LONG 0x02b4 0x000
		LPF ADD_CRE_EFFECT INT_VAR opcode=147 target=1 timing=9 power=1 STR_VAR resource=~d5_latbo~ END
END
//__________________________________________________________________________________
