
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							STAT-BASED BONUS SPELLS
//__________________________________________________________________________________
//__________________________________________________________________________________


// -----------------------------
// ABILITY SCORE BONUS SPELLS
// -----------------------------

// ***** zero out MXSPLWIS, use this method for all priests - and paladins and rangers, too

DEFINE_ACTION_FUNCTION ability_bonus_spells BEGIN 

//Define undefined mage clabs
//
ACTION_FOR_EACH kitclab IN ~CLABMA01~ ~CLABMA02~ ~CLABMA03~ ~CLABMA04~ ~CLABMA05~ ~CLABMA06~ ~CLABMA07~ ~CLABMA08~ ~CLABMA09~ BEGIN 
	ACTION_IF !(FILE_EXISTS_IN_GAME ~%kitclab%.2DA~) THEN BEGIN
		COPY ~%MOD_FOLDER%/data/stats/BLANKCLAB.2da~ ~override/%kitclab%.2da~ // generate undefined clab files
	END 
END  

APPEND ~splprot.2da~ ~D5_INT_SLOTS%TAB%38%TAB%-1%TAB%1~ UNLESS ~D5_INT_SLOTS~
APPEND ~splprot.2da~ ~D5_CHR_SLOTS%TAB%42%TAB%-1%TAB%1~ UNLESS ~D5_CHR_SLOTS~

COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols 
	READ_2DA_ENTRIES_NOW rows cols   
	FOR (row = 1; row < rows; ++row) BEGIN 
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ 
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_INT_SLOTS~ BEGIN
	    SET int_slots = %row%
	  END
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_CHR_SLOTS~ BEGIN
	    SET chr_slots = %row%
	  END
	END
BUT_ONLY

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5__abil_spells.d5~) THEN BEGIN

// INCREASE the # of mage/bard/sorcerer/dd slots by 2... then we will reduce them by stat

ACTION_FOR_EACH mage_table IN ~mxsplwiz~ BEGIN
  COPY_EXISTING ~%mage_table%.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 0; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 slots
	  PATCH_IF !(FILE_EXISTS_IN_GAME ~qdtnb_l1cantrips.qd~) BEGIN
		PATCH_IF (slots > 0) BEGIN
		  SET_2DA_ENTRY row 1 cols (slots + 2)
		END
	  END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~qdtnb_l1cantrips.qd~) BEGIN
		PATCH_IF (slots > 0) BEGIN
		  SET_2DA_ENTRY row 1 cols (slots + 1)
		END
	  END
	  FOR (col = 2; col < 8; ++col) BEGIN
		READ_2DA_ENTRY_FORMER rows row col slots
		PATCH_IF (slots > 0) BEGIN
		  SET_2DA_ENTRY row col cols (slots + 2)
		END
	  END
	END
  IF_EXISTS BUT_ONLY
END
ACTION_FOR_EACH bard_table IN ~mxsplbrd~ BEGIN
  COPY_EXISTING ~%bard_table%.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 0; row < rows; ++row) BEGIN
	  FOR (col = 1; col < 7; ++col) BEGIN
		READ_2DA_ENTRY_FORMER rows row col slots
		PATCH_IF (slots > 0) BEGIN
		  SET_2DA_ENTRY row col cols (slots + 2)
		END
	  END
	END
  IF_EXISTS BUT_ONLY
END
ACTION_FOR_EACH sorc_table IN ~mxsplsrc~ ~mxspldd~ BEGIN
  COPY_EXISTING ~%sorc_table%.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 0; row < rows; ++row) BEGIN
	  FOR (col = 1; col < 6; ++col) BEGIN
		READ_2DA_ENTRY_FORMER rows row col slots
		PATCH_IF (slots > 0) BEGIN
		  SET_2DA_ENTRY row col cols (slots + 2)
		END
	  END
	END
  IF_EXISTS BUT_ONLY
END
ACTION_FOR_EACH cleric_table IN ~mxsplprs~ BEGIN
  COPY_EXISTING ~%cleric_table%.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 0; row < rows; ++row) BEGIN
	  FOR (col = 1; col < cols; ++col) BEGIN
		READ_2DA_ENTRY_FORMER rows row col slots
		PATCH_IF (slots > 0) BEGIN
		  SET_2DA_ENTRY row col cols (slots + 2)
		END
	  END
	END
  IF_EXISTS BUT_ONLY
END
ACTION_FOR_EACH druid_table IN ~mxspldru~ BEGIN
  COPY_EXISTING ~%druid_table%.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 0; row < rows; ++row) BEGIN
	  FOR (col = 1; col < cols; ++col) BEGIN
		READ_2DA_ENTRY_FORMER rows row col slots
		PATCH_IF (slots > 0) BEGIN
		  SET_2DA_ENTRY row col cols (slots + 2)
		END
	  END
	END
  IF_EXISTS BUT_ONLY
END
ACTION_FOR_EACH paladin_table IN ~mxsplpal~ BEGIN
  COPY_EXISTING ~%paladin_table%.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 0; row < rows; ++row) BEGIN
	  FOR (col = 1; col < cols; ++col) BEGIN
		READ_2DA_ENTRY_FORMER rows row col slots
		PATCH_IF (slots > 0) BEGIN
		  SET_2DA_ENTRY row col cols (slots + 2)
		END
	  END
	END
  IF_EXISTS BUT_ONLY
END
ACTION_FOR_EACH ranger_table IN ~mxsplran~ BEGIN
  COPY_EXISTING ~%ranger_table%.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 0; row < rows; ++row) BEGIN
	  FOR (col = 1; col < cols; ++col) BEGIN
		READ_2DA_ENTRY_FORMER rows row col slots
		PATCH_IF (slots > 0) BEGIN
		  SET_2DA_ENTRY row col cols (slots + 2)
		END
	  END
	END
  IF_EXISTS BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~qdtnb_l1cantrips.qd~) BEGIN
	OUTER_SET L1C = 1
END 
ACTION_IF !(FILE_EXISTS_IN_GAME ~qdtnb_l1cantrips.qd~) BEGIN
	OUTER_SET L1C = 0 
END 

//COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slot1.spl~ ~override/d5absp1.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5absp1.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5absp1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~d5abspw~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 19 parameter2 = 105 timing = 0 duration = 1 STR_VAR resource = ~d5absp1~ END
//COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slot1.spl~ ~override/d5absp2.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5absp2.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5absp2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 5 parameter2 = 5 timing = 9 STR_VAR resource = ~d5abspb~ END
//COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slot1.spl~ ~override/d5absp3.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5absp3.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5absp3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 19 parameter2 = 5 timing = 9 STR_VAR resource = ~d5absps~ END

COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.eff~ ~override/d5abspw.eff~
	WRITE_ASCII 0x30 ~d5abspw~ #8
COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.eff~ ~override/d5abspb.eff~
	WRITE_ASCII 0x30 ~d5abspb~ #8
COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.eff~ ~override/d5absps.eff~
	WRITE_ASCII 0x30 ~d5absps~ #8

//COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.spl~ ~override/d5absp.spl~

COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.spl~ ~override/d5abspw.spl~ 	// 	spell slot modifications for wizards
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 13 parameter2 = 129 target = 1 timing = 1 STR_VAR resource = ~d5intwl~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 13 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 14 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwn~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 15 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwo~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 16 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 17 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 18 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 19 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intws~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 20 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 21 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 22 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 23 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intww~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 24 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwx~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 25 parameter2 = %int_slots% target = 1 timing = 1 STR_VAR resource = ~d5intwy~ END
COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.spl~ ~override/d5abspb.spl~ 	// 	spell slot modifications for bards
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 13 parameter2 = 133 target = 1 timing = 1 STR_VAR resource = ~d5chrbl~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 13 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 14 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbn~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 15 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbo~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 16 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 17 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 18 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 19 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbs~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 20 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 21 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 22 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 23 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 24 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrbx~ END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 25 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrby~ END
COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.spl~ ~override/d5absps.spl~ 	// 	spell slot modifications for sorcerers
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 13 parameter2 = 133 target = 1 timing = 1 STR_VAR resource = ~d5chrsl~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 13 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrsm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 14 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrsn~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 15 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrso~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 16 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrsp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 17 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrsq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 18 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrsr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 19 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrss~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 20 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrst~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 21 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrsu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 22 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrsv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 23 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrsw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 24 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrsx~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 25 parameter2 = %chr_slots% target = 1 timing = 1 STR_VAR resource = ~d5chrsy~ END

  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwl.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5intwl~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 127 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 127 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwm.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5intwm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 127 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (126 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwn.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5intwn~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 126 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (126 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwo.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5intwo~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 126 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (124 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwp.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5intwp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 124 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (124 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwq.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5intwq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 124 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (120 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwr.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5intwr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 124 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (112 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intws.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5intws~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 120 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (112 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwt.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5intwt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 120 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (96 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwu.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5intwu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 112 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (96 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwv.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5intwv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 112 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (64 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intww.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5intww~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 96 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (64 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwx.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5intwx~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (96 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5intwy.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5intwy~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (64 + %L1C%) target = 1 timing = 0 duration = 7 END

  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbl.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrbl~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 63 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 63 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbm.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrbm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 63 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (62 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbn.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrbn~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 62 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (62 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbo.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrbo~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 62 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (60 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbp.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrbp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 60 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (60 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbq.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrbq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 60 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (56 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbr.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrbr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 60 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (48 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbs.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrbs~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 56 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (48 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbt.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrbt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 56 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (32 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbu.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrbu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 48 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (32 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbv.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrbv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (48 + %L1C%) target = 1 timing = 0 duration = 7 END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 64 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbw.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrbw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (32 + %L1C%) target = 1 timing = 0 duration = 7 END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 64 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrbx.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrbx~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (32 + %L1C%) target = 1 timing = 0 duration = 7 END
//  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrby.spl~
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrby~ END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (64 + %L1C%) target = 1 timing = 0 duration = 7 END

  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsl.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrsl~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 31 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 31 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsm.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrsm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 31 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (30 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsn.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrsn~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 30 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (30 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrso.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrso~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 30 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (28 + %L1C%) target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsp.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrsp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 30 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (28 + %L1C%) target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 191 parameter1 = 1 parameter2 = 0 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsq.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrsq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 28 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (28 + %L1C%) target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 191 parameter1 = 1 parameter2 = 0 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsr.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrsr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 28 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (24 + %L1C%) target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 191 parameter1 = 1 parameter2 = 0 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrss.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrss~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 28 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (24 + %L1C%) target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 191 parameter1 = 2 parameter2 = 0 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrst.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrst~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 24 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (24 + %L1C%) target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 191 parameter1 = 2 parameter2 = 0 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsu.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrsu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 24 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (16 + %L1C%) target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 191 parameter1 = 2 parameter2 = 0 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsv.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrsv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 24 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (16 + %L1C%) target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 191 parameter1 = 3 parameter2 = 0 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsw.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrsw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 16 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (16 + %L1C%) target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 191 parameter1 = 3 parameter2 = 0 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsx.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrsx~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (16 + %L1C%) target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 191 parameter1 = 3 parameter2 = 0 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5chrsy.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5chrsy~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = (16 + %L1C%) target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 191 parameter1 = 4 parameter2 = 0 target = 1 timing = 0 duration = 7 END


// 		only sorcerer bonuses - wild mage is in kitlist so will add wizard bonuses below
ACTION_IF FILE_EXISTS_IN_GAME ~clabma01.2da~ BEGIN
	APPEND ~clabma01.2da~ ~XTRA_SPL    AP_D5ABSP3  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END
	 
ACTION_IF FILE_EXISTS_IN_GAME ~clabba01.2da~ BEGIN
	APPEND ~clabba01.2da~ ~XTRA_SPL    AP_D5ABSP2  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END

/* 		no need, dragon disciple uses this and is in kitlist.2da
ACTION_IF FILE_EXISTS_IN_GAME ~clabso01.2da~ BEGIN
	APPEND ~clabso01.2da~ ~XTRA_SPL    AP_D5ABSP3  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END
*/

// ***** need to rename these! ...I think
// ...also probably should make these in semi_spont.tpa

/*
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5zislt.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5zislt~ END

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5zjslt.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5zjslt~ END
*/

COPY_EXISTING ~kitlist.2da~ ~override~
//  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS 10 rows
  FOR (row = 3 ; row < rows ; ++row) BEGIN
	READ_2DA_ENTRY %row% 1 10 modname
	READ_2DA_ENTRY %row% 5 10 modclab
	READ_2DA_ENTRY %row% 8 10 modclass
    PATCH_IF (FILE_EXISTS_IN_GAME ~%modclab%.2da~) BEGIN
	  PATCH_IF (%modclass% = 1) AND !(~%modname%~ STRING_MATCHES_REGEXP ~C0SA+~ = 0) AND !(~%modclab%~ STRING_EQUAL_CASE ~D5ACNST~) AND !(~%modclab%~ STRING_EQUAL_CASE ~D5_MANA~) BEGIN	// mage kits
	    INNER_ACTION BEGIN
		  APPEND ~%modclab%.2da~ ~XTRA_SPL    AP_D5ABSP1  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
	    END
	  END
	  PATCH_IF (%modclass% = 5) AND !(~%modname%~ STRING_MATCHES_REGEXP ~C0SA+~ = 0) BEGIN 	// bard kits
	    INNER_ACTION BEGIN
		  APPEND ~%modclab%.2da~ ~XTRA_SPL    AP_D5ABSP2  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
	    END
	  END
	  PATCH_IF (%modclass% = 19) AND !(~%modname%~ STRING_MATCHES_REGEXP ~C0SA+~ = 0) BEGIN 	// sorcerer kits
	    INNER_ACTION BEGIN
		  APPEND ~%modclab%.2da~ ~XTRA_SPL    AP_D5ABSP3  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
	    END
	  END
	  PATCH_IF (%modclass% = 1) OR (%modclass% = 5) OR (%modclass% = 19) OR (%modclass% = 7) OR (%modclass% = 10) OR (%modclass% = 13) OR (%modclass% = 14) OR (%modclass% = 17) BEGIN
	    PATCH_IF (~%modname%~ STRING_MATCHES_REGEXP ~C0SA+~ = 0) BEGIN	// shadow adept arcane kits
		  INNER_ACTION BEGIN
		    APPEND ~%modclab%.2da~ ~XTRA_SPL    AP_D5ZISLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
		    APPEND ~%modclab%.2da~ ~XTRA_SPL    AP_D5ZJSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
		  END
	    END
	  END
	END
  END
BUT_ONLY


// CHA bonus spells for multisorc_____________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5sorc.2da~) BEGIN

  LAM semi_cha_slots

  COPY_EXISTING ~d5xrfsh.spl~ ~override~
	PHP_EACH cha_nums_lets AS cha => slot BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 10 opcode = 326 target = 1 parameter1 = %cha% parameter2 = 132 timing = 1 STR_VAR resource = EVAL ~d5chas%slot%~ END
	END
	PHP_EACH cha_nums_lets AS cha => slot BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 1 opcode = 321 target = 1 timing = 1 STR_VAR resource = EVAL ~d5chas%slot%~ END
	END
  IF_EXISTS BUT_ONLY

END

// fix multisorc spell table just in case_____________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~qdtnb_mcsrc.qd~) BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~d5xltsr.spl~) BEGIN
    DELETE ~d5xltsr.spl~
  END
  LAF arcane_casting_slots STR_VAR slot_table = ~mxsplsrc~ table_spl = ~d5xltsr~ END
END


// CHA bonus spells for manasorc______________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5_mana.2da~) BEGIN

  LAM semi_cha_slots

  COPY_EXISTING ~d5mrfrsh.spl~ ~override~
	PHP_EACH cha_nums_lets AS cha => slot BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 10 opcode = 326 target = 1 parameter1 = %cha% parameter2 = %chr_slots% timing = 1 STR_VAR resource = EVAL ~d5cham%slot%~ END
	END
	PHP_EACH cha_nums_lets AS cha => slot BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 1 opcode = 321 target = 1 timing = 1 STR_VAR resource = EVAL ~d5cham%slot%~ END
	END
  IF_EXISTS BUT_ONLY

END


COPY ~%MOD_FOLDER%/lib/semi_spont/d5_marker.d5~ ~override/d5__abil_spells.d5~

END


// WIS bonus spells for priests_______________________________________________________
//
COPY ~%MOD_FOLDER%/data/stats/mxsplwis.2da~ ~override~

STRING_SET 9586 @20005 


// WIS bonus spells for shaman________________________________________________________
//
ACTION_FOR_EACH shaman_table IN ~mxsplshm~ BEGIN
  COPY_EXISTING ~%shaman_table%.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 0; row < rows; ++row) BEGIN
	  FOR (col = 1; col < 8; ++col) BEGIN
		READ_2DA_ENTRY_FORMER rows row col slots
		PATCH_IF (slots > 0) BEGIN
		  SET_2DA_ENTRY row col cols (slots + 2)
		END
	  END
	END
  IF_EXISTS BUT_ONLY
END

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5absp4.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5absp4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 21 parameter2 = 5 timing = 9 STR_VAR resource = ~d5absph~ END

COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.eff~ ~override/d5absph.eff~
	WRITE_ASCII 0x30 ~d5absph~ #8

APPEND ~splprot.2da~ ~D5_WIS_SLOTS%TAB%39%TAB%-1%TAB%1~ UNLESS ~D5_WIS_SLOTS~

COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols 
	READ_2DA_ENTRIES_NOW rows cols   
	FOR (row = 1; row < rows; ++row) BEGIN 
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ 
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_WIS_SLOTS~ BEGIN
	    SET wis_slots = %row%
	  END
	END
BUT_ONLY

COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.spl~ ~override/d5absph.spl~ 	// 	spell slot modifications for shamans
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 13 parameter2 = 131 target = 1 timing = 1 STR_VAR resource = ~d5wishl~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 13 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wishm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 14 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wishn~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 15 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wisho~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 16 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wishp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 17 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wishq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 18 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wishr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 19 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wishs~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 20 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wisht~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 21 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wishu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 22 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wishv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 23 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wishw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 24 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wishx~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 25 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wishy~ END

  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wishl.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wishl~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 127 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 127 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wishm.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wishm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 127 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 126 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wishn.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wishn~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 126 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 126 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wisho.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wisho~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 126 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 124 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wishp.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wishp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 124 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 124 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wishq.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wishq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 124 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 120 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wishr.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wishr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 124 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 112 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wishs.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wishs~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 120 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 112 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wisht.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wisht~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 120 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 96 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wishu.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wishu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 112 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 96 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wishv.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wishv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 112 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 64 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wishw.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wishw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 96 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 64 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wishx.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wishx~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 96 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wishy.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wishy~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 64 target = 1 timing = 0 duration = 7 END

ACTION_IF FILE_EXISTS_IN_GAME ~clabsh01.2da~ BEGIN
	APPEND ~clabsh01.2da~ ~XTRA_SPL    AP_D5ABSP4  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabshgs.2da~ BEGIN
	APPEND ~clabshgs.2da~ ~XTRA_SPL    AP_D5ABSP4  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabpr01.2da~ BEGIN
	APPEND ~clabpr01.2da~ ~XTRA_SPL    AP_D5ABSP4  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabdr01.2da~ BEGIN
	APPEND ~clabdr01.2da~ ~XTRA_SPL    AP_D5ABSP4  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabpa01.2da~ BEGIN
	APPEND ~clabpa01.2da~ ~XTRA_SPL    AP_D5ABSP4  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabrn01.2da~ BEGIN
	APPEND ~clabrn01.2da~ ~XTRA_SPL    AP_D5ABSP4  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END

COPY_EXISTING ~kitlist.2da~ ~override~
//  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS 10 rows
  FOR (row = 3 ; row < rows ; ++row) BEGIN
	READ_2DA_ENTRY %row% 1 10 modname
	READ_2DA_ENTRY %row% 5 10 modclab
	READ_2DA_ENTRY %row% 8 10 modclass
	PATCH_IF (%modclass% = 21) OR (%modclass% = 3) OR (%modclass% = 11) OR (%modclass% = 6) OR (%modclass% = 12) BEGIN	// divine kits
	  INNER_ACTION BEGIN
		APPEND ~%modclab%.2da~ ~XTRA_SPL    AP_D5ABSP4  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
	  END
	END
  END
BUT_ONLY

// adjust joinable NPC slots__________________________________________________________
//
LAM JOINABLE_NPC_ARRAYS

ACTION_PHP_EACH JOINABLE_NPC_ARRAY AS cre => dv BEGIN
//  PRINT ~%cre% = non-joinable~ 
  COPY_EXISTING ~%cre%~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
      GET_OFFSET_ARRAY slot_array CRE_V10_SPELL_MEM_INFO
      PHP_EACH slot_array AS inf => slot_off BEGIN
        READ_SHORT slot_off spl_level
        READ_SHORT (slot_off + 0x02) spl_slots
        READ_SHORT (slot_off + 0x06) spl_type
        PATCH_IF (spl_slots > 0) AND (spl_level < 7) AND !(spl_type = 2) BEGIN
          WRITE_SHORT (slot_off + 0x02) (spl_slots + 2)
        END
      END
    END
  BUT_ONLY
END
//____________________________________________________________________________________


END 	//	end define function


//____________________________________________________________________________________
//____________________________________________________________________________________


DEFINE_ACTION_FUNCTION 5e_no_priest_mem_bonus BEGIN 

  ACTION_IF (MOD_IS_INSTALLED ~5E_spellcasting.tp2~ ~100~) BEGIN
    COPY ~%MOD_FOLDER%/data/stats/mxsplwis_0.2da~ ~override/mxsplwis.2da~
  END

/* ...what is all this for? why not just zero out the table??

  COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5absp5.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5absp5~ END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 21 parameter2 = 5 timing = 9 STR_VAR resource = ~d5abspp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 11 parameter2 = 5 timing = 9 STR_VAR resource = ~d5abspp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 3 parameter2 = 5 timing = 9 STR_VAR resource = ~d5abspp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 8 parameter2 = 5 timing = 9 STR_VAR resource = ~d5abspp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 14 parameter2 = 5 timing = 9 STR_VAR resource = ~d5abspp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 15 parameter2 = 5 timing = 9 STR_VAR resource = ~d5abspp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 16 parameter2 = 5 timing = 9 STR_VAR resource = ~d5abspp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 17 parameter2 = 5 timing = 9 STR_VAR resource = ~d5abspp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 18 parameter2 = 5 timing = 9 STR_VAR resource = ~d5abspp~ END

  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.eff~ ~override/d5abspp.eff~
	WRITE_ASCII 0x30 ~d5abspp~ #8

  APPEND ~splprot.2da~ ~D5_WIS_SLOTS%TAB%39%TAB%-1%TAB%1~ UNLESS ~D5_WIS_SLOTS~

  COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols 
	READ_2DA_ENTRIES_NOW rows cols   
	FOR (row = 1; row < rows; ++row) BEGIN 
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ 
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_WIS_SLOTS~ BEGIN
	    SET wis_slots = %row%
	  END
	END
  BUT_ONLY

  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slots.spl~ ~override/d5abspp.spl~ 	// 	spell slot modifications for shamans
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 13 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wispm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 14 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wispn~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 15 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wispo~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 16 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wispp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 17 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wispq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 18 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wispr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 19 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wisps~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 20 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wispt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 21 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wispu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 22 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wispv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 23 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wispw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 24 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wispx~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 parameter1 = 25 parameter2 = %wis_slots% target = 1 timing = 1 STR_VAR resource = ~d5wispy~ END

  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wispm.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wispm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 1 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wispn.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wispn~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 3 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wispo.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wispo~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 3 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 1 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wispp.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wispp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 7 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 1 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wispq.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wispq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 7 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 3 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wispr.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wispr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 15 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 3 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wisps.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wisps~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 15 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 7 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wispt.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wispt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 31 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 7 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wispu.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wispu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 31 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 15 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wispv.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wispv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 63 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 15 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wispw.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wispw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 63 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 31 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wispx.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wispx~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 127 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 31 target = 1 timing = 0 duration = 7 END
  COPY ~%MOD_FOLDER%/data/ability_bonuses/d5_slotx.spl~ ~override/d5wispy.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 parameter2 = 0 target = 1 timing = 1 STR_VAR resource = ~d5wispy~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 127 target = 1 timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 parameter1 = (0 - 1) parameter2 = 63 target = 1 timing = 0 duration = 7 END

/* no, apply this in d5zzini
  ACTION_IF FILE_EXISTS_IN_GAME ~clabsh01.2da~ BEGIN
	APPEND ~clabpr01.2da~ ~XTRA_SPL    AP_D5ABSP5  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
  END
  ACTION_IF FILE_EXISTS_IN_GAME ~clabshgs.2da~ BEGIN
	APPEND ~clabdr01.2da~ ~XTRA_SPL    AP_D5ABSP5  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
  END

  COPY_EXISTING ~kitlist.2da~ ~override~
//  COUNT_2DA_COLS cols
    COUNT_2DA_ROWS 10 rows
    FOR (row = 3 ; row < rows ; ++row) BEGIN
	  READ_2DA_ENTRY %row% 1 10 modname
	  READ_2DA_ENTRY %row% 5 10 modclab
	  READ_2DA_ENTRY %row% 8 10 modclass
	  PATCH_IF (%modclass% = 3) OR (%modclass% = 11) BEGIN	// priest kits
	    PATCH_IF (FILE_EXISTS_IN_GAME ~%modclab%.2da~) BEGIN
	      PATCH_IF !(~%modname%~ STRING_MATCHES_REGEXP ~C0SA+~ = 0) AND !(~%modname%~ STRING_EQUAL_CASE ~~) BEGIN	// shadow adept arcane kits
	        INNER_ACTION BEGIN
		      APPEND ~%modclab%.2da~ ~XTRA_SPL    AP_D5ABSP5  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
	        END
	      END
	    END
	  END
    END
  BUT_ONLY
*/

  ACTION_IF (FILE_EXISTS_IN_GAME ~d5zzini.spl~) BEGIN
    COPY_EXISTING ~d5zzini.spl~ ~override~
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 4 opcode = 326 target = 1 parameter1 = 3 parameter2 = 105 timing = 1 STR_VAR resource = ~d5absp5~ END
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 4 opcode = 326 target = 1 parameter1 = 6 parameter2 = 105 timing = 1 STR_VAR resource = ~d5absp5~ END
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 4 opcode = 326 target = 1 parameter1 = 8 parameter2 = 105 timing = 1 STR_VAR resource = ~d5absp5~ END
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 4 opcode = 326 target = 1 parameter1 = 11 parameter2 = 105 timing = 1 STR_VAR resource = ~d5absp5~ END
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 4 opcode = 326 target = 1 parameter1 = 12 parameter2 = 105 timing = 1 STR_VAR resource = ~d5absp5~ END
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 4 opcode = 326 target = 1 parameter1 = 14 parameter2 = 105 timing = 1 STR_VAR resource = ~d5absp5~ END
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 4 opcode = 326 target = 1 parameter1 = 15 parameter2 = 105 timing = 1 STR_VAR resource = ~d5absp5~ END
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 4 opcode = 326 target = 1 parameter1 = 16 parameter2 = 105 timing = 1 STR_VAR resource = ~d5absp5~ END
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 4 opcode = 326 target = 1 parameter1 = 17 parameter2 = 105 timing = 1 STR_VAR resource = ~d5absp5~ END
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 4 opcode = 326 target = 1 parameter1 = 18 parameter2 = 105 timing = 1 STR_VAR resource = ~d5absp5~ END
	BUT_ONLY
  END
*/

END 	//	end define function

//____________________________________________________________________________________

